### ISSUE TITLE
Why do you encode all of your scripts?

### ISSUE THREAD

**Issue by demongamer3001** [Blank-c/Blank-Grabber#10]

**Comment by Blank-c** [comment]
Its because someone stole my code long time ago and pretended it to be his own.

**Comment by demongamer3001** [comment]
Just add a LICENSE or dont upload it to github

**Comment by Blank-c** [comment]
idk if I can copyright claim on github :3

**Comment by demongamer3001** [comment]
Yes you can if you have a license i think
