### ISSUE TITLE
Webhook problem, and discord crash.

### ISSUE THREAD

**Issue by Talalcs** [Blank-c/Blank-Grabber#103]
Whenever i run it, it doesn't send anything to my webhook and my discord crashes and restarts for some reason.

**Comment by Talalcs** [comment]
can you help me?

**Comment by Blank-c** [comment]
Because of the discord injection, your discord crashes after its files are modified.

Can you check your `%temp%` folder for some file named `Blank-<something>.zip`. Is it there?

**Comment by Talalcs** [comment]
alright

**Comment by Blank-c** [comment]
Please continue this in #98

**Comment by Talalcs** [comment]
> Because of the discord injection, your discord crashes after its files are modified.
> 
> Can you check your `%temp%` folder for some file named `Blank-<something>.zip`. Is it there?

Nope there is nothing.

**Comment by Talalcs** [comment]
alright

**Comment by Talalcs** [comment]
user?

**Comment by Blank-c** [comment]
in the readme

**Comment by Talalcs** [comment]
sent
