### ISSUE TITLE
how to import cookies?

### ISSUE THREAD

**Issue by ImPixeluwu** [Blank-c/Blank-Grabber#109]
question in title

**Comment by Blank-c** [comment]
Here, I found a random video that might help you: https://youtu.be/H3OTcR2vKxk

**Comment by Blank-c** [comment]
The VPN is to make sure the providers won't change the login cookies when loging in from a different country. You can use any VPN or even no VPN at all.

**Comment by DogusCzk** [comment]
use firefox cookie manager
