### ISSUE TITLE
0 password

### ISSUE THREAD

**Issue by DogusCzk** [Blank-c/Blank-Grabber#112]
![image](https://user-images.githubusercontent.com/123574822/215293912-bbbe6aff-b70c-43cf-a8b3-3e33fe039c62.png)
it sayin 110 password but there is no password why

**Comment by DogusCzk** [comment]
there is  more like this

**Comment by Blank-c** [comment]
Is the passwords.txt inside? Is it empty?

**Comment by DogusCzk** [comment]
Although it says 118, it was empty when I downloaded the password.txt

**Comment by DogusCzk** [comment]
After that, it came 1 more time and this time it was written 0 in the password section.

**Comment by Blank-c** [comment]
> After that, it came 1 more time and this time it was written 0 in the password section.

maybe this time it didnt get any passwords, often caused by AVs

**Comment by Blank-c** [comment]
> Although it says 118, it was empty when I downloaded the password.txt

Happens sometime like I said, due to AVs or some error with the exe (since its packed and not compiled to exe)

**Comment by Blank-c** [comment]
Like I said, thats basee on their PC and idk why it happened on the first place, the above are all possibilities. So, unless one can provide a way to reproduce this error, I can't help.
