### ISSUE TITLE
Unhandled exception in script

### ISSUE THREAD

**Issue by Carbneth** [Blank-c/Blank-Grabber#115]
![resim](https://user-images.githubusercontent.com/31568154/216303397-53b43dff-a3ea-431d-af98-eb53e75292b5.png)

python is 3.10.8

**Comment by Blank-c** [comment]
Reinstall python and tell me what you did before this happened.

**Comment by Carbneth** [comment]
> Reinstall python and tell me what you did before this happened.

Okay fixed the issue, you have to bind an executeable. I had it blank thinking it could create empty executeable that does nothing but grabs.

You can include that in readme or limit build without binding executeable :)

**Comment by Blank-c** [comment]
> > Reinstall python and tell me what you did before this happened.
> 
> Okay fixed the issue, you have to bind an executeable. I had it blank thinking it could create empty executeable that does nothing but grabs.
> 
> You can include that in readme or limit build without binding executeable :)

Not sure what you mean, are you saying that you need to bind an executable in order for it to work? If this is what you think, NO, you are not right. You can build the grabber without binding the executable. This is an error with your python installation I guess. You can try this on a VM.
