### ISSUE TITLE
Blank grabber password bug

### ISSUE THREAD

**Issue by DtKdPython** [Blank-c/Blank-Grabber#118]
![image](https://user-images.githubusercontent.com/122708389/216850992-ecc9c798-3e8f-405d-bd16-f66d973b10ae.png)
i have lot of saved passwords in my chrome but it says 0 passwords and there isnt any saved passwords in the folder

**Comment by Blank-c** [comment]
Hey, can you download [this tool](https://www.nirsoft.net/utils/web_browser_password.html) and run it to see if your passwords are shown or not. It would confirm if your passwords are accessible or not.

**Comment by Blank-c** [comment]
Also, does your zip file contain any error logs?

**Comment by DogusCzk** [comment]
I had a similar problem

**Comment by Blank-c** [comment]
@DogusCzk can you do the things I have said above, and tell whats the result.

**Comment by Blank-c** [comment]
@DogusCzk @DtKdPython Did the above method worked?

**Comment by DtKdPython** [comment]
@Blank-c i ran the WebBrowserPassView.exe and the passwords are shown

**Comment by DtKdPython** [comment]
i think i found the issue when i run the main.py without changing anything except the webhook, the passwords are shown when i modify some settings the passwords arent shown

**Comment by DtKdPython** [comment]
can i have your discord so we can test your grabber?

**Comment by Blank-c** [comment]
The grabber is meant to be converted to exe and not directly as script. Thats why this happen.
