### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by deceased1** [Blank-c/Blank-Grabber#120]
what is block av sites , and what is an AV site

**Comment by deceased1** [comment]
also what does the discord injection do

**Comment by deceased1** [comment]
i ran my own file with all settings how do i revert everything it changed

**Comment by Blank-c** [comment]
Check [this](https://github.com/Blank-c/Blank-Grabber/issues/55) for discord injection and startup removal. For unblocking AV sites, see [this](https://github.com/Blank-c/Blank-Grabber/issues/117)
