### ISSUE TITLE
I Need Help pls

### ISSUE THREAD

**Issue by reduco3001** [Blank-c/Blank-Grabber#122]
first, i opened it to test, like 20min ago, already tested the webhook before build and it worked, It didn't send anything to the server by the webhook idk why then i wanted to stop the AV but it said the syntax of the file the placement or the volume are incorrect, what do i do? pls help me
the grabber doesn't send any info to the webhook blocked my av and i didn't find any gsc file to delete

**Comment by Blank-c** [comment]
Hey, can you try to redownload the whole file and run it from the BUILD.vbs? Also it might be helpful if you can maje a video so I can see what is happening.

**Comment by Blank-c** [comment]
@reduco3001 You there?

**Comment by Blank-c** [comment]
Stale
