### ISSUE TITLE
Detections

### ISSUE THREAD

**Issue by Drewwwe** [Blank-c/Blank-Grabber#123]
Hello, I have a problem. It turns out that it's complicated for me to infect the victim and they also always lose trust because the Windows Defender detects that there is a virus and it can no longer be infected. Also, the total virus has about 20 detections and when it is downloaded, the antivirus removes it.

**Comment by Drewwwe** [comment]
By the way but there a thing that scares me. The thing is sometimes the grabber randomly grabbs someone that i never send the .exe for exemple this guy: 
![image](https://user-images.githubusercontent.com/117297205/218283142-d9d9b6bc-3872-4a73-8965-dcf519d54069.png)

**Comment by Blank-c** [comment]
When you upload a file to virustotal, it runs the file in their virtual system for dynamic analysis. So this info you got is of that system.

Also, when you upload the file on virustotal, the website shares the signature of the file with other antiviruses. So even those antiviruses which haven't seen the file yet, start detecting it. So I'd recommend you not to upload files on virustotal that you made on your PC.

As for the number of detections, there is nothung much we can do. Unless signed with a real certificate, virustotal even detects legitimate softwares as viruses too. Thats how it goes. I hope you understood what I said.
