### ISSUE TITLE
Not grabbing credit cards cvv

### ISSUE THREAD

**Issue by DogusCzk** [Blank-c/Blank-Grabber#127]
All credit cards I've looked at don't have CVV, is this normal?

**Comment by Blank-c** [comment]
Chrome doesn't store CVV

**Comment by Blank-c** [comment]
![image](https://user-images.githubusercontent.com/94945186/218764128-cab96b83-55c8-476c-900d-c564897ff851.png)
this is all what it stores

**Comment by DogusCzk** [comment]
The card has no meaning without cvv. Is it possible to use it without cvv?
