### ISSUE TITLE
ERORRRS!!!!

### ISSUE THREAD

**Issue by PeakScripts** [Blank-c/Blank-Grabber#129]
Traceback (most recent call last):
  File "<string>", line 346, in newfunc
  File "<string>", line 1938, in directoryTree
ValueError: list.remove(x): x not in list
---------------------------------------------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "<string>", line 346, in newfunc
  File "<string>", line 2062, in captureDiscordTokens
  File "<string>", line 1326, in getTokens
AttributeError: 'str' object has no attribute 'get'
---------------------------------------------------------------------------------------------------------------------------------------------------
Line 46 : grab : OSError : screen grab failed
Line 19 : encode : UnicodeEncodeError : 'charmap' codec can't encode characters in position 1091-1092: character maps to <undefined>
---------------------------------------------------------------------------------------------------------------------------------------------------

**Comment by Blank-c** [comment]
Can you give me your discord username or send me a request. I'd like to discuss something with you. Also what is your [client version](https://support.discord.com/hc/en-us/articles/360052735334-How-do-I-find-my-client-info-#:~:text=Tap%20your%20avatar%20to%20bring,is%20your%20current%20Client%20Version.)?

**Comment by Blank-c** [comment]
Can you update and check if you still get the errors?

**Comment by Blank-c** [comment]
Closing cuz dead
