### ISSUE TITLE
error

### ISSUE THREAD

**Issue by yigit311** [Blank-c/Blank-Grabber#130]
Error while creating virtual environment ("python -m venv env"): access denied

**Comment by Blank-c** [comment]
Turn off AV and use the `BUILD.vbs` not the `builder.py`

**Comment by yigit311** [comment]
same error : (

**Comment by Blank-c** [comment]
Can you turn off AV and run the command `python -m venv env` and see if that still gave error? Also on which drive and location are you trying to build it?

**Comment by yigit311** [comment]
I run the command in cmd and not give a error

**Comment by Blank-c** [comment]
The only possible reason which comes to my mind in this case is that your AV/Defender is blocking the file. Are you sure you turned off your AV or Real time protection of your defender?

**Comment by yigit311** [comment]
nothing change but thanks

**Comment by Blank-c** [comment]
You should try to build on a different folder, like desktop or somewhere. If still don't work, you can use an online [vm](https://app.apponfly.com/trial)

**Comment by Blank-c** [comment]
Closing because can't reproduce the issue. And the possible fixes are stated.
