### ISSUE TITLE
Error whilst stealing passwords

### ISSUE THREAD

**Issue by deceased1** [Blank-c/Blank-Grabber#132]
Whenever i get a target i either get all there passwords with no error logs or no passwords with this error:

`Line 19 : encode : UnicodeEncodeError : 'charmap' codec can't encode character '\u200b' in position 14040: character maps to <undefined>
Line 1338 : getTokens : AttributeError : 'str' object has no attribute 'get'`

pls fix

**Comment by deceased1** [comment]
> Does this happen in your PC too? Also are you using the latest version.

na it doesnt on my pc and it only happens half of the time, also ill update to the latest version

**Comment by deceased1** [comment]
btw i recently reset my pc and now im getting this error 
`Error while creating virtual environment ("python -m venv env"): Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.`

**Comment by Blank-c** [comment]
in the windows search app, search for "Manage app execution aliases" and turn off every "python", "pip" etc. (basically every python related option). And then install python from their official website.

**Comment by deceased1** [comment]
it doesnt show the passwords it latest versions aswell contact me wanted#5538

**Comment by deceased1** [comment]
nvm fixed it

**Comment by deceased1** [comment]
> in the windows search app, search for "Manage app execution aliases" and turn off every "python", "pip" etc. (basically every python related option). And then install python from their official website.

when the grabber grabs someones roblox cookies it doesnt grab the correct cookie. The first part is correct (`_|WARNING:-DO-NOT-SHARE-THIS.--Sharing-this-will-allow-someone-to-log-in-as-you-and-to-steal-your-ROBUX-and-items.|_`) but then there is a random string of numbers and letters (i am not sure how long this string is) and the string that the grabber sends is `32` characters over the ammount it should need.

**Comment by Blank-c** [comment]
Oh. Damn, I'll look into this problem soon. My exams are currently going on so I might not be available most of the time. But I'll contact you when I get time.

**Comment by deceased1** [comment]
> Oh. Damn, I'll look into this problem soon. My exams are currently going on so I might not be available most of the time. But I'll contact you when I get time.

im really confused, I've just downloaded my own file and it hasnt done this it got my cookie perfectly but then i beam these other people and the cookie is like 32 characters incorrect..

**Comment by Blank-c** [comment]
If you are talking about the roblox cookie, the grabber searches it in a registry of the system. It can be possible that the key there is incorrect and its what you are getting.

**Comment by deceased1** [comment]
> If you are talking about the roblox cookie, the grabber searches it in a registry of the system. It can be possible that the key there is incorrect and its what you are getting.

that could be it, if it is possible can you make it steal directly from the browser itself? (in the f12/ctrl+shift+i application, cookies folder) I am pretty sure roblox has updated the way there cookies work which is why the registry has made it weird and incorrect.

**Comment by Blank-c** [comment]
It already steals from chrome browser. In the chrome cookies.txt, there should be roblox cookie too

**Comment by deceased1** [comment]
> It already steals from chrome browser. In the chrome cookies.txt, there should be roblox cookie too

it does the same things it is an incorrect cookie

**Comment by Blank-c** [comment]
If the incorrect cookies is in the cookies.txt, then it means that the same (incorrect) cookie is stored in the victim's browser.

**Comment by Blank-c** [comment]
Stale
