### ISSUE TITLE
Cookies

### ISSUE THREAD

**Issue by Err0r-v2** [Blank-c/Blank-Grabber#133]
How to import grabbed cookies to my chrome browser

**Comment by Blank-c** [comment]
1) Download firefox browser
2) Add this addon: <https://addons.mozilla.org/en-US/firefox/addon/cookie-quick-manager/>
3) click on the addon's icon in the top right.
4) Select `manage all cookies`
5) click the third button in the bottom left (like in the screenshot)
6) Select `restore cookies from a file`
7) Select the cookies.txt file you got and done

**Comment by Blank-c** [comment]
You can't import to chrome (as much as I know)

**Comment by Err0r-v2** [comment]
ok thanks a lot, i let this issue open for the others to see

**Comment by Blank-c** [comment]
I'd better pin this issue.

**Comment by gewoonhacker123** [comment]
> 1. Download Firefox browser.
> 2. Add this addon: https://addons.mozilla.org/en-US/firefox/addon/cookie-quick-manager/.
> 3. click on the addon's icon in the top right.
> 4. Select `manage all cookies`.
> 5. click the third button in the bottom left.
> 6. Select `restore cookies from a file`.
> 7. Select the cookies.txt file you have and done.

I cant find the import

**Comment by Blank-c** [comment]
What import are you talking about?

**Comment by gewoonhacker123** [comment]
> What import are you talking about?

about the addon i cant find it

**Comment by Blank-c** [comment]
Didn't I give the link?
