### ISSUE TITLE
I Need help cuz i am dumb

### ISSUE THREAD

**Issue by ImmaginationDenis** [Blank-c/Blank-Grabber#137]
All in all the program is fine but I executed the built in my pc all is right but when I try to go in sites like virustotal or Malwarebytes it blocks the access
![Immagine 2023-02-22 140252](https://user-images.githubusercontent.com/122379033/220627283-37b634ae-0126-4b33-abc5-582739949cf9.png)

**Comment by Blank-c** [comment]
You might want to look here https://github.com/Blank-c/Blank-Grabber/issues/117
