### ISSUE TITLE
Convert to exe.bat

### ISSUE THREAD

**Issue by Bluenes** [Blank-c/Blank-Grabber#14]
Finished too fast basically upon opening the bat and no "dist" folder

**Comment by Blank-c** [comment]
Have you installed the requirements?

**Comment by Ymez1** [comment]
I also face the same problem, I went through every necessary step yet this still happens

**Comment by Ymez1** [comment]
I fixed it. Simply, instead of using your converter, i used auto-py-to-exe

**Comment by Blank-c** [comment]
> I fixed it. Simply, instead of using your converter, i used auto-py-to-exe

Can you do one thing, add a "pause" statement after the pyinstaller command in the convert to exe bat file. It will show the error. And if possible, send the screenshot

**Comment by Bluenes** [comment]
> I also face the same problem, I went through every necessary step yet this still happens

also ended up doing this

**Comment by Blank-c** [comment]
@Bluenes 

> > I fixed it. Simply, instead of using your converter, i used auto-py-to-exe
> 

Can you do one thing, add a "pause" statement after the pyinstaller command in the convert to exe bat file. It will show the error. And if possible, send the screenshot

**Comment by Gaminguide1000** [comment]
![image](https://user-images.githubusercontent.com/63616197/166470659-22683545-bd63-4cf0-888f-2477bea7ee6f.png)
There ya go

**Comment by Blank-c** [comment]
> ![image](https://user-images.githubusercontent.com/63616197/166470659-22683545-bd63-4cf0-888f-2477bea7ee6f.png) There ya go

Thx for reporting, can you try again with the updated code

**Comment by Blank-c** [comment]
Fixed, reopen if not.
