### ISSUE TITLE
no build

### ISSUE THREAD

**Issue by jamiekarvans** [Blank-c/Blank-Grabber#140]
hi there is no build after i enter webhook and click the button, only dist folder will open and it's empty

**Comment by Blank-c** [comment]
Does it show any error while building? Also make sure your Antivirus is off when you press build.

**Comment by jamiekarvans** [comment]
Hey, no there is no error
And I have totally disabled anti virus,
It used to create no problem but after latest update there is no build.
I don't know either the problem is with source code on from my PC but I
have uninstalled and installed python again and still no luck.

**Comment by Blank-c** [comment]
I tried it on AppsOnFly VM and it built and ran perfectly. I don't see any problem with the code either. Which OS are you using?

**Comment by jamiekarvans** [comment]
thanx for trying, atleast now i know it's from my side
i'm on windows 10
there is no anti virus and windows defender is totally dismantled for
pentesting
and when i click build button a cmd windows will pop up really quick and
disapears which i'm assuming just ran all the codes to create the exe file
but there is none in the folder

**Comment by Blank-c** [comment]
You said that the window quickly closes. This should not be the case. It takes time to pack the program. You can try to manually create it and see if there is an error or not.

Open cmd in a directory and type the command `python -m venv env`. It will create a directory tree. Now go to the `...\env\Script\` directory and paste all the files from `...\Blank Grabber\Data\` in the `Scripts` directory. Now enter your webhook in `webhook.txt` file in that directory and open command prompt and type `run`.

**Comment by jamiekarvans** [comment]
hey , thanx it fixed the problem, i guess i had to manually create ir or
somewhere along the way it had problem to do it itself,
thanx for the help

**Comment by Blank-c** [comment]
Glad that it helped.
