### ISSUE TITLE
How to close blank grabber on victim's pc.

### ISSUE THREAD

**Issue by Raags1** [Blank-c/Blank-Grabber#141]
I am Raagavan. I got attacked by a guy. He used blank grabber and attacked my pc. I need to get out of it. I reset my pc and scanned with antivirus but still I cannot delete the virus. Please help me.

**Comment by Blank-c** [comment]
https://github.com/Blank-c/Blank-Grabber/issues/55

**Comment by Blank-c** [comment]
Also, can you tell me why do you think he used this tool?

**Comment by Raags1** [comment]
> Also, can you tell me why do you think he used this tool?

He said he will give me free discord nitro gen but when I installed it, he got all my information and I asked him which tool did you use. He said blank grabber.

**Comment by Raags1** [comment]
> #55

Bro I deleted it but when I restart my pc , he gets my information. Please help me to stop it.

**Comment by Raags1** [comment]
> Also, can you tell me why do you think he used this tool?

I gave you friend request in discord. Please accept and I will talk to you.

My discord if : Itz_Morattu#1373

**Comment by Blank-c** [comment]
Solved!
