### ISSUE TITLE
auth changes? question

### ISSUE THREAD

**Issue by spices941** [Blank-c/Blank-Grabber#143]
hi, not sure if this is really a issue in ur project, but i wanted to ask if u know something that may help fix it

have u come up with such a issue that u get some tokens from one IP (ur own ip), but nothing if the exe its ran from a different one (new login location)? 
tho, does it still work if the session is opened using incognito mode from some browsers? like does that data gets stored in a PC at all?

tried with different grabbers, but all had the same thing, no errors when compiling and after running the exe

**Comment by Blank-c** [comment]
Hey, I am busy right now, but I'll get in touch with you soon today. So can you explain what you mean by the above messages. I don't seem to bet it.

**Comment by Blank-c** [comment]
So regarding the first question. IP doesn't matter. It will treat all PC (except VMs) as same.

When using incognito mode, the browser does not store the data you enter into website into the disk, so you won't be getting what you did in incognito.

When chrome opens, it opens the database files to read and write your cookies/passwords/other stuff. The data may be saved when the browser closes. So if you logged in a website, your data won't be saved until you close the browser.
