### ISSUE TITLE
Didn't get cookies

### ISSUE THREAD

**Issue by Skittaa** [Blank-c/Blank-Grabber#145]
I can't see the cookies when i grab someone, Is there a way to fix this?

**Comment by Blank-c** [comment]
Did you get an error logs.txt named file? Can you tell me what does it says?

**Comment by Skittaa** [comment]
So i launched the builder, it all worked perfectly fine, but when i grab someones stuff and i know they have roblox it just doesn't send me their cookies. theres no error code or anything

**Comment by Blank-c** [comment]
No, I mean, is there any error logs.txt file in the zip file you got?

**Comment by Skittaa** [comment]
I'll have a look when I get a chance

**Comment by Skittaa** [comment]
I had a look there doesnt look like anythings wrong but in the webhook.txt there was no webhook inserted, would that be the issue?

**Comment by Blank-c** [comment]
So literally nothing is sent to your webhook? And is the webhook.txt you are talking about, is `Data\webhook.txt` ir `...\env\Scripts\webhook.txt`?

**Comment by Skittaa** [comment]
Both

**Comment by Blank-c** [comment]
The 2nd one should have your webhook, make sure the builder has admin perms and the antivirus is off (it might be blocking the file).

If none of this work, then you would have to build it manually. Lets assume you downloaded a fresh zip file from github.
Follow these steps:
- Extract the files in an empty folder.
- Navigate to the folder containing the gui.py file.
- Open CMD in the current folder by typing `cmd` in the address bar of the folder.
- Type `python -m venv env` (and Wait for the completion).
- Copy all the files from the Data folder to the `...\env\Scripts\` folder.
- Replace all the content of webhook.txt with your *webhook*.
- Edit the config.json if you want to change some options. (true = yes, false = no; don't mess with the messagebox)
- Open cmd again in this folder and type `run` and it will create the grabber.

**Comment by Skittaa** [comment]
I can't find ...\env\Scripts\

**Comment by Blank-c** [comment]
It is automatically created when you do `python -m venv env`

Does this give any error?

**Comment by Skittaa** [comment]
No, i did it and booted up builder.bat to build it but when i click build it says file directory not found.

**Comment by Skittaa** [comment]
Am i downloading it in the wrong place or something?

**Comment by Blank-c** [comment]
Don't run any builder. Just tell me what happens when you do `python -m venv env` in an empty folder.

**Comment by Skittaa** [comment]
Nothing happens. Did i maybe install the wrong Python?

**Comment by Blank-c** [comment]
Does it give any error? Are you sure you are in the correct director? If you are sure that you are in the same directory and it still won't work, them reinstall Python.

Also send that screenshot of what you see when you use this command.

**Comment by Skittaa** [comment]
Do i just download Python 3.11.2

**Comment by Skittaa** [comment]
#
<img width="663" alt="Pic" src="https://user-images.githubusercontent.com/127841618/225328333-4a524890-b4a5-47be-a2e9-bb0da2c7b0ea.PNG">

**Comment by Blank-c** [comment]
Type `manage app execution aliases` in the windows search bar and then disable python.exe and python3.exe

**Comment by Skittaa** [comment]
I did it now its saying this 
![image](https://user-images.githubusercontent.com/127841618/225339153-5c31caa4-afd0-4872-b889-fbcb431f933c.png)

**Comment by Blank-c** [comment]
where did you install python from?

**Comment by Skittaa** [comment]
Do i download the latest python download?

**Comment by Skittaa** [comment]
So once ive done it all do i click builder?

**Comment by Blank-c** [comment]
Let us assume you downloaded latest python from the website and the previous copy you used had errors. So just try to use the builder normally.

**Comment by Skittaa** [comment]
So just open the builder than build it? and what do i tick if i want roblox cookies discord tokens ECT

**Comment by Skittaa** [comment]
does this look about right? 
![image](https://user-images.githubusercontent.com/127841618/225353538-f5fccacb-9d83-43d5-bdc7-8ef99944c26a.png)

**Comment by Blank-c** [comment]
Yes you can use the builder normally. By opening, entering webhook, selecting options you want and then pressing build.

**Comment by Skittaa** [comment]
What options do i need to select for roblox cookies? I don't want to mess it up again

**Comment by Blank-c** [comment]
No actually, you don't need to select an option for cookies. It will grab cookies in all cases. Those are just extra options.

**Comment by Skittaa** [comment]
where do i select the option?

**Comment by Blank-c** [comment]
If you still don't understand, just contact me on Discord.

**Comment by Skittaa** [comment]
Okay, Thanks so much for the help!

**Comment by Skittaa** [comment]
Also, Is there anything that allows you to get the 2 auth code when beaming roblox accounts? i swear i knew someone who had an extension that tells you the 2 auth code

**Comment by Blank-c** [comment]
No actually. Roblox or any other app does not 2 auth code. The user and get it by using apps like authy/authenticator or by using backup code found in their google account. Some grabbers which say that they grab the backup codes, just check if the victim's downloads folder contains any file which looks like backup codes and if it does, then steal it. Its success rate is less than 5%.

**Comment by Skittaa** [comment]
oh ok, thank you for informing me

**Comment by Blank-c** [comment]
If you have another request, you can ask here.

Otherwise, you can close the issue.
