### ISSUE TITLE
Block sites not working

### ISSUE THREAD

**Issue by ytjhrttytj** [Blank-c/Blank-Grabber#147]
Block sites not working, when i go to drivers/etc i can't see the archive to block sites and i can enter av sites.

**Comment by Blank-c** [comment]
Make sure you enabled the options to show hidden files and show system files.
Open command prompt as admin and type this command `REG QUERY HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters /V DataBasePath` 
What do you see?

**Comment by ytjhrttytj** [comment]
![Captura de pantalla 2023-03-16 102419](https://user-images.githubusercontent.com/127214764/225686611-dbd06962-1f9c-4561-a1ac-63a087ba10dd.png)

**Comment by Blank-c** [comment]
> ![aaa](https://user-images.githubusercontent.com/127214764/225688674-44301209-d0e7-4093-b357-28bd61ca3d75.png) i found that

Did you turn on system files also, I didn't find hosts file here.

It looks like the block site is not working on your PC. But if someone else run the stub, it would work normally. You can test this on a VM.
