### ISSUE TITLE
Error while creating .exe file

### ISSUE THREAD

**Issue by MasterDooom** [Blank-c/Blank-Grabber#148]
When I press "Create file" to make the .exe file, it shows me an error:
Error while creating virtual environment ("python -m venv env"): Access is denied.

![image](https://user-images.githubusercontent.com/95602174/225904516-a52b6a76-d757-4351-9f63-0c9bd18ac562.png)

**Comment by Blank-c** [comment]
Make sure your antivirus is off and you are running the builder in a folder with writable permissions and not somewhere like OneDrive etc.

**Comment by MasterDooom** [comment]
I have it in my pendrive would it still work?

**Comment by Blank-c** [comment]
no you need to put it in one of your local disk (preferably not C)

**Comment by MasterDooom** [comment]
Alright, I shifted the folder to my main desktop and tried building .exe from there.. still getting the same error. It says access is denied to virtual env. (as shown in ss above)

**Comment by Blank-c** [comment]
Are you sure your antivirus is turned off?
Also, whats the output of these commands?

`where python`
`python --version`
`python -m venv env`

Execute all these commands in a command prompt (with admin access) in the same folder as the `gui.py`

**Comment by MasterDooom** [comment]
I tested this on my friend's PC and the virtual environment part worked and all..
But got a new error now (refer img)
![image](https://user-images.githubusercontent.com/95602174/226101774-f7dd2676-1135-4968-9fc1-17fde464e0ab.png)

**Comment by Blank-c** [comment]
It looks like you are missing `main.py` file. Look in your Data folder, if there is main.py
Delete the env and try again while making sure the antivirus is off.

If possible, please send a video of your situation, so I can understand what actually is going wrong.

**Comment by MasterDooom** [comment]
Can I contact you on your DC server if you have one, or would you mind sharing your discord ID?

**Comment by MasterDooom** [comment]
![image](https://user-images.githubusercontent.com/95602174/226108765-82dddb35-a557-4edd-80c8-aff1a5821629.png)
Also what is this?

**Comment by Blank-c** [comment]
> Can I contact you on your DC server if you have one, or would you mind sharing your discord ID?

I have already provided the discord username in the Readme

**Comment by MasterDooom** [comment]
Added you as a friend, the guy named "futurE"
