### ISSUE TITLE
[ERROR.] AFTER BUILDING EXE AND RUNNING IT, IT GAVED ERROR

### ISSUE THREAD

**Issue by polii-keiu** [Blank-c/Blank-Grabber#151]
![image](https://user-images.githubusercontent.com/128136353/226176730-fa1de3bb-e9db-4609-84ad-c074196a053d.png)

OS: 7 - SP:1
PY[VER]: 3.8.10
--------------------------------------------------------------
WEBHOOK:STATUS:WORKING

**Comment by Blank-c** [comment]
3.8 is not supported. This error is seen in older version of python. Please upgrade to a newer version. And DON'T use the version in windows store. Download the one in https://python.org/downloads
