### ISSUE TITLE
How to autocomplete passwords from cookies?

### ISSUE THREAD

**Issue by WenaWena** [Blank-c/Blank-Grabber#153]
I imported the cookies to firefox as instructed, but it only autocompletes some emails, not passwords (to sites which passwords weren't extracted)

**Comment by Blank-c** [comment]
Cookies are used to log in to sites, not autocompletion. For example: If someone is logged in to github and then you got their cookie and imported it, you will be automatically logged in to their github. But there are many websites which don't store login info in cookies and thats why this method would not work on those sites. Also many sites reset the users' cookies if they log out or someone from suspiciously far away location logs in the account.
