### ISSUE TITLE
ZIP file appears to be damaged

### ISSUE THREAD

**Issue by WenaWena** [Blank-c/Blank-Grabber#154]
Screenshot, cookies.txt and history.txt appear to be damaged on my ZIP file and can't be extracted or viewed.

**Comment by Blank-c** [comment]
Yes this is the 2nd time I got this type of report, (last time one year ago). But this doesn't seem to happen frequently.
This might be the cause due to antiviruses blocking the zip file or something else. I don't think I can do something about this.

**Comment by WenaWena** [comment]
closed by mistake
