### ISSUE TITLE
Trigger Windows Deffender

### ISSUE THREAD

**Issue by raphaelgrougnet** [Blank-c/Blank-Grabber#157]
Hi, the grabber triggers Windows Deffender and WD deletes it, that kinda embarasing

**Comment by Blank-c** [comment]
it happens. You must disable wd while building.

**Comment by raphaelgrougnet** [comment]
i mean, when you start the grabber.exe it triggers wd, i had to disable wd to try grabbing

**Comment by Blank-c** [comment]
Ye since it is a trojan (and also open source).
