### ISSUE TITLE
doesn't steal passwords

### ISSUE THREAD

**Issue by jamiekarvans** [Blank-c/Blank-Grabber#158]
it's 50/50 on most computers
even tho i know a pc has passwords saved in firefox but it doesn't steal anything and only shows the history
maybe there is a problem in the grabbing file directory of firefox saved password 
i've manually checked the directory and firefox has logins.json file in \AppData\Roaming\Mozilla\Firefox\Profiles\mx8gkqxi.default-release
but it doesn't grab it or send anything about it

**Comment by Blank-c** [comment]
If you have direct access to the PC, can you check if the passwords stored in firefox are visible in [this software](https://www.nirsoft.net/utils/web_browser_password.html)

**Comment by jamiekarvans** [comment]
yes both chrome and firefox are visible

**Comment by Blank-c** [comment]
Then I am not sure why this happened, does the zip file has an error logs file?

**Comment by jamiekarvans** [comment]
Most of them doesn't have any error log file but I've got one now that it
contains error file
This is the error:

Line 1588 : captureBrowserPasswords : PermissionError : [WinError 5] Access
is denied: 'C:\\Users\\mahya\\AppData\\Local\\Temp\\_MEI78642\\getPass.exe'
Line 19 : encode : UnicodeEncodeError : 'charmap' codec can't encode
characters in position 260243-260248: character maps to <undefined>

I've even tried with run as administrator and still the same thing.

**Comment by jamiekarvans** [comment]
I dismantled the anti virus and now there is no error log file, but
everything else is the same, there is only history but cookies and
passwords are empty
Tried it on a few other computers and still the same thing,
I think maybe it's getting caused by enabled screenshot, but it also was
like this before except before was 50/50 but now all of computers have
empty password file

**Comment by Blank-c** [comment]
I hate to say this but would you mind trying out each older versions (last two or three versions) of the grabber. This problem might become a huge one if not treated properly.

**Comment by jamiekarvans** [comment]
yes i tried the version with webcam off
this time it shows that pc has passwords correctly in the message in the discord but it in the passwords file it's empty
also doesn't grab the cookies
and also tired a few versions before it's the same thing, it shows the pc has passwords but doesn't send them, it's weird because i tried it on the same pc which before it sent me passwords but this time it doesn't work even the older versions, i'm thinking maybe if there is any link in the source code, it might have problem with that or something similar
i will try to build with another python version and also another pc and i will let you know

**Comment by Blank-c** [comment]
If the passwords file is empty. Then it means, that the grabber did grab the passwords, but was unable to save them to a file (permission error or some other process blocking) or it (password file contents) could have been removed by the antivirus.

**Comment by jamiekarvans** [comment]
there is no anti virus installed on the device
if it is the permission error can you just add the get administrator code to the source?

**Comment by Blank-c** [comment]
It already has the code. But for some reason it is getting permission error. I don't think I can do anything about this.

**Comment by Blank-c** [comment]
I can't help without any type of crucial information. If there is something else, you can open a new issue.
