### ISSUE TITLE
Discord?

### ISSUE THREAD

**Issue by lITronusIl** [Blank-c/Blank-Grabber#159]
o, i tried the grabber on my friends and it works fine, but it wont grab the discord token. whats the matter

**Comment by Blank-c** [comment]
Is there an error logs.txt file?

**Comment by lITronusIl** [comment]
No

**Comment by Blank-c** [comment]
Then it means, the grabber couldn't find the token in the specified directories.
Maybe the friends are using some other discord client than the official discord client.

**Comment by lITronusIl** [comment]
Can tokens of users that arent logged in for like a year disappear or can they disappear after an update?

**Comment by Blank-c** [comment]
When users (or discord itself) change passwords, the token resets.
No, they won't disappear if the user hasn't logged in for years.
