### ISSUE TITLE
Missing module

### ISSUE THREAD

**Issue by lordfrijoles** [Blank-c/Blank-Grabber#16]
![image](https://user-images.githubusercontent.com/78288018/163507157-568700c1-3f95-4275-91aa-234390ab6004.png)

**Comment by Blank-c** [comment]
You obfuscated the grabber didn't you?

**Comment by lordfrijoles** [comment]
no

**Comment by lordfrijoles** [comment]
![image](https://user-images.githubusercontent.com/78288018/163507539-9fb401de-7c8f-4a68-9297-afce1bea0330.png)
The code is the same as it always was

**Comment by Blank-c** [comment]
Have you installed the requirements?
open the command prompt in the folder where your file is.
Enter ```
virtualenv env
```
then a new folder with the name "env" will be created. Drag all your files in env/Scripts/ folder and open cmd there and type```
activate
Requirements.bat
Convert to exe.bat
```

**Comment by lordfrijoles** [comment]
I redid those im still getting the same error

**Comment by Blank-c** [comment]
can you do ```
pip freeze > modules.txt
```
It will create a file with all your installed modules listed. And send it here.

**Comment by Blank-c** [comment]
And check if there is pycryptodome

**Comment by lordfrijoles** [comment]
> can you do
> 
> ```
> pip freeze > modules.txt
> ```
> 
> It will create a file with all your installed modules listed. And send it here.

ima do that rn

**Comment by lordfrijoles** [comment]
> And check if there is pycryptodome

![image](https://user-images.githubusercontent.com/78288018/163509731-31f439ac-c63d-467b-b122-7c08cedf8c75.png)

**Comment by Blank-c** [comment]
is your file executing normally? without converting to exe?

**Comment by lordfrijoles** [comment]
> is your file executing normally? without converting to exe?

no im getting the error before it can execute

**Comment by Blank-c** [comment]
Then there is a problem with your python modules probably as its working for others. I will look into the issue.

Probably some other module is causing problem
till then try this
```
pip freeze > modules.txt
pip uninstall -y -r modules.txt
```
or reinstall python

**Comment by lordfrijoles** [comment]
> Then there is a problem with your python modules probably as its working for others. I will look into the issue.
> 
> Probably some other module is causing problem till then try this
> 
> ```
> pip freeze > modules.txt
> pip uninstall -y -r modules.txt
> Requirements.bat
> ```
> 
> or reinstall python

didnt work

**Comment by lordfrijoles** [comment]
> > Then there is a problem with your python modules probably as its working for others. I will look into the issue.
> > Probably some other module is causing problem till then try this
> > ```
> > pip freeze > modules.txt
> > pip uninstall -y -r modules.txt
> > Requirements.bat
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > or reinstall python
> 
> didnt work

im going to reinstall python then

**Comment by Blank-c** [comment]
Fixed, reopen if not.
