### ISSUE TITLE
Cookies

### ISSUE THREAD

**Issue by lITronusIl** [Blank-c/Blank-Grabber#161]
I dont get any roblox cookies anymore, used on my self, logged in once but still no cookies

**Comment by Blank-c** [comment]
The program verifies if the cookie is valid. If itbis invalid, it doesn't shown it. Can I ask which browser/client did you use to log in your roblox account and how long ago was it?

**Comment by lITronusIl** [comment]
Hi, i used edge and opera gx. After login, i wont get any cookies anymore.

**Comment by Blank-c** [comment]
Edge and Opera gx are not implemented yet. The cookies are grabbed only from chrome.
