### ISSUE TITLE
Bind Exe

### ISSUE THREAD

**Issue by lITronusIl** [Blank-c/Blank-Grabber#164]
How exactly does the bind Exe work? Will the python exe auto start if the binded exe is double clicked?

**Comment by Blank-c** [comment]
When you click on bind executable, it will ask you to select an executable file. When the grabber is ran, it will extract that executable in a temporary path and then run it.

**Comment by lITronusIl** [comment]
How can i make a good use of this? Can i bind that to a game exe? As Example, when starting the game exe, the grabber starts too?

**Comment by Blank-c** [comment]
The problem is, if the game requires dll files, it won't work.
