### ISSUE TITLE
Blue Screen of Death even if not run in Virtual Box

### ISSUE THREAD

**Issue by terbium360** [Blank-c/Blank-Grabber#167]
Everything was set until I ran the "Built", it flashed the screen and immediately restarted my computer.

**Comment by Blank-c** [comment]
Oh I am so sorry to hear that it considered your system as a VM and killed it.

Would you mind running these commands below in the command prompt and send the output, so I might find out why it considered your system as a VM.

UUID: `wmic csproduct get uuid`
Computer Name: `echo %computername%`
Account username: `echo %username%`
GPU: `wmic path win32_VideoController get name`

Also check if you have any of the listed folder in your D drive: `Tools`, `OS2`, `NT3X`

**Comment by Blank-c** [comment]
Stale
