### ISSUE TITLE
I have the most recent version of python but

### ISSUE THREAD

**Issue by YuyaHam** [Blank-c/Blank-Grabber#168]
Two errors appear whenever I load it
`'python' is not recognized as an internal or external command,
operable program or batch file.`
or
`Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.`
I have python 3.11.2 and ive tried disabling, re-enabling app execution aliases and when i disable that it gives me the first error, i dont know what "install from microsoft store" means or how to disable that

**Comment by Blank-c** [comment]
1) Disable from execution aliased.
2) When using the python installer, tick the "Add Python to PATH" option.
