### ISSUE TITLE
I keep getting this error

### ISSUE THREAD

**Issue by Fr0go1** [Blank-c/Blank-Grabber#175]
Fatal error in launcher: Unable to create process using '"C:\Users\User\Downloads\Blank-Grabber-main\Blank-Grabber-main\Blank Grabber\env\Scripts\python.exe"  "D:\Files\Blank-Grabber-main\Blank-Grabber-main\Blank Grabber\env\Scripts\pyinstaller.exe" --onefile --clean --noconsole --noconfirm main-o.py --name "Built.exe" -i icon.ico --hidden-import urllib3 --hidden-import sqlite3 --hidden-import PIL.Image --hidden-import PIL.ImageGrab --hidden-import PIL.ImageStat --hidden-import pyaes --hidden-import win32crypt --hidden-import json --add-data Camera;. --add-data config.json;. --add-data injection-obfuscated.js;. --add-data getPass;. --version-file version.txt  ': The system cannot find the file specified.

Building failed!
Press any key to continue . . .

**Comment by Blank-c** [comment]
Can you type this command in cmd `where python && python --version`.
Also, are you sure you extracted the zip file when running the builder?

**Comment by Blank-c** [comment]
stale; Try to download the latest version of Python (and remove the older version) and Blank Grabber and extract the zip file before building.
