### ISSUE TITLE
getting version error

### ISSUE THREAD

**Issue by iprevale** [Blank-c/Blank-Grabber#176]
i keep getting this error tho i have the latest version of python installed 
![image](https://user-images.githubusercontent.com/130697472/231851047-1fc63e37-ddf9-4b7c-862a-b64824fcb2f1.png)

**Comment by Blank-c** [comment]
I think it is simple english, isn't it?

**Comment by Blank-c** [comment]
you need to install python latest one from https://python.org/download

**Comment by iprevale** [comment]
> you need to install python latest one from https://python.org/download

thats the issue i have the latest version installed and still getting this error

**Comment by Blank-c** [comment]
Can you run this command in command prompt `where python && python --version`

**Comment by iprevale** [comment]
> Can you run this command in command prompt `where python && python --version`

![image](https://user-images.githubusercontent.com/130697472/232236723-c679d082-edcf-44c5-9792-160b5b3dcd7b.png)

**Comment by Blank-c** [comment]
Can you download the latest update of Blank Grabber and Go to windows settings, search for `Manage app execution aliases`, then turn off python related options. Then use the new update of Blank Grabber, see if it works.

**Comment by iprevale** [comment]
have done same error

**Comment by Blank-c** [comment]
After you updated the grabber, the builder must be showing the version of the python being used. Can you send the screemshot of the new error.

**Comment by iprevale** [comment]
![image](https://user-images.githubusercontent.com/130697472/232241270-50043fa4-1399-4fb8-9a9c-fd2bcee371ec.png)


> After you updated the grabber, the builder must be showing the version of the python being used. Can you send the screemshot of the new error.

**Comment by Blank-c** [comment]
Uninstall python 3.9 from control panel

**Comment by iprevale** [comment]
> Uninstall python 3.9 from control panel

seems to have sorted it thank you
