### ISSUE TITLE
error whil openning the built

### ISSUE THREAD

**Issue by vianzas** [Blank-c/Blank-Grabber#177]
raceback (most recent call last):
  File "main-o.py", line 5, in <module>
  File "<string>", line 2, in <module>
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'pyaes'

**Comment by Blank-c** [comment]
What are you doing that causes this error?

**Comment by vianzas** [comment]
> What are you doing that causes this error?

Ijust open up the built

**Comment by Blank-c** [comment]
This is wierd. Can you tell me the output of `where python && python --version` in command prompt.
Also try to redownload the grabber from github (in case any file is missing)

**Comment by vianzas** [comment]
Sorry idont know how to do that

**Comment by Blank-c** [comment]
Check on google "How to open command prompt"

**Comment by Blank-c** [comment]
Also like I said, try to redownload the files.

**Comment by vianzas** [comment]
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)] on win32

**Comment by Blank-c** [comment]
Write the full command `where python && python --version`

**Comment by vianzas** [comment]
C:\Users\vianz\AppData\Local\Programs\Python\Python310\python.exe
C:\Users\vianz\AppData\Local\Microsoft\WindowsApps\python.exe
Python 3.10.9

**Comment by Blank-c** [comment]
If you tried to redownload the files but you are getting still the same problem, then there is something wrong with your system. You can use this online VM and build the grabber [there](https://app.apponfly.com/trial). Don't forget to install python in this VM from the official site.

Make sure to turn off VMPROTECT in case you are going to test it on the same VM.

**Comment by vianzas** [comment]
> If you tried to redownload the files but you are getting still the same problem, then there is something wrong with your system. You can use this online VM and build the grabber [there](https://app.apponfly.com/trial). Don't forget to install python in this VM from the official site.
> 
> 
> 
> Make sure to turn off VMPROTECT in case you are going to test it on the same VM.

Ok thank you
