### ISSUE TITLE
Victim runs it and no info is sent to the webhook.

### ISSUE THREAD

**Issue by VesperLmao** [Blank-c/Blank-Grabber#178]
Read title.

**Comment by VesperLmao** [comment]
@Blank-c

**Comment by Blank-c** [comment]
Did you try to turn off VMPROTECT?
Sometimes the grabber consider the victim's PC as VM.

**Comment by Blank-c** [comment]
@VesperLmao

**Comment by Blank-c** [comment]
Reopen if this issue still persists.
