### ISSUE TITLE
Doesnt send anything

### ISSUE THREAD

**Issue by Gaminguide1000** [Blank-c/Blank-Grabber#18]
The BlankGrabber.exe doesnt send anything. Tried with 3 Different Servers and 5 Webhooks. It just doesnt send it

**Comment by Blank-c** [comment]
Please try to run the script instead of webhook and then reply again.

**Comment by Gaminguide1000** [comment]
i dont get what you mean? I wrote the webhook into the script and turned it into an exe with the converter from here.

**Comment by Blank-c** [comment]
Try to run the script instead of converting it to exe

**Comment by Blank-c** [comment]
if it doesn't work, try to redownload the script. I have updated the code a little bit.

**Comment by Gaminguide1000** [comment]
tried with the script, also didnt work. ima redownload it, even tough i already did that lol

**Comment by Gaminguide1000** [comment]
kk works now
