### ISSUE TITLE
Files corrupting when downloading from discord

### ISSUE THREAD

**Issue by BlitzFan1209** [Blank-c/Blank-Grabber#180]
hello when i install the info it sent it corrupts the files sometime has happened twice to me
![SharedScreenshot](https://user-images.githubusercontent.com/98890042/234814932-12e280c2-344c-4501-a392-8daf40dc247c.jpg)

**Comment by Blank-c** [comment]
It happens sometimes when the upload is interrupted or antivirus blocks the file.
