### ISSUE TITLE
Error Python

### ISSUE THREAD

**Issue by LeLi9898** [Blank-c/Blank-Grabber#185]
When i try open builder.bat an error appears "Python"

**Comment by Blank-c** [comment]
Can you send me screenshot of:
1) The error itself.
2) The command prompt result `where python && python --version`

**Comment by LeLi9898** [comment]
> 2\. where python && python --version

**Comment by LeLi9898** [comment]
> Can you send me screenshot of:
> 
> 1. The error itself.
> 2. The command prompt result `where python && python --version`

![PythonError2](https://user-images.githubusercontent.com/127128144/236617518-4b770f31-d8ce-4b2d-b1b1-5ff7aebd5fdf.png)
![PythonError1](https://user-images.githubusercontent.com/127128144/236617521-30133016-d25d-49f6-b651-b2a95e23a53c.png)

**Comment by LeLi9898** [comment]
is working

**Comment by Blank-c** [comment]
Did you fix it? If so, please write the your side of fix here.
