### ISSUE TITLE
Unable to download the zip file.

### ISSUE THREAD

**Issue by LeLi9898** [Blank-c/Blank-Grabber#186]
the zip archive with these victims is not downloaded

**Comment by Blank-c** [comment]
What do you mean? Can you explain?

**Comment by LeLi9898** [comment]
> What do you mean? Would you please explain?
when I try to download the zip archive with the victims data, the error Failed to open this page It seems that the web page at https://cdn.discordapp.com/attachments/1100115448109998184/1104432100330983504/Blank-lildenn.zip contains errors or has been permanently moved to a new web address. (im uses translate)

**Comment by Blank-c** [comment]
This is a problem related to discord. This problem is not with the grabber.

**Comment by LeLi9898** [comment]
> This is a problem related to discord. This problem is not with the grabber.

And how can this be fixed?

**Comment by LeLi9898** [comment]
all good, tried it from a different browser. It worked.
