### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Drewwwe** [Blank-c/Blank-Grabber#189]
Add a opption to build only the python script without obsufucated code.
I want analize the code and use other better method for obsufucation.

**Comment by Blank-c** [comment]
> Add a opption to build only the python script without obsufucated code. I want analize the code and use other better method for obsufucation.

Modify the `BlankOBF.py` or `process.py` in the data file if you wanna analyse.

**Comment by Drewwwe** [comment]
I mean add a option into the builder gui for select if you want build the python script clean of the trojan

**Comment by Drewwwe** [comment]
Basically that you can see the code of the trojan that you build

**Comment by Blank-c** [comment]
why do you want it that way. The code of the stub is already in the `Componentes\stub.py` file.
You can modify the process.py to not obfuscate the file. This way it would generate a non obfuscated file.
I don't see any reason why someone would want to build a non obfuscated stub tho.

**Comment by Drewwwe** [comment]
I want do it because I know a better obsufucation method with less detections in virus total

**Comment by Blank-c** [comment]
Thats why I said you should modify the process.py it is the one which is calling the obfuscator and adding values to the program.
