### ISSUE TITLE
'env' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by Riparonipepper** [Blank-c/Blank-Grabber#19]
the file was to large so i was doing the virtual environment thing, i had put into cmd the "virtualenv env" and all is well, but when i put in "env/Scripts/activate" it said that env wasnt recognized as an internal or external command, operable program or batch file.

Heres a screen shot.
![image](https://user-images.githubusercontent.com/104666223/166575054-7bc60c24-f603-44d9-8a4b-d6e26b2ff793.png)

**Comment by Blank-c** [comment]
> the file was to large so i was doing the virtual environment thing, i had put into cmd the "virtualenv env" and all is well, but when i put in "env/Scripts/activate" it said that env wasnt recognized as an internal or external command, operable program or batch file.
> 
> Heres a screen shot. ![image](https://user-images.githubusercontent.com/104666223/166575054-7bc60c24-f603-44d9-8a4b-d6e26b2ff793.png)

Try
```
cd env
cd Scripts
activate
```

**Comment by Blank-c** [comment]
Can you see "(env)" written before the location in cmd? (if yes, then it means its activated). You don't have to close the cmd. Just write the name of the requirements and converter file in the cmd without closing it.

**Comment by Riparonipepper** [comment]
dang ok so it went down from a 19,000kb to a 12,000kb and discord says it without nitro only allows 8megabyte files and im sure you know this but 1,000 Kilobytes is 1 megabyte, but thanks for the step by step for the virtual Env thing

**Comment by Blank-c** [comment]
You can upload it to some platform like mega/anonfiles etc.

:)
