### ISSUE TITLE
I got hacked with it

### ISSUE THREAD

**Issue by NokoxSlays** [Blank-c/Blank-Grabber#190]
How can I remove it?

**Comment by Blank-c** [comment]
https://github.com/Blank-c/Blank-Grabber/issues/142

**Comment by NokoxSlays** [comment]
but I just discovered it was hazard but the screens of the bot ware blsnk grabber, can you help me with that, all though appreciate you!

**Comment by NokoxSlays** [comment]
So basically it left a note in my bio

**Comment by NokoxSlays** [comment]
Nuked with hazard and the link

**Comment by Blank-c** [comment]
What was it?

**Comment by Blank-c** [comment]
Please send all the evidences that you have.

**Comment by Blank-c** [comment]
> Nuked with hazard and the link

it might be possible that you got hacked by this and your account was nuked by hazard nuker

**Comment by NokoxSlays** [comment]
that's what I said

**Comment by Blank-c** [comment]
Oh you should follow the steps I stated above to remove it.

**Comment by NokoxSlays** [comment]
but do the provided steps remove everything. and yes I did the steps

**Comment by Blank-c** [comment]
> but do the provided steps remove everything. and yes I did the steps

Unless the person who hacked you bound some executable to the file, or modified the code, you are safe to go. But do scan your PC with antivirus (preferably malwarebytes)

**Comment by NokoxSlays** [comment]
I'll try but my english got so much worse when he scared me like emy grama and everything but I'll try thank you

**Comment by NokoxSlays** [comment]
ok, I did Norton but that other tool and Malwarebytes +your options, hope am safe.......  ......Can you like remote in the guy's PC to check it, I can send his discord (also add me)

**Comment by Blank-c** [comment]
> ok, I did Norton but that other tool and Malwarebytes +your options, hope am safe....... ......Can you like remote in the guy's PC to check it, I can send his discord (also add me)

No sorry but I can't. The grabber is not backdoored.
