### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by BlitzFan1209** [Blank-c/Blank-Grabber#191]
What is the minecraft session for if you cant really log into theyre account or can you?

**Comment by Blank-c** [comment]
If the session is active, you can replace the files in your .minecraft folder with the ones you got, you can login to their minecraft accoumt.

**Comment by Blank-c** [comment]
If I remember correctly, you can use liquid bounce to log into their minecraft account.

**Comment by TitanGaming12** [comment]
can you tell me how exactly to get on to their account, and also it seems the new blank grabber version doesent steal nothing else than passwords and discord accounts

**Comment by Blank-c** [comment]
I never did it myself but you may search for it on google.
Can you try to run the grabber with antivirus/defender off

**Comment by BlitzFan1209** [comment]
Is liquid bounce even safe i see reddit posts about it overheating theyre computers

**Comment by zEncrypte** [comment]
https://github.com/CCBlueX/LiquidBounce

**Comment by Blank-c** [comment]
Might help: https://www.unknowncheats.me/forum/minecraft/483869-login-session-id.html

**Comment by BlitzFan1209** [comment]
Wheres the session id located?

**Comment by Blank-c** [comment]
> you can always manually edit your launcher_profiles and launcher_accounts file to just replace an entry with the session id you stole

You may try this. You may try to replace the whole file.

**Comment by TitanGaming12** [comment]
thank you, the new version doesent get other details though i use no
security on

**Comment by BlitzFan1209** [comment]
does tlauncher work
 with replacing the files?

**Comment by Blank-c** [comment]
> thank you, the new version doesent get other details though i use no security on

Can you try it on a VM? (Log into one [here](https://app.apponfly.com/trial)) Make sure to turn off Anti VM when building.

**Comment by Blank-c** [comment]
> does tlauncher work with replacing the files?

You may try.

Also just so you know, the session token is only one time use. If the victim logged in his minecraft account, the token would automatically reset.

**Comment by BlitzFan1209** [comment]
tlauncher dosnt work what other launchers may it work on?

**Comment by TitanGaming12** [comment]
i will check it out and let you know. you got discord by chance?
let me know your name

**Comment by BlitzFan1209** [comment]
> 

eae6t3#7020

**Comment by Blank-c** [comment]
> tlauncher dosnt work what other launchers may it work on?

It may also be possible that the session id has expired. Its one time use. And it expires when the original owner logs in the game the next time.

**Comment by Blank-c** [comment]
not sure how to explain.

**Comment by BlitzFan1209** [comment]
what launcher should i use

**Comment by Blank-c** [comment]
> what launcher should i use

Just use TLauncher, I think it should work fine.

**Comment by BlitzFan1209** [comment]
tlauncher dosnt work

**Comment by Blank-c** [comment]
Like I said more than 3 times, it can be possible that the key is expired thats why its not working.

**Comment by BlitzFan1209** [comment]
Yeah ik i tried it like a minute after i got the key

**Comment by Blank-c** [comment]
It may also be possible that the victim also used tlauncher. Tlauncher creates a fake session key. Which won't work on other systems.

**Comment by BlitzFan1209** [comment]
may you tell me other launchers that session id works on since its weird on tlauncher

**Comment by Blank-c** [comment]
> may you tell me other launchers that session id works on since its weird on tlauncher

sorry I don't know any other.
