### ISSUE TITLE
OS says windows 11 even though OS is windows 10

### ISSUE THREAD

**Issue by SniperNation** [Blank-c/Blank-Grabber#192]
It says my OS is windows 11 pro when I'm using windows 10 pro
reproduction:
Run bot
Check OS field

**Comment by Blank-c** [comment]
Please enter this command in cmd (as admin) `wmic os get Caption`

**Comment by Blank-c** [comment]
@SniperNation You there?

**Comment by 8FrMc** [comment]
bro died

**Comment by Blank-c** [comment]
Rip. I am closing this issue for now. Reopen if you came back @SniperNation with an answer.
