### ISSUE TITLE
Sorry

### ISSUE THREAD

**Issue by CrippinDog3** [Blank-c/Blank-Grabber#194]
I want to say sorry, i confused u for another repository

**Comment by CrippinDog3** [comment]
today i confused u for PatrigPagoda

**Comment by CrippinDog3** [comment]
im so sorry to have u accused

**Comment by CrippinDog3** [comment]
Im so fricking sorry

**Comment by CrippinDog3** [comment]
ur is not a virus, the other one yes, ur is safe

**Comment by Blank-c** [comment]
No worries. I am glad that you understood.

**Comment by CrippinDog3** [comment]
Ye, im so sorry

**Comment by aryan5555github** [comment]
> 

wait a minute his stealer is a virus dont download it @CrippinDog3

**Comment by aryan5555github** [comment]
abt tat  PatrigPagoda
