### ISSUE TITLE
blank grabber not working 

### ISSUE THREAD

**Issue by BlitzFan1209** [Blank-c/Blank-Grabber#195]
some guy opened it didnt work he even opened it as administrator still didnt work he sent a clip of opening it did nohting and sent nohting to webhook too

**Comment by BlitzFan1209** [comment]
https://cdn.discordapp.com/attachments/1106527661695713321/1107327107455004802/VID_20230514222112.mp4

**Comment by BlitzFan1209** [comment]
also he has 2 gb of ram if thats a problem

**Comment by BlitzFan1209** [comment]
I even tested it it sent nohting to the webhook

**Comment by Blank-c** [comment]
Looking at the taskbar and under the quick access tab at the "My Computer" icon. It looks like he is running the file on windows 7. Windows 7 is neither supported by Python anymore nor the grabber.

**Comment by Blank-c** [comment]
> I even tested it it sent nohting to the webhook

Can you test it without the Anti VM option?

**Comment by BlitzFan1209** [comment]
Yeah but what about my problem
since like i ran it and it sent nohting to the 
umm webhook

**Comment by BlitzFan1209** [comment]
uhh

**Comment by BlitzFan1209** [comment]
Maybe also can you accept my friend request eae6t3#7020

**Comment by BlitzFan1209** [comment]
Since it takes bit long time to get a response

**Comment by Blank-c** [comment]
> Maybe also can you accept my friend request eae6t3#7020

I don't use discord anymore. You may join my Telegram group.

**Comment by BlitzFan1209** [comment]
Why not?

**Comment by Blank-c** [comment]
> Yeah but what about my problem since like i ran it and it sent nohting to the umm webhook

Try to build it without enabling "Anti VM" option.
If this does not solve the problem. Go to the folder *...\env\Scripts* and right click the *run.bat* and then edit it and remove the ` --noconsole` (include a space in the beginning) and then save and double click the bat file. Then run this new file. If it gets error, it would show there.

**Comment by Blank-c** [comment]
> Why not?

Banned yesterday. Too lazy to make new account for this.

**Comment by BlitzFan1209** [comment]
Send telegram link

**Comment by Blank-c** [comment]
> Send telegram link

its at the end of the readme.

**Comment by BlitzFan1209** [comment]
oh

**Comment by BlitzFan1209** [comment]
When i tried to build the file it gave me a error

**Comment by Blank-c** [comment]
> When i tried to build the file it gave me a error

whats the error?

**Comment by BlitzFan1209** [comment]
725 DEPRECATION: Bytecode encryption will be removed in PyInstaller v6. Please remove your --key=xxx argument to avoid breakages on upgrade. For the rationale/alternatives see https://github.com/pyinstaller/pyinstaller/pull/6999
725 INFO: PyInstaller: 5.11.0
726 INFO: Python: 3.10.7
793 INFO: Platform: Windows-10-10.0.19044-SP0
797 INFO: wrote C:\Users\User\Downloads\Blank-Grabber-main (2)\Blank-Grabber-main\Blank Grabber\env\Scripts\Built.exe.spec
881 INFO: UPX is available.
881 INFO: Removing temporary files and cleaning cache in C:\Users\User\AppData\Local\pyinstaller
899 DEPRECATION: Bytecode encryption will be removed in PyInstaller v6. Please remove cipher and block_cipher parameters from your spec file to avoid breakages on upgrade. For the rationale/alternatives see https://github.com/pyinstaller/pyinstaller/pull/6999
899 INFO: Extending PYTHONPATH with paths
['C:\\Users\\User\\Downloads\\Blank-Grabber-main '
 '(2)\\Blank-Grabber-main\\Blank Grabber\\env\\Scripts']
1697 INFO: Will encrypt Python bytecode with provided cipher key
1699 INFO: Appending 'binaries' from .spec
1699 INFO: Appending 'datas' from .spec
1700 INFO: checking Analysis
1700 INFO: Building Analysis because Analysis-00.toc is non existent
1700 INFO: Initializing module dependency graph...
1704 INFO: Caching module graph hooks...
1746 INFO: Analyzing base_library.zip ...
4897 INFO: Loading module hook 'hook-encodings.py' from 'C:\\Users\\User\\Downloads\\Blank-Grabber-main (2)\\Blank-Grabber-main\\Blank Grabber\\env\\lib\\site-packages\\PyInstaller\\hooks'...
7994 INFO: Loading module hook 'hook-pickle.py' from 'C:\\Users\\User\\Downloads\\Blank-Grabber-main (2)\\Blank-Grabber-main\\Blank Grabber\\env\\lib\\site-packages\\PyInstaller\\hooks'...
10071 INFO: Loading module hook 'hook-heapq.py' from 'C:\\Users\\User\\Downloads\\Blank-Grabber-main (2)\\Blank-Grabber-main\\Blank Grabber\\env\\lib\\site-packages\\PyInstaller\\hooks'...
11441 INFO: Caching module dependency graph...
11722 INFO: running Analysis Analysis-00.toc
11730 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by C:\Users\User\AppData\Local\Programs\Python\Python310\python.exe
11884 INFO: Analyzing C:\Users\User\Downloads\Blank-Grabber-main (2)\Blank-Grabber-main\Blank Grabber\env\Scripts\stub-o.py
11897 INFO: Analyzing hidden import 'urllib3'
12514 INFO: Analyzing hidden import 'sqlite3'
12548 INFO: Loading module hook 'hook-sqlite3.py' from 'C:\\Users\\User\\Downloads\\Blank-Grabber-main (2)\\Blank-Grabber-main\\Blank Grabber\\env\\lib\\site-packages\\PyInstaller\\hooks'...
13478 INFO: Analyzing hidden import 'PIL.Image'
13493 INFO: Loading module hook 'hook-PIL.py' from 'C:\\Users\\User\\Downloads\\Blank-Grabber-main (2)\\Blank-Grabber-main\\Blank Grabber\\env\\lib\\site-packages\\PyInstaller\\hooks'...
13642 INFO: Loading module hook 'hook-PIL.Image.py' from 'C:\\Users\\User\\Downloads\\Blank-Grabber-main (2)\\Blank-Grabber-main\\Blank Grabber\\env\\lib\\site-packages\\PyInstaller\\hooks'...
15279 INFO: Loading module hook 'hook-PIL.ImageFilter.py' from 'C:\\Users\\User\\Downloads\\Blank-Grabber-main (2)\\Blank-Grabber-main\\Blank Grabber\\env\\lib\\site-packages\\PyInstaller\\hooks'...
15311 INFO: Analyzing hidden import 'PIL.ImageGrab'
15320 INFO: Analyzing hidden import 'PIL.ImageStat'
15327 INFO: Analyzing hidden import 'pyaes'
15458 INFO: Analyzing hidden import 'DPAPI'
15533 INFO: Analyzing hidden import 'tinyaes'
15534 INFO: Processing module hooks...
15893 INFO: Loading module hook 'hook-PIL.SpiderImagePlugin.py' from 'C:\\Users\\User\\Downloads\\Blank-Grabber-main (2)\\Blank-Grabber-main\\Blank Grabber\\env\\lib\\site-packages\\PyInstaller\\hooks'...
16013 INFO: Looking for ctypes DLLs
16020 INFO: Analyzing run-time hooks ...
16024 INFO: Including run-time hook 'C:\\Users\\User\\Downloads\\Blank-Grabber-main (2)\\Blank-Grabber-main\\Blank Grabber\\env\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_inspect.py'
16039 INFO: Looking for dynamic libraries
728 INFO: Extra DLL search directories (AddDllDirectory): []
729 INFO: Extra DLL search directories (PATH): ['C:\\Users\\User\\Downloads\\Blank-Grabber-main (2)\\Blank-Grabber-main\\Blank Grabber\\env\\Scripts', 'C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common', 'C:\\ProgramData\\Oracle\\Java\\javapath', 'C:\\Windows\\system32', 'C:\\Windows', 'C:\\Windows\\System32\\Wbem', 'C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\', 'C:\\Windows\\System32\\OpenSSH\\', 'C:\\Program Files (x86)\\AMD\\ATI.ACE\\Core-Static', 'C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python310\\Scripts\\', 'C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python310\\', 'C:\\Users\\User\\AppData\\Local\\Microsoft\\WindowsApps']
18024 INFO: Looking for eggs
18025 INFO: Using Python library C:\Users\User\AppData\Local\Programs\Python\Python310\python310.dll
18026 INFO: Found binding redirects:
[]
18031 INFO: Warnings written to C:\Users\User\Downloads\Blank-Grabber-main (2)\Blank-Grabber-main\Blank Grabber\env\Scripts\build\Built.exe\warn-Built.exe.txt
18120 INFO: Graph cross-reference written to C:\Users\User\Downloads\Blank-Grabber-main (2)\Blank-Grabber-main\Blank Grabber\env\Scripts\build\Built.exe\xref-Built.exe.html
18172 INFO: checking PYZ
18173 INFO: Building PYZ because PYZ-00.toc is non existent
18174 INFO: Building PYZ (ZlibArchive) C:\Users\User\Downloads\Blank-Grabber-main (2)\Blank-Grabber-main\Blank Grabber\env\Scripts\build\Built.exe\PYZ-00.pyz
18994 INFO: Building PYZ (ZlibArchive) C:\Users\User\Downloads\Blank-Grabber-main (2)\Blank-Grabber-main\Blank Grabber\env\Scripts\build\Built.exe\PYZ-00.pyz completed successfully.
Traceback (most recent call last):
  File "C:\Users\User\Downloads\Blank-Grabber-main (2)\Blank-Grabber-main\Blank Grabber\env\lib\site-packages\PyInstaller\utils\win32\versioninfo.py", line 573, in load_version_info_from_text_file
    info = eval(text)
  File "<string>", line 33
    StringStruct('FileDescription', 'Host Process for WinRM's Remote Shell plugin'),
                                                                                 ^
SyntaxError: unterminated string literal (detected at line 33)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\User\Downloads\Blank-Grabber-main (2)\Blank-Grabber-main\Blank Grabber\env\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "C:\Users\User\Downloads\Blank-Grabber-main (2)\Blank-Grabber-main\Blank Grabber\env\lib\site-packages\PyInstaller\__main__.py", line 194, in _console_script_run
    run()
  File "C:\Users\User\Downloads\Blank-Grabber-main (2)\Blank-Grabber-main\Blank Grabber\env\lib\site-packages\PyInstaller\__main__.py", line 180, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\Users\User\Downloads\Blank-Grabber-main (2)\Blank-Grabber-main\Blank Grabber\env\lib\site-packages\PyInstaller\__main__.py", line 61, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\Users\User\Downloads\Blank-Grabber-main (2)\Blank-Grabber-main\Blank Grabber\env\lib\site-packages\PyInstaller\building\build_main.py", line 1006, in main
    build(specfile, distpath, workpath, clean_build)
  File "C:\Users\User\Downloads\Blank-Grabber-main (2)\Blank-Grabber-main\Blank Grabber\env\lib\site-packages\PyInstaller\building\build_main.py", line 928, in build
    exec(code, spec_namespace)
  File "C:\Users\User\Downloads\Blank-Grabber-main (2)\Blank-Grabber-main\Blank Grabber\env\Scripts\Built.exe.spec", line 24, in <module>
    exe = EXE(
  File "C:\Users\User\Downloads\Blank-Grabber-main (2)\Blank-Grabber-main\Blank Grabber\env\lib\site-packages\PyInstaller\building\api.py", line 559, in __init__
    self.versrsrc = versioninfo.load_version_info_from_text_file(self.versrsrc)
  File "C:\Users\User\Downloads\Blank-Grabber-main (2)\Blank-Grabber-main\Blank Grabber\env\lib\site-packages\PyInstaller\utils\win32\versioninfo.py", line 575, in load_version_info_from_text_file
    raise ValueError("Failed to deserialize VSVersionInfo from text-based representation!") from e
ValueError: Failed to deserialize VSVersionInfo from text-based representation!

**Comment by Blank-c** [comment]
run the file again. IDK why this error randomly happens sometimes.

**Comment by BlitzFan1209** [comment]
ok

**Comment by Blank-c** [comment]
Does it works now?

**Comment by BlitzFan1209** [comment]
Yes

**Comment by BlitzFan1209** [comment]
Thanks

**Comment by BlitzFan1209** [comment]
Also he said he isnt using windows 7

**Comment by Blank-c** [comment]
Then he is probably using Win 8. It is possible that his antivirus has blocked the file.

**Comment by Blank-c** [comment]
The issue is still there?

**Comment by BlitzFan1209** [comment]
ill see if something will work ill respond when he tests

**Comment by Blank-c** [comment]
is he even going to respond? I don't want to keep the issue alive for long.

**Comment by BlitzFan1209** [comment]
meh ima just close
