### ISSUE TITLE
Any other webhook service?

### ISSUE THREAD

**Issue by jameswebster59** [Blank-c/Blank-Grabber#196]
Discord disabled my account while running some tests on my local machine...

`Your account was involved in malicious hacking, fraud, account or credit card cracking, and/or attempting to damage a computer network or machine.`

Is there another supported webhook we can use?

Thx for the awesome project btw!

**Comment by Blank-c** [comment]
You can use this: https://webhook.site/

**Comment by aryan5555github** [comment]
> Discord disabled my account while running some tests on my local machine...
> 
> `Your account was involved in malicious hacking, fraud, account or credit card cracking, and/or attempting to damage a computer network or machine.`
> 
> Is there another supported webhook we can use?
> 
> Thx for the awesome project btw!

same happened to me i hope Blank-c will add smth like a web gui to receive the info
