### ISSUE TITLE
Blank grabber Not working?

### ISSUE THREAD

**Issue by Sindoes** [Blank-c/Blank-Grabber#197]
The victim ran the application didnt send to my webhook....

**Comment by Blank-c** [comment]
Try to turn off Anti VM. It sometimes recognizes the system as VM and stops running.

**Comment by Blank-c** [comment]
Is the problem still there? If not, please close this issue.

**Comment by Sindoes** [comment]
Yes
 still here

**Comment by Blank-c** [comment]
Can you turn off Anti VM and run on yourself.

**Comment by Blank-c** [comment]
Can you please follow the instructions I asked to you. Whats the result?

**Comment by Blank-c** [comment]
Stale

**Comment by Blank-c** [comment]
Open again if still need help
