### ISSUE TITLE
Passwords encrypted & no token

### ISSUE THREAD

**Issue by Gaminguide1000** [Blank-c/Blank-Grabber#20]
It doesnt send the token, and the passwords are all encrypted (which btw makes sense)

**Comment by Gaminguide1000** [comment]
yes

**Comment by Blank-c** [comment]
It will not work for VM passwords and probably cookies too. If the VM does not have discord, it cannot get the token.

**Comment by Gaminguide1000** [comment]
it does have discord & chrome, still no token. Ima try on real machine now for chrome stuff, but still, no token even tough it has discord

**Comment by Blank-c** [comment]
Are you using a discord mod like bluecord/greencord etc??

**Comment by Gaminguide1000** [comment]
nope, blank discord, completely normal. Yes i am logged into an account

**Comment by Gaminguide1000** [comment]
In normal machine it works completely, in vm nothing works

**Comment by Blank-c** [comment]
Can you check if "AppData/roaming/discord/Local State/leveldb folder" exist? Most grabbers does not work on vm tho.

**Comment by Gaminguide1000** [comment]
Nope, there is only "Local Storage"

**Comment by Blank-c** [comment]
¯\_(ツ)_/¯

**Comment by Gaminguide1000** [comment]
ok, ooks like a discord bug (￣ ‘i ￣;)( *^-^)ρ(*╯^╰)(ノへ￣、)o(￣┰￣*)ゞ(#｀-_ゝ-)（＞人＜；）( ˘︹˘ )（︶^︶）ヽ（≧□≦）ノ(￣ε(#￣)☆╰╮o(￣皿￣///)___*( ￣皿￣)/#____
