### ISSUE TITLE
fix AV Site Blocker after Infection

### ISSUE THREAD

**Issue by noahmajors** [Blank-c/Blank-Grabber#200]
I already referenced your pinned issue about removing the infection on a machine, but even after cleaning, the AV sites still seem to have persisted. What would the steps be to restoring access to these sites?

**Comment by noahmajors** [comment]
no errors. worked like a charm. would recommend pinning this or referencing in the readme next to where you referenced how to uninstall

**Comment by Blank-c** [comment]
> no errors. worked like a charm. would recommend pinning this or referencing in the readme next to where you referenced how to uninstall

There actually is. In the pinned issue, I have provided a hyperlink to allow access to AVs.
