### ISSUE TITLE
Help with my own code

### ISSUE THREAD

**Issue by KiritoIsMid** [Blank-c/Blank-Grabber#202]
SO I have some of your code and my code inm the grabber I made and every time i try to build it it always says module notnamed 

![image](https://github.com/Blank-c/Blank-Grabber/assets/111599854/3b2bfefb-2acb-4f10-94ea-ae635a26393c)

**Comment by Blank-c** [comment]
If you used any obfuscations, then you need to either place all the import statements outside the obfuscated code or mark them with hidden imports of Pyinstaller.
