### ISSUE TITLE
Won't let me build

### ISSUE THREAD

**Issue by KoomzyYT** [Blank-c/Blank-Grabber#203]
No Python at '"C:\Program Files\Python311\python.exe'
Fatal error in launcher: Unable to create process using '"C:\Users\Ry\Downloads\Blank-Grabber-main\Blank-Grabber-main\Blank Grabber\env\Scripts\python.exe"  "C:\Users\Ry\OneDrive\Desktop\blank grabber-20230506T131903Z-001\blank grabber-20230506T131903Z-001\blank grabber\Blank-Grabber-main\Blank Grabber\env\Scripts\pyinstaller.exe" --onefile --clean --noconsole --noconfirm main-o.py --name "Built.exe" -i NONE --hidden-import urllib3 --hidden-import sqlite3 --hidden-import PIL.Image --hidden-import PIL.ImageGrab --hidden-import PIL.ImageStat --hidden-import pyaes --hidden-import win32crypt --hidden-import json --add-data Camera;. --add-data config.json;. --add-data getPass;. --version-file version.txt  ': The system cannot find the file specified.

Building failed!
Press any key to continue . . .

This is the error I keep getting I'm not sure hwo to fix it

**Comment by KoomzyYT** [comment]
If someone can help me here is my discord: KoomzyYT#8200

**Comment by Blank-c** [comment]
Can you run this command in cmd. 
`where python && python --version`

**Comment by Blank-c** [comment]
@KoomzyYT you alive?

**Comment by BlitzFan1209** [comment]
i killed him

**Comment by Blank-c** [comment]
RIP
