### ISSUE TITLE
"Python is not installed!" error.

### ISSUE THREAD

**Issue by LordCrestfallen** [Blank-c/Blank-Grabber#205]
I have Python 3.11.3. It's added to path. I have antivirus off. I have zero clue why this is happening.

![image_2023-05-27_230006200](https://github.com/Blank-c/Blank-Grabber/assets/131706299/45adcd2d-25cc-44d6-8aee-dad1a6b53667)
![image_2023-05-27_230021827](https://github.com/Blank-c/Blank-Grabber/assets/131706299/8bcaf356-05d8-4d90-94bc-dde06bdd552a)

**Comment by Blank-c** [comment]
Can you run the command `python --version` in cmd

**Comment by Blank-c** [comment]
Can you type `where python` in cmd

**Comment by LordCrestfallen** [comment]
![image_2023-05-28_002730985](https://github.com/Blank-c/Blank-Grabber/assets/131706299/6bfa2b0f-d503-4d48-b696-db6b4e2e3aee)

**Comment by Blank-c** [comment]
> ![image_2023-05-28_002730985](https://user-images.githubusercontent.com/131706299/241506314-6bfa2b0f-d503-4d48-b696-db6b4e2e3aee.png)

Hey can you try to run these commands one by one
```bat
where python > NUL 2>&1
echo %errorlevel%
python --version > NUL 2>&1
echo %errorlevel%
```

Also I have updated the code, check if that works for you?

**Comment by Blank-c** [comment]
And at last if none of this works
Do this
1) Open CMD in the builder's folder (the folder containing the file gui.py)
2) Type `pip install customtkinter pillow`
3) Type `python gui.py`

**Comment by Blank-c** [comment]
Tell me which one worked for you

**Comment by LordCrestfallen** [comment]
I didn't do any of your steps, but your new changes to the python checker have worked for me. Thanks, man.
