### ISSUE TITLE
Error python not installed

### ISSUE THREAD

**Issue by Pato06688** [Blank-c/Blank-Grabber#206]
![image](https://github.com/Blank-c/Blank-Grabber/assets/128635054/8312d82d-c97b-44ab-aa9d-ddf6993a4c39)

**Comment by Blank-c** [comment]
Can you open cmd and type `where python && python --version`

**Comment by luigilessluigieatscum** [comment]
im having the same issue, i wrote that in cmd and this showed up
![image](https://github.com/Blank-c/Blank-Grabber/assets/99555189/4b9e9b6b-98c5-415a-8524-9bde6d425a89)

**Comment by Blank-c** [comment]
#152

**Comment by luigilessluigieatscum** [comment]
> #152

tysm it worked

**Comment by Blank-c** [comment]
I am glad that your problem is fixed.

@Pato06688 Wbu?

**Comment by Blank-c** [comment]
Stale
