### ISSUE TITLE
File Binder

### ISSUE THREAD

**Issue by Pandiyt** [Blank-c/Blank-Grabber#209]
The file binder is not working! It only opens the binded file but not the stub.

**Comment by Blank-c** [comment]
Did you try with Anti VM off?

**Comment by aryan5555github** [comment]
Happened to me to buy with ex file

**Comment by Blank-c** [comment]
@Pandiyt You tried what I asked you to?

**Comment by Pandiyt** [comment]
@Blank-c  no but imma try

**Comment by Pandiyt** [comment]
yeah aight now it works thx

**Comment by Blank-c** [comment]
I am glad that your problem is fixed.
