### ISSUE TITLE
Still no Discord Message

### ISSUE THREAD

**Issue by Gaminguide1000** [Blank-c/Blank-Grabber#21]
YEEEEE again. Again no message, made on a REAL MACHINE, with the leveldb folder. All antivirus stuff & Firewall off

**Comment by Blank-c** [comment]
Try the script instead of exe, if it works, then the exe should work.

**Comment by Gaminguide1000** [comment]
Also tried wigth the script, didnt work

**Comment by Blank-c** [comment]
I will look into the problem soon

**Comment by Gaminguide1000** [comment]
Did you change stuff??

**Comment by Gaminguide1000** [comment]
Would liek to know

**Comment by Gaminguide1000** [comment]
Bruh winrar cut out some files, bc of this i didnt had some stuff, gonna look into it
