### ISSUE TITLE
Python is Not Installed! Error

### ISSUE THREAD

**Issue by SharkyMantisGD** [Blank-c/Blank-Grabber#211]
I installed the latest Python version, and when I run Builder, it says "Python is not installed" 
How do I fix that?
Btw I have a Windows 11 and I installed Python 3.11 64 Bit

**Comment by Blank-c** [comment]
When installing python, you have to tick the "Add Python to PATH" option in the first screen of the installer.

**Comment by SharkyMantisGD** [comment]
> When installing python, you have to tick the "Add Python to PATH" option in the first screen of the installer.

oh ok ill try

**Comment by SharkyMantisGD** [comment]
it worked

**Comment by SharkyMantisGD** [comment]
it worked
