### ISSUE TITLE
Drag and Drop Error

### ISSUE THREAD

**Issue by SharkyMantisGD** [Blank-c/Blank-Grabber#212]
When i try to drag the Blank-Grabber-main file to file explorer, an error shows up. Ive tried drag and drop on 3 different compressor applications and all have the same error.

**Comment by Blank-c** [comment]
Whats the error? I don't think its an error will the grabber but I can help.

**Comment by SharkyMantisGD** [comment]
> Whats the error? I don't think its an error will the grabber but I can help. But first make sure your antivirus is off.

What application did you use to transfer the files over from?

**Comment by SharkyMantisGD** [comment]
its fixed
