### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by SharkyMantisGD** [Blank-c/Blank-Grabber#213]
Is it possible to get webhooks from other servers? Or does it have to be from a server you own/have high role to see the webhooks?

Can I see a bot's discord token? Like Dyno, and MEE6, etc..

Also, how do I do it to other users and not just me? i know im stupid but im new to this lol

**Comment by Blank-c** [comment]
You cannot get webhook from any server if you don't have permission there.

You can only see the token of your own bot.

If you need other peoples' token you need to use malware like this.
