### ISSUE TITLE
how do i fix this?

### ISSUE THREAD

**Issue by darknightmc80** [Blank-c/Blank-Grabber#214]
![image](https://github.com/Blank-c/Blank-Grabber/assets/135541360/9a4f117a-0120-44ba-b4f6-5e1f82958860)

**Comment by Blank-c** [comment]
Can you type `pip install customtkinter urllib3 pillow`

If it says something like `module not found pip`
Then reinstall python.

**Comment by darknightmc80** [comment]
> Can you type `pip install customtkinter urllib3 pillow` in command prompt.
> 
> If it says something like `module not found pip` then type `python -m ensurepip` and type the command again.
> 
> If still getting the same error then reinstall Python.

i rentralled python but it says i dont have phython instralled but i have phython instralled

**Comment by Blank-c** [comment]
Did you select the `Add Python to PATH` option?

**Comment by darknightmc80** [comment]
thanks worked
