### ISSUE TITLE
ISSUE

### ISSUE THREAD

**Issue by gqgqgerg** [Blank-c/Blank-Grabber#217]
python: cant open file bla bla bla bla gui.py

**Comment by Blank-c** [comment]
"bla bla bla bla" won't do, you need to send the screenshot or tell the exact error.

Also make sure you have extracted the zip file before running the builder.

**Comment by noahmajors** [comment]
make sure the .zip is extracted. then run the Builder.bat rather than gui.py

if it still doesnt work, i would double check that your python installation is in PATH
