### ISSUE TITLE
the anti VM or what ever aint working can you fix

### ISSUE THREAD

**Issue by ashton1342** [Blank-c/Blank-Grabber#218]

**Comment by noahmajors** [comment]
Anti-VM is hardcoded with blacklisted items. These blacklisted items include UUIDS, ComputerNames, Users, and Tasks. It is possible that your VM's information is not in the blacklist.

Did you change some of these values yourself?
Are you using a modified VM?
Can you please share with us the UUID of the VM?
(These help to see if your VM is just bypassing the detection or if Anti-VM is actually broken)

**Comment by Blank-c** [comment]
@ashton1342 If I am not wrong, you mean you enabled Anti VM but the grabber is still working on your VM?

Also please give the information asked above.
