### ISSUE TITLE
virtual environment error when not in virtual environment

### ISSUE THREAD

**Issue by Tibosity** [Blank-c/Blank-Grabber#220]
I get the following error whenever I try to build the executable

`Error while creating virtual environment ("python -m venv env"): Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
`

These are the options I have checked while still getting this error, 
https://imgur.com/a/y3jb9fy

**Comment by Blank-c** [comment]
Uninstall every python you have using control panel and follow this: https://github.com/Blank-c/Blank-Grabber/issues/152

**Comment by Blank-c** [comment]
@Tibosity Is your issue solved?
