### ISSUE TITLE
Why does my browser close when I open the stealer?

### ISSUE THREAD

**Issue by moshiax** [Blank-c/Blank-Grabber#222]
I remember this was not the case in older versions.

**Comment by Blank-c** [comment]
Many browsers (including chrome) now lock the Cookies file preventing the grabber to copy the file, so now the grabber closes the browsers.

**Comment by moshiax** [comment]
Oh, does this mean that older versions now also close the browser?

**Comment by Blank-c** [comment]
> Oh, does this mean that older versions now also close the browser?

No they won't. Just the viersion which released today.

**Comment by moshiax** [comment]
i mean older version of stealers

> > Oh, does this mean that older versions now also close the browser?
> 
> No they won't. Just the version which released today and from now on.

**Comment by Blank-c** [comment]
> i mean older version of stealers
> 
> > > Oh, does this mean that older versions now also close the browser?
> > 
> > 
> > No they won't. Just the version which released today and from now on.

No the older version of the stealer don't close the browsers.

**Comment by moshiax** [comment]
thank you

**Comment by moshiax** [comment]
That is, if I download the old version of the builder, I can make a grabber that will not close the browser and will steal cookies?

**Comment by moshiax** [comment]
yep, I downloaded the version from Jun 12, 2023 and made a grabber that stole my cookies without closing the browser, so I think newer versions will be worse

**Comment by Blank-c** [comment]
> yep, I downloaded the version from Jun 12, 2023 and made a grabber that stole my cookies without closing the browser, so I think newer versions will be worse

Just in case, I'll look at it.
