### ISSUE TITLE
password for rar?

### ISSUE THREAD

**Issue by MRFN088** [Blank-c/Blank-Grabber#224]
Blank u sneaky little bugger what is the rar password after grabbing?

**Comment by XierOnTop** [comment]
default is blank, whatever u set it to when first openeing before the builder even opens but after running bat

**Comment by MRFN088** [comment]
> default is blank, whatever u set it to when first openeing before the builder even opens but after running bat

yo whats ur discord

**Comment by MRFN088** [comment]
i 

> default is blank, whatever u set it to when first openeing before the builder even opens but after running bat

i keep getting incorrect

**Comment by XierOnTop** [comment]
Just reinstall the folder from github again, and redo the steps it first asks if you wanted to be updates Y or N then asks for Password. Make sure you know what it is.

**Comment by XierOnTop** [comment]
> 
Xier#7163

**Comment by MRFN088** [comment]
> 

got it fixed dw

**Comment by Blank-c** [comment]
Solved I guess. I wonder why people keep asking this even though the builder asks them to set the password at first.
