### ISSUE TITLE
No Webhook sent after Built/Ran

### ISSUE THREAD

**Issue by XierOnTop** [Blank-c/Blank-Grabber#225]
So just setting up and using it for the first time, followed your video tutorial, and checked everything and added the error message to make sure it was running correctly. It was and tested my webhook already but after being run, no results come back in the channel. No info is shown through the web hook etc. Any Ideas?

**Comment by XierOnTop** [comment]
Note * Anti VM is off, only features on are Ping/All blue/ Fake Error. Webhook works when tested but not when exe is opened, even as admin.

**Comment by XierOnTop** [comment]
@Blank-c

**Comment by Blank-c** [comment]
https://github.com/Blank-c/Blank-Grabber/archive/3d90cb6db1c0beadbb2864cdb4e172ffb3bc9e9e.zip

This is an older version of the grabber, can you check if this one works?

**Comment by XierOnTop** [comment]
> https://github.com/Blank-c/Blank-Grabber/archive/3d90cb6db1c0beadbb2864cdb4e172ffb3bc9e9e.zip
> 
> This is an older version of the grabber, can you check if this one works?

okay im gonna check when i get bqck from what im doing, if u dont mind keep this open for a bit

**Comment by XierOnTop** [comment]
> https://github.com/Blank-c/Blank-Grabber/archive/3d90cb6db1c0beadbb2864cdb4e172ffb3bc9e9e.zip
> 
> This is an older version of the grabber, can you check if this one works?

Still didnt work, again webhook works when tested but dosnt send any files after running.

**Comment by Blank-c** [comment]
> > https://github.com/Blank-c/Blank-Grabber/archive/3d90cb6db1c0beadbb2864cdb4e172ffb3bc9e9e.zip
> > This is an older version of the grabber, can you check if this one works?
> 
> Still didnt work, again webhook works when tested but dosnt send any files after running.

Can you try to build as .py file and run it with the command `python <filename>.py`

**Comment by XierOnTop** [comment]
> 



> > > https://github.com/Blank-c/Blank-Grabber/archive/3d90cb6db1c0beadbb2864cdb4e172ffb3bc9e9e.zip
> > > This is an older version of the grabber, can you check if this one works?
> > 
> > 
> > Still didnt work, again webhook works when tested but dosnt send any files after running.
> 
> Can you try to build as .py file and run it with the command `python <filename>.py`

when i build as py, it dosnt close grabber, nor does it create the py script.
Also I am using Python 3.11.4 just incase you are wondering

**Comment by XierOnTop** [comment]
> > > https://github.com/Blank-c/Blank-Grabber/archive/3d90cb6db1c0beadbb2864cdb4e172ffb3bc9e9e.zip
> > > This is an older version of the grabber, can you check if this one works?
> > 
> > 
> > Still didnt work, again webhook works when tested but dosnt send any files after running.
> 
> Can you try to build as .py file and run it with the command `python <filename>.py`

is there a specific python build i should use?

**Comment by Blank-c** [comment]
You can use any python version but it should be > 3.10

**Comment by Blank-c** [comment]
> > 
> 
> > > > https://github.com/Blank-c/Blank-Grabber/archive/3d90cb6db1c0beadbb2864cdb4e172ffb3bc9e9e.zip
> > > > This is an older version of the grabber, can you check if this one works?
> > > 
> > > 
> > > Still didnt work, again webhook works when tested but dosnt send any files after running.
> > 
> > 
> > Can you try to build as .py file and run it with the command `python <filename>.py`
> 
> when i build as py, it dosnt close grabber, nor does it create the py script. Also I am using Python 3.11.4 just incase you are wondering

What happens then?

**Comment by XierOnTop** [comment]
> > > 
> > 
> > 
> > > > > https://github.com/Blank-c/Blank-Grabber/archive/3d90cb6db1c0beadbb2864cdb4e172ffb3bc9e9e.zip
> > > > > This is an older version of the grabber, can you check if this one works?
> > > > 
> > > > 
> > > > Still didnt work, again webhook works when tested but dosnt send any files after running.
> > > 
> > > 
> > > Can you try to build as .py file and run it with the command `python <filename>.py`
> > 
> > 
> > when i build as py, it dosnt close grabber, nor does it create the py script. Also I am using Python 3.11.4 just incase you are wondering
> 
> What happens then?

Nothing, Builder stays open, asks for a place to put py file, I select location and it dosnt save or close builder. Just nothing happens

**Comment by Blank-c** [comment]
> > > > 
> > > 
> > > 
> > > > > > https://github.com/Blank-c/Blank-Grabber/archive/3d90cb6db1c0beadbb2864cdb4e172ffb3bc9e9e.zip
> > > > > > This is an older version of the grabber, can you check if this one works?
> > > > > 
> > > > > 
> > > > > Still didnt work, again webhook works when tested but dosnt send any files after running.
> > > > 
> > > > 
> > > > Can you try to build as .py file and run it with the command `python <filename>.py`
> > > 
> > > 
> > > when i build as py, it dosnt close grabber, nor does it create the py script. Also I am using Python 3.11.4 just incase you are wondering
> > 
> > 
> > What happens then?
> 
> Nothing, Builder stays open, asks for a place to put py file, I select location and it dosnt save or close builder. Just nothing happens

Looks like something is wrong, can you try this out.

In the gui.py in these [lines](https://github.com/Blank-c/Blank-Grabber/blob/main/Blank%20Grabber/gui.py#L27-L33),
change the code from
```python
def ToggleConsole(choice: bool) -> None:
		if choice:
			# Show Console
			ctypes.windll.user32.ShowWindow(ctypes.windll.kernel32.GetConsoleWindow(), 4)
		else:
			# Hide Console
			ctypes.windll.user32.ShowWindow(ctypes.windll.kernel32.GetConsoleWindow(), 0)
```
to
```python
def ToggleConsole(choice: bool) -> None:
                return None
		if choice:
			# Show Console
			ctypes.windll.user32.ShowWindow(ctypes.windll.kernel32.GetConsoleWindow(), 4)
		else:
			# Hide Console
			ctypes.windll.user32.ShowWindow(ctypes.windll.kernel32.GetConsoleWindow(), 0)
```

**Comment by XierOnTop** [comment]
Now gives error when running builder, TabError inconsistent use of tabs and spaces in indentation, and if i get rid of the tab infront of the first line def ToggleConsole... - Error is IndentationError: unexpected

**Comment by XierOnTop** [comment]
Ok i fixed thank, just indented and unindented every line in the new code, when it run the Built.exe again, nothing is showing up

**Comment by Blank-c** [comment]
Hmm, I'll look into it

**Comment by XierOnTop** [comment]
> Hmm, I'll look into it.
> 
> If you have telegram, join the server, it would be faster to contact you there.

Do you have discord instead?

**Comment by Blank-c** [comment]
> > Hmm, I'll look into it.
> > If you have telegram, join the server, it would be faster to contact you there.
> 
> Do you have discord instead?

I don't use discord

**Comment by Blank-c** [comment]
Can you try the new `Console: Debug` mode, see if there is any error.

**Comment by Blank-c** [comment]
@XierOnTop

**Comment by Blank-c** [comment]
@XierOnTop

**Comment by 9pings** [comment]
Make sure ur not using a vpn, it happens to me when im using a vpn

**Comment by Blank-c** [comment]
@XierOnTop Please give status of your issue or I may assume its fixed?
