### ISSUE TITLE
unblock_sites.py not working

### ISSUE THREAD

**Issue by Nuclearpotato69** [Blank-c/Blank-Grabber#227]
i ran this on my system by accident and then was going to check another file using virus total and its still blocked

**Comment by Blank-c** [comment]
What did it say when you ran the file?

**Comment by Nuclearpotato69** [comment]
it didnt say anything it requesting something as admin so i let it then it did nothing not even a cmd opened

**Comment by Blank-c** [comment]
> it didnt say anything it requesting something as admin so i let it then it did nothing not even a cmd opened

Can you do this:

1) Run cmd as admin.
2) cd into the Extras directory, type `python unblock_sites.py`.

**Comment by Nuclearpotato69** [comment]
ty its fixed
