### ISSUE TITLE
Archive password not received

### ISSUE THREAD

**Issue by Vovilon12** [Blank-c/Blank-Grabber#228]
Archive password not received    
![image](https://github.com/Blank-c/Blank-Grabber/assets/137065993/bf4fff10-d851-4b34-9e56-f787610de2f0)

**Comment by Blank-c** [comment]
Archive password is the one you set when building it. If you left it empty, then the password is `blank`
If you want to check the password. Look for a file named `config.ini` in the same folder as `Builder.bat` file.
