### ISSUE TITLE
Whenever used as i used it on myself it did not work

### ISSUE THREAD

**Issue by ashton1342** [Blank-c/Blank-Grabber#229]
if can be fixed i would appreciate it the problem is when i used it on myself it did not show up in the discord webhook does anyone else have this problem?

**Comment by Blank-c** [comment]
Can you try the `Console: Debug` mode

**Comment by ashton1342** [comment]
i already did but i can try again

**Comment by ashton1342** [comment]
it just comes up with an error

**Comment by Blank-c** [comment]
> it just comes up with an error

Whats the error, please paste screenshot or the error itself.

**Comment by ashton1342** [comment]
basically it says on the top Administrator: ERROR

**Comment by Blank-c** [comment]
> basically it says on the top Administrator: ERROR

When does it say? When you run the stub or the builder?

Please attach screenshot

**Comment by ashton1342** [comment]
i gotta go rn but i can talk in about 3 hours+

**Comment by Blank-c** [comment]
> i gotta go rn but i can talk in about 3 hours+

Sure, send the screenshot when you get time.

**Comment by ashton1342** [comment]
> > i gotta go rn but i can talk in about 3 hours+
> 
> Sure, send the screenshot when you get time.

![Screenshot 2023-06-19 162420](https://github.com/Blank-c/Blank-Grabber/assets/101904173/132f0d57-c9cf-4572-8a91-ed44299fa139)
this is the thing but idk if you can hack me with this info so i just blurred out somethings

**Comment by Blank-c** [comment]
Oh did you turn off your antivirus?

**Comment by ashton1342** [comment]
OOOOOHHHHHHHHHHHHHHH

**Comment by ashton1342** [comment]
nvm i always have it off thats not the problem

**Comment by ashton1342** [comment]
wait nvm again ill try it one more time

**Comment by ashton1342** [comment]
nvm again it still says error lol

**Comment by ashton1342** [comment]
ok so i made it work but it dosent go through my webhook

**Comment by Blank-c** [comment]
> it just comes up with an error

Can you send the full screenshot please, unlike the last one that you blurred.

**Comment by Blank-c** [comment]
> ok so i made it work but it dosent go through my webhook

Try to build it in debug mode

**Comment by ashton1342** [comment]
ok i will try that again

**Comment by ashton1342** [comment]
ima restart my pc rq

**Comment by Blank-c** [comment]
If the stub show an error, please send ss.

**Comment by ashton1342** [comment]
![Screenshot 2023-06-19 162420](https://github.com/Blank-c/Blank-Grabber/assets/101904173/29cc7b64-f0a9-421b-a79f-8ebf2383fa0c)

**Comment by Blank-c** [comment]
Can you send the whole error

**Comment by Blank-c** [comment]
@ashton1342

**Comment by ashton1342** [comment]
oh sorry 

> @ashton1342
![Screenshot 2023-06-21 131530](https://github.com/Blank-c/Blank-Grabber/assets/101904173/39e1330d-8ad0-468b-9aeb-ed9e9a6c7b9b)

**Comment by ashton1342** [comment]
im not going to share my name though

**Comment by Blank-c** [comment]
Can you delete the `env` folder in the same directory as the builder, download the latest version of the grabber, turn off antivirus and then build normally.

**Comment by Blank-c** [comment]
@ashton1342

**Comment by ashton1342** [comment]
ok thanks

**Comment by ashton1342** [comment]
but it dosent send through the webhook any thoughts?

**Comment by ashton1342** [comment]
but i dont have the discord app i only have the website does that interfere with it

**Comment by Blank-c** [comment]
> but i dont have the discord app i only have the website does that interfere with it

No it should not interfere with. Please try to run the debug build and see if it shows any error.

**Comment by Blank-c** [comment]
You there?

**Comment by ashton1342** [comment]
sorry

**Comment by ashton1342** [comment]
> > but i dont have the discord app i only have the website does that interfere with it
> 
> No it should not interfere with. Please try to run the debug build and see if it shows any error.

ive been but i can try again

**Comment by ashton1342** [comment]
soooo it worked but i used it on myself and its not sending to my webhook and shows this:
![Screenshot 2023-06-24 164350](https://github.com/Blank-c/Blank-Grabber/assets/101904173/3fe3b3e1-d316-4a62-8189-c3e37836e98c)

**Comment by Blank-c** [comment]
You need internet connection + if you are using a vpn, you need to disconnect from it.

**Comment by Blank-c** [comment]
Also check if you are able to do `curl https://gstatic.com/generate_204`

**Comment by ashton1342** [comment]
> You need internet connection + if you are using a vpn, you need to disconnect from it.

OOOOOOOOOHHHHHHHHHH

**Comment by ashton1342** [comment]
ok so it works it just doesn't send to my webhook BUT my internet sucks so I gotta turn on my vpn to see if it works and I think that's why but I will seek out my internet problem so don't worry...yet

**Comment by Blank-c** [comment]
So, is your problem solved?

**Comment by ashton1342** [comment]
no because whenever i use it, it dosent send to the wehook even with normal internet and not a vpn

**Comment by Blank-c** [comment]
> Also check if you are able to do `python -c "from urllib.request import urlopen;print(urlopen('https://gstatic.com/generate_204').status)"` and it prints 204.

did you try it?

**Comment by Blank-c** [comment]
@ashton1342

**Comment by Blank-c** [comment]
@ashton1342 You alive?

**Comment by ashton1342** [comment]
LOL sorry

**Comment by Blank-c** [comment]
So can try the latest update and tell me if it works for you

**Comment by Blank-c** [comment]
Should I assume that the problem is fixed?

**Comment by aryan5555github** [comment]
@ashton1342 reinstall python and blank graber files

**Comment by aryan5555github** [comment]
Is problem solved

**Comment by Blank-c** [comment]
@ashton1342 You good?

**Comment by aryan5555github** [comment]
@ashton1342 @ashton1342 r u ok?

**Comment by ashton1342** [comment]
yea lol sorry i was on vaca for a while

**Comment by ashton1342** [comment]
oh its just started working tysm I will send another issue if it doesn't work again so you can help me sorry for the long wait and thanks you for your patients with me
