### ISSUE TITLE
dist file

### ISSUE THREAD

**Issue by Gwil99** [Blank-c/Blank-Grabber#23]
when i finish making the grabber i cant find the dist file, is it in another directory or am i just stupid, any help would be appreciated

**Comment by Honezyx** [comment]
when i finish making the grabber i cant find the dist file, is it in another directory or am i just stupid, any help would be appreciated

**Comment by Blank-c** [comment]
._.

The dist folder will be in the same directory. If it is not, try to reinstall pyinstaller. (This is not a problem related to the grabber)
