### ISSUE TITLE
winrar asking for a password

### ISSUE THREAD

**Issue by Rezzerog** [Blank-c/Blank-Grabber#230]
whats the password

**Comment by Blank-c** [comment]
Dude, whe you ran the builder first time, it asked you two questions.

1) Whether you want to keep the update checker on or not.
2) The password for the archive (if you left it empty, the password is 'blank').

**Comment by Rezzerog** [comment]
is there a way to check what it is?

**Comment by Rezzerog** [comment]
nvm thank you i got it have a good day

**Comment by Blank-c** [comment]
> nvm thank you i got it have a good day

In future, in case you forgot. The password is inside the `config.ini` file in the same folder as the builder.
