### ISSUE TITLE
Says "Python not installed", even if it already is.

### ISSUE THREAD

**Issue by twistyohnah** [Blank-c/Blank-Grabber#232]
for some reason it ask me to download python even though its installed?

**Comment by Blank-c** [comment]
In cmd type `python --version`
If it says not found, then install python (even if you already have).

Make sure to tick the Add Python To Path option in the python installer.

**Comment by twistyohnah** [comment]
ty!

**Comment by twistyohnah** [comment]
![image](https://github.com/Blank-c/Blank-Grabber/assets/132831997/c40eb4d8-9cc2-4825-8b3a-b9aaccee42c0)
?

**Comment by Blank-c** [comment]
https://github.com/Blank-c/Blank-Grabber/issues/152
