### ISSUE TITLE
Python installed but unable to detect.

### ISSUE THREAD

**Issue by twistyohnah** [Blank-c/Blank-Grabber#233]
still doesnt work it works with py file but doesnt send info???? also same issue 
![image](https://github.com/Blank-c/Blank-Grabber/assets/132831997/7e465439-a449-41cb-8b89-e968a0434192)

**Comment by Blank-c** [comment]
Did you follow the steps: #152

**Comment by twistyohnah** [comment]
yes

**Comment by twistyohnah** [comment]
ive already followed it still says the same

**Comment by Blank-c** [comment]
Did you disable all Pip, python, pythonw, idle switches?

**Comment by Codepulze** [comment]
isnt it pain to help people i mean if you find a ret... its hard to help isnt it?

**Comment by Blank-c** [comment]
It is difficult, but most of the people are not much experienced with stuff like this, so I have to do it since I manage the project ¯\\\_(ツ)_/¯,

**Comment by Blank-c** [comment]
@twistyohnah Is your problem solved?

**Comment by twistyohnah** [comment]
no pip switches has already been switched

**Comment by Blank-c** [comment]
> no pip switches has already been switched

Can you send screenshot of all your switches there.

**Comment by Codepulze** [comment]
> It is difficult, but most of the people are not much experienced with stuff like this, so I have to do it since I manage the project ¯\_(ツ)_/¯,

Yeah i would lost it already 💀 :DD

**Comment by twistyohnah** [comment]
![image](https://github.com/Blank-c/Blank-Grabber/assets/132831997/6429926a-55c1-4d5a-b33c-1e7acac18779)

**Comment by Blank-c** [comment]
execute this in cmd `where python && python --version`

**Comment by twistyohnah** [comment]
where?

**Comment by twistyohnah** [comment]
still deosnt work

**Comment by twistyohnah** [comment]
'python3' is not recognized as an internal or external command,
operable program or batch file.

**Comment by twistyohnah** [comment]
oh it it because for soem reaason it says my python is 3.10 does it have to be latest?

**Comment by Blank-c** [comment]
Any version above 3.10 would work but try the latest. Also make sure `python --version` prints the version. 
Do not use beta version of Python.

**Comment by twistyohnah** [comment]
beta?

**Comment by twistyohnah** [comment]
im not it looks like this
![Screenshot (1)](https://github.com/Blank-c/Blank-Grabber/assets/132831997/aaa351c8-7245-4c90-8a49-94178a0d5b2c)

**Comment by Blank-c** [comment]
dont use search box, like I said, use cmd to type the command

**Comment by twistyohnah** [comment]
type what?

**Comment by twistyohnah** [comment]
thoose are versions i have i wanted to see if any of them are on beta

**Comment by twistyohnah** [comment]
can you stay here?

**Comment by twistyohnah** [comment]
3.11.4

**Comment by twistyohnah** [comment]
also how do you use your umbral stealar?

**Comment by Blank-c** [comment]
Can you send screenshot instead? Also send the full command `where python && python --version`

**Comment by Blank-c** [comment]
> also how do you use your umbral stealar?

Isn't it pretty straight forward?

**Comment by twistyohnah** [comment]
im super new to c## thats why i was asking

**Comment by twistyohnah** [comment]
![image](https://github.com/Blank-c/Blank-Grabber/assets/132831997/15df8aee-a2ed-4385-8306-759d0f337dce)

**Comment by twistyohnah** [comment]
does your micro soft store have to work cuz i have infinite loading for mines for some reason

**Comment by Blank-c** [comment]
Do you have a telegram?

**Comment by Blank-c** [comment]
> does your micro soft store have to work cuz i have infinite loading for mines for some reason

it works

**Comment by twistyohnah** [comment]
well does mine have too?

**Comment by Blank-c** [comment]
> well does mine have too?

Not sure what you mean

**Comment by Blank-c** [comment]
> im super new to c## thats why i was asking

You want to use Umbral stealer, or just see the code?

**Comment by twistyohnah** [comment]
well my microsoft store doesnt launch and micrsoft store alliances got me there

**Comment by twistyohnah** [comment]
> > im super new to c## thats why i was asking
> 
> You want to use Umbral stealer, or just see the code?

you can decide whats best for me
since umbral stealer is more detected

**Comment by Blank-c** [comment]
> well my microsoft store doesnt launch and micrsoft store alliances got me there

Not really sure whats the issue with it, I use windows 10 and it works fine for me.

**Comment by Blank-c** [comment]
> > > im super new to c## thats why i was asking
> > 
> > 
> > You want to use Umbral stealer, or just see the code?
> 
> you can decide whats best for me since umbral stealer is more detected

This one is better, I can help you fix it. Do you have a telegram account?

**Comment by twistyohnah** [comment]
well

is there any other way we can get in contact?

**Comment by Blank-c** [comment]
> 

sorry I only use telegram

**Comment by twistyohnah** [comment]
ok

**Comment by twistyohnah** [comment]
do you have discord or anythng because i cant use my telephone number for it for some reason i apoligise but ima try in a second

**Comment by Blank-c** [comment]
> do you have discord or anythng because i cant use my telephone number for it for some reason i apoligise but ima try in a second

lets continue it here

**Comment by twistyohnah** [comment]
ok

**Comment by Blank-c** [comment]
so can you type this command `python -c "print('hello world')"`

**Comment by twistyohnah** [comment]
wher exactly?

**Comment by Blank-c** [comment]
> wher exactly?

![image](https://github.com/Blank-c/Blank-Grabber/assets/94945186/e8372499-b5d4-4385-8865-8b00d018dc22)

**Comment by twistyohnah** [comment]
can we continue tommorow as it is getting late for me but first step is done

**Comment by twistyohnah** [comment]
just tell me steps in chat and i will reveiw tommorow

**Comment by Blank-c** [comment]
> just tell me steps in chat and i will reveiw tommorow

sure. When you get time, send screenshots

**Comment by Blank-c** [comment]
thats the only step for now, the output will determine the next steps.

**Comment by Codepulze** [comment]
😆

**Comment by twistyohnah** [comment]
![image](https://github.com/Blank-c/Blank-Grabber/assets/132831997/5f194689-356f-42b2-8e7f-1f9284e456e6)

**Comment by twistyohnah** [comment]
> 😆

i don't see what's the funny part as we both have different time zones

**Comment by Blank-c** [comment]
I woner why. Everything works fine. Can you try the builder now? (Make sure you disable your AV)

**Comment by twistyohnah** [comment]
are you suppose to run as adminstrator?

**Comment by twistyohnah** [comment]
sorry for the issue i was trying to leaern so i can make my own logger btw

**Comment by Blank-c** [comment]
Don't worry.

> are you suppose to run as adminstrator?

Yes.

**Comment by twistyohnah** [comment]
ok

**Comment by twistyohnah** [comment]
also i had a question

**Comment by twistyohnah** [comment]
oh thank you its working now

**Comment by Blank-c** [comment]
> also i had a question

Sure ask here.

> oh thank you its working now

Great!

**Comment by twistyohnah** [comment]
> 

is it possible for you to help me with my own tiy project that im working on? ill get telegram if i need to

**Comment by Blank-c** [comment]
> 

You can join the group and dm me or ask stuff in the group (so others may help you too).

**Comment by twistyohnah** [comment]
ok
