### ISSUE TITLE
Best grabber i have ever used

### ISSUE THREAD

**Issue by ZlxveMyAimzZz** [Blank-c/Blank-Grabber#236]
I just wanted to say its cool to use this grabber and the updates are getting better and better you shouldn't stop making these updates

**Comment by ZlxveMyAimzZz** [comment]
And i wanted to ask is it possible to make these stubs FUD?

**Comment by Blank-c** [comment]
Thanks for the compliment, I appreciate your thoughts.

However its not possible to make it completely FUD. This is because its an open source stealer and antiviruses update their signature when people upload this to Virustotal.
