### ISSUE TITLE
I didn't received any data.

### ISSUE THREAD

**Issue by xianalua** [Blank-c/Blank-Grabber#240]
whenever i try the grabber on my self the webhook is not showing on my discord server

**Comment by Blank-c** [comment]
> whenever i try the grabber on my self the webhook is not showing on my discord server

Can you try the `Console:debug` mode with Anti VM turned off.

**Comment by Blank-c** [comment]
Also run this command in cmd `python -c "from urllib.request import urlopen; print(urlopen('https://gstatic.com/generate_204').status)"`

**Comment by xianalua** [comment]
its working now tysm
