### ISSUE TITLE
stealer does not steal ssfn files of steam

### ISSUE THREAD

**Issue by moshiax** [Blank-c/Blank-Grabber#241]
Steals only files from the config folder, which allows you to bypass the password but does not allow you to bypass the steam guard
![image](https://github.com/Blank-c/Blank-Grabber/assets/97439761/71db0525-b6e4-45fe-b422-97e6042713ff)

**Comment by noahmajors** [comment]
I assumed the auth token for bypassing Steam Guard in this case would be located in `loginusers.vdf`. When I tested against myself, making sure to use a VM with steam freshly installed, on my main account with Steam Guard enabled, it transferred to the VM almost seamlessly. 

If this was just a stoke of luck, please provide us with a direct file name(s) and directory as to where we can find the SSFN files. @moshiax

**Comment by Blank-c** [comment]
Now steals ssfn files.

**Comment by moshiax** [comment]
> Now steals ssfn files.

Thanks, but I'm still using the old version because it doesn't close the browser, it's just that if the browser closes, the victim immediately understands everything and downloads the antivirus, which then removes the stealer.
