### ISSUE TITLE
Google Crash

### ISSUE THREAD

**Issue by ossuruk3123** [Blank-c/Blank-Grabber#245]
After running the exe, google chrome closes by itself and I also don't want to put a password on the rar, a preference should be added to it

**Comment by Blank-c** [comment]
Chrome and maybe some other browsers lock the cookie file when they are running. Thats why the stealer kills the process. I'll try to find a workaround without killing the process.

The password in the file is for safety. In case someone got access to the logs, they won't be able to see or misuse them without the password.
