### ISSUE TITLE
suggestion: Browser inject

### ISSUE THREAD

**Issue by sanzaz** [Blank-c/Blank-Grabber#247]
Kinda like hawkish eyes its where u can choose to inject to broser and when a new saved password gets saved or gets entered to a website then ur webhook will recive the new update of all paswords ect u get what i mean

**Comment by Blank-c** [comment]
Someone recommended but I don't know how to make a chrome extension.

**Comment by furax124** [comment]
> Someone recommended but I don't know how to make a chrome extension.
I think you don't need very to make a extension you just do a exe on startup who check password and cookie and send if new are added

**Comment by Blank-c** [comment]
I also think so.
