### ISSUE TITLE
help?

### ISSUE THREAD

**Issue by twistyohnah** [Blank-c/Blank-Grabber#249]
is there anyway to create you own cookie logger as a beginner to python?

**Comment by Blank-c** [comment]
I don't recommend you to make a cookie logger as a beginner to Python. You may try if you have any prior programming knowledge as you will have to deal with AES, databases, environment variables etc.

**Comment by twistyohnah** [comment]
> I don't recommend you to make a cookie logger as a beginner to Python. You may try if you have any prior programming knowledge as you will have to deal with AES, databases, environment variables etc.

thank yoou as them monets im using chat gpt as a result of this issue
