### ISSUE TITLE
How big can Common Files be?

### ISSUE THREAD

**Issue by moshiax** [Blank-c/Blank-Grabber#251]
Just wondering

**Comment by Blank-c** [comment]
2 MB

**Comment by moshiax** [comment]
> 2 MB

and how many can there be?

**Comment by Blank-c** [comment]
Any number. Not fixed.

**Comment by moshiax** [comment]
but what happens if the size exceeds 25 megabytes?

**Comment by Blank-c** [comment]
if the size exceeds 2 MB, it won't be copied.
