### ISSUE TITLE
blank c help please

### ISSUE THREAD

**Issue by EeroTheDEV** [Blank-c/Blank-Grabber#255]
StealMinecraft:   INFO:Stealing Minecraft related files
StealEpic:   INFO:Stealing Epic session
StealSteam:   INFO:Stealing Steam session
StealUplay:   INFO:Stealing Uplay session
GetAntivirus:   INFO:Getting antivirus
GetClipboard:   INFO:Getting clipboard text
GetTaskList:   INFO:Getting task list
GetDirectoryTree:   INFO:Getting directory trees
GetWifiPasswords:   INFO:Getting wifi passwords
StealSystemInfo:   INFO:Stealing system information
TakeScreenshot:   INFO:Taking screenshot
StealDiscordTokens:   INFO:Injecting backdoor into discord
StealRobloxCookies:   INFO:Stealing Roblox cookies
newFunc:  ERROR:Traceback (most recent call last):
  File "<string>", line 148, in newFunc
  File "<string>", line 1461, in StealDiscordTokens
AttributeError: 'NoneType' object has no attribute 'returncode'

__init__:   INFO:All functions ended
GenerateTree:   INFO:Generating tree
CreateArchive:   INFO:Creating archive
SendData:   INFO:Sending data to C2
<module>:CRITICAL:list index out of range
Traceback (most recent call last):
  File "<string>", line 1715, in <module>
  File "<string>", line 948, in __init__
  File "<string>", line 1529, in SendData
IndexError: list index out of range
<module>:   INFO:There was an error, retrying after 10 minutes

this is the error im getting

**Comment by Blank-c** [comment]
Oh I'll look at this

**Comment by EeroTheDEV** [comment]
> Oh I'll look at this. Did you perhaps modify any file?

you reply fast sir

**Comment by EeroTheDEV** [comment]
chat with me on discord if u want 
Eero#2394

**Comment by Blank-c** [comment]
Can you enter this command in CMD

```bat
py -c "import subprocess;print(subprocess.run('wmic csproduct get uuid', capture_output= True, shell= True).stdout.decode(errors= 'ignore').strip().split())"
```

**Comment by EeroTheDEV** [comment]
C:\Users\Nate>py -c "import subprocess;print(subprocess.run('wmic csproduct get uuid', capture_output= True, shell= True).stdout.decode(errors= 'ignore').strip().split())"
[]

C:\Users\Nate>

**Comment by Blank-c** [comment]
can you enter this command in cmd `wmic csproduct get uuid`

**Comment by EeroTheDEV** [comment]
> can you enter this command in cmd `wmic csproduct get uuid`

C:\Users\Nate>wmic csproduct get uuid
No Instance(s) Available.



C:\Users\Nate>

**Comment by EeroTheDEV** [comment]
also i dont have anti virus i only have avast but i turned it off

**Comment by Blank-c** [comment]
Yea I saw the problem was in the code. I forgot to change it when I made an update.

**Comment by EeroTheDEV** [comment]
> Yea I saw the problem was in the code. I forgot to change it when I made an update.

alr thanks man sm <3

**Comment by Blank-c** [comment]
I'll upload the fix in some minutes

**Comment by EeroTheDEV** [comment]
okay thanks

**Comment by Blank-c** [comment]
Please test the new version and tell me if it works or not.

**Comment by EeroTheDEV** [comment]
alr

**Comment by EeroTheDEV** [comment]
> Please test the new version and tell me if it works or not.

works man thank you sm
