### ISSUE TITLE
sorry for another issue its not a issue i need help tho

### ISSUE THREAD

**Issue by EeroTheDEV** [Blank-c/Blank-Grabber#256]
what do i do with the epic session?

**Comment by Blank-c** [comment]
1) Press **Windows key** + **R**
2) Type `%localappdata%`
3) Go to `...\EpicGamesLauncher\Saved\Config\Windows`
4) Paste all the files you got there.

**Comment by Blank-c** [comment]
ust make sure you replace the files once epic games is closed. once you relaunch the client, youll be signed in

**Comment by EeroTheDEV** [comment]
omg thank you sm

**Comment by Blank-c** [comment]
☺

**Comment by EeroTheDEV** [comment]
> 

also what is  melt stub and pump stub

**Comment by Blank-c** [comment]
> > 
> 
> also what is melt stub and pump stub

Check [stub settings](https://github.com/Blank-c/Blank-Grabber#stub-settings)
