### ISSUE TITLE
Wallets Question

### ISSUE THREAD

**Issue by ossuruk3123** [Blank-c/Blank-Grabber#261]
Hello, can you post a tutorial showing how to use the wallets files extracted from rar, usually metamask comes out, I don't know how to use it.

**Comment by ossuruk3123** [comment]
Also I don't know how to use it in steam files

**Comment by Blank-c** [comment]
You just need to paste the files in their corresponding location.

For example, metamask would go to your chrome extentions path (search on google for it), Atomic wallet files go to your installation location of Atomic wallet etc.

**Comment by Blank-c** [comment]
> Also I don't know how to use it in steam files

You just need to paste the steam files inside your steam installation directory (make sure steam is closed). Then start steam and log into your account. Then you will be able to switch account with the grabbed one.

**Comment by ossuruk3123** [comment]
ok thank u <3
