### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by ossuruk3123** [Blank-c/Blank-Grabber#262]
![image](https://github.com/Blank-c/Blank-Grabber/assets/88185938/fbbb5dab-7b73-46de-ad2d-265a967f160d)
As shown here, I write the token and chat id of the bot I created with botfather, but when I test it, I get this error, can you tell me how to do it?

**Comment by Blank-c** [comment]
Can you type this in cmd `curl https://api.telegram.org > nul` and then try again.

**Comment by Blank-c** [comment]
Also I think your token is not correct. A typical bot token is like `[numbers]:[letters]`. Are you sure you copied it from botfather and didn't make any changes to it?

**Comment by ossuruk3123** [comment]
![image](https://github.com/Blank-c/Blank-Grabber/assets/88185938/490813e2-4135-4bfe-a18d-0f90e26b52a8)
I am doing it in accordance with the format here, botfather gives a result like below
![image](https://github.com/Blank-c/Blank-Grabber/assets/88185938/05ebe958-763a-40c2-8db4-08ec1bf4b7b3)

**Comment by ossuruk3123** [comment]
> Can you type this in cmd `curl https://api.telegram.org > nul` and then try again.


it didn't work

**Comment by Blank-c** [comment]
> ![image](https://user-images.githubusercontent.com/88185938/250305915-490813e2-4135-4bfe-a18d-0f90e26b52a8.png) I am doing it in accordance with the format here, botfather gives a result like below ![image](https://user-images.githubusercontent.com/88185938/250305961-05ebe958-763a-40c2-8db4-08ec1bf4b7b3.png)

You have to paste full token there. Including the number at the beginning.

**Comment by ossuruk3123** [comment]
shouldn't I do this?
000000000$g22923GASKDNMJKNJ23JNNJ2NJDSNDSD
When I do it this way and press the test button, I get the error unable to connect. Maybe I'm doing something wrong, can you send a message showing how to do it as an example?

**Comment by Blank-c** [comment]
Example: __5760629467__:AAHbnjC4IuyyG-97w8riT3gjIbvFUqgGe58$__-934369079__

It should be like this, the one you put there is missing the ID at the beginning. Make sure you paste the exact token there as the one botfather sent you.
