### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by qiqto** [Blank-c/Blank-Grabber#264]
Can we have cookies exported as a json

or json format inside a txt
so i can easily import them with cookiebro or somthing

**Comment by Blank-c** [comment]
The cookies are already exported in netscape format which you can import using firefox. There are also tools online which convert cookies to json. You may test them.

**Comment by aryan5555github** [comment]
@Blank-c tat txt to json doesn't work also balnk-c it exports to Netscape really???

**Comment by aryan5555github** [comment]
@qiqto oh and also i suggested tat before u I think

**Comment by Blank-c** [comment]
> @Blank-c tat txt to json doesn't work also balnk-c it exports to Netscape really???

Yea it already exports to netscape. You can import it using firefox.

**Comment by aryan5555github** [comment]
@Blank-c i tried it not exporting to netscape

**Comment by Blank-c** [comment]
> @Blank-c i tried it not exporting to netscape

It already does, Are you not able to import it?
Did you follow the instructions in one of the pinned issues?
