### ISSUE TITLE
HELP ME

### ISSUE THREAD

**Issue by gabuja** [Blank-c/Blank-Grabber#265]
I run the grabber on my pc to test it, and i forgot that it would block the antivirus sites.
Now i cant unlock them.

I have already tried running unblock_sites.py multiples time using different apps but it doesnt change anything.
Please help me on what i should do now to unblock the sites..

And yes whenever i run unblock_sites.py multiple black cmd windows open but close instantly..

**Comment by Blank-c** [comment]
You need to open cmd in the folder by typing `cmd` in the address bar of the Extras folder and then typing `python unblock_sites.py`

**Comment by aryan5555github** [comment]
@gabuja just goto he extra directory and run the unblock_sites.py or maybe open cmd in admin and cd to tat directory and then run py file

**Comment by gabuja** [comment]
> @gabuja just goto he extra directory and run the unblock_sites.py or maybe open cmd in admin and cd to tat directory and then run py file

Thank you so much it worked ur great!
