### ISSUE TITLE
STEAM

### ISSUE THREAD

**Issue by Priest6942000** [Blank-c/Blank-Grabber#266]
How to login with steam ssfn

**Comment by Blank-c** [comment]
Paste the grabbed files as well as the ssfn files into your own steam installation folder (usually in C:/Program Files(x86)/Steam`. 
Then run steam, it will ask you to login. Simply login to your own account Then go to your account and click on 'change account', steam will restart and show you 2 (or more) accounts. One will be yours and the other will be of the victim. You can then select their account. If he hasn't changed the password, you will get inside their account.

**Comment by aryan5555github** [comment]
Wow
