### ISSUE TITLE
my webhook is not working

### ISSUE THREAD

**Issue by ZCOu** [Blank-c/Blank-Grabber#267]
![Скриншот 02 07 23_19 47 29](https://github.com/Blank-c/Blank-Grabber/assets/128056163/6ef01e39-2e37-43d2-aafe-cf3282d1cb97)

**Comment by Blank-c** [comment]
Are you sure the webhook is correct?
Try to open the webhook link in browser, what does it show?
If its still valid, in command prompt type `curl https://discord.com > nul` and then use the builder again.

**Comment by ZCOu** [comment]
Thank you
