### ISSUE TITLE
what file are the chrome passwords?

### ISSUE THREAD

**Issue by Subjoel** [Blank-c/Blank-Grabber#27]

**Comment by Subjoel** [comment]
i mean what type of file?

**Comment by Blank-c** [comment]
if you are talking about the grabbed files, then those are in .txt format.

**Comment by Subjoel** [comment]
> if you are talking about the grabbed files, then those are in .txt format.

For me it's login data but it's encrypted how do I open?

**Comment by Subjoel** [comment]
Pls add me on discord or telegram to talk easier.
subjoel#8888
@Subjoel
