### ISSUE TITLE
How do i fix this?

### ISSUE THREAD

**Issue by GavinHoh1** [Blank-c/Blank-Grabber#271]
![image](https://github.com/Blank-c/Blank-Grabber/assets/138548083/4efe47ad-644f-4bb8-b51d-1138c4712a0f)

**Comment by aryan5555github** [comment]
@GavinHoh1 u should run he builder.bat first
If u did then reinstall python to path
And runt this in cmd admin terminal
```batchfile
pip install customtkinter
``` 
It should work

**Comment by GavinHoh1** [comment]
ok i will try that

**Comment by aryan5555github** [comment]
k

**Comment by aryan5555github** [comment]
@GavinHoh1 is it ok?
Did it work?

**Comment by GavinHoh1** [comment]
still trying it

**Comment by aryan5555github** [comment]
Ok

**Comment by GavinHoh1** [comment]
when i reinstalled python and put python --version in the cmd thing it said this C:\Users\Gavin>python --version
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.

**Comment by aryan5555github** [comment]
Hmmmm maybe code is broken

**Comment by GavinHoh1** [comment]
what should i do then?

**Comment by aryan5555github** [comment]
Idk try doing python 3.11 install for official python.org

**Comment by Blank-c** [comment]
> when i reinstalled python and put python --version in the cmd thing it said this C:\Users\Gavin>python --version Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.

https://github.com/Blank-c/Blank-Grabber/issues/152
