### ISSUE TITLE
What is the zip password?

### ISSUE THREAD

**Issue by omercanssss** [Blank-c/Blank-Grabber#272]
Everything is fine but when i download the zip there is a password,in discord there is nothing about the zip password. What is the zip password?

**Comment by aryan5555github** [comment]
@omercanssss default password is 
Blank

**Comment by aryan5555github** [comment]
The

**Comment by aryan5555github** [comment]
Word Blank

**Comment by aryan5555github** [comment]
Did u change password?
If yes see config.ini
@omercanssss
