### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Trollol01** [Blank-c/Blank-Grabber#273]
Can you add the possibility to add/edit/generate file certificate?

**Comment by aryan5555github** [comment]
?

**Comment by Blank-c** [comment]
It already signs the built file.

**Comment by Trollol01** [comment]
Yes, I know. It would be cool to sign the file as Adobe for example, or as other companies...

**Comment by Blank-c** [comment]
Certificates cost money, so the builder selects a random exe file from the `System32` folder on windows and then copy its certificate to the built stub. 

What are you asking for?

**Comment by noahmajors** [comment]
I believe he is asking to let users point to a signed exe of their choice, rather than a randomly signed file from sys32.

**Comment by Blank-c** [comment]
@Trollol01 you talking 'bout this?
