### ISSUE TITLE
This keeps coming up 

### ISSUE THREAD

**Issue by David12345321** [Blank-c/Blank-Grabber#274]
![Untitled](https://github.com/Blank-c/Blank-Grabber/assets/27980593/a388e21e-d7b2-47c4-8820-3503b0fab824)

**Comment by Blank-c** [comment]
Reinstall python, this happens sometimes. Its a problem with Python.

**Comment by Cr7pt0nic** [comment]
No it's not a problem with python. It says you don't have a module called "customkinter" so instead use "pip3" or "pip" to install customkinter. But considering that package doesn't exist try to remove the import itself.

**Comment by Blank-c** [comment]
> No it's not a problem with python. It says you don't have a module called "customkinter" so instead use "pip3" or "pip" to install customkinter. But considering that package doesn't exist try to remove the import itself.

No thats not the problem. All the people who had this problem in the paste when try to install the package from `pip`, it showed them error "No module named pip!"
