### ISSUE TITLE
Why is Discord Injection not working in telegram logs?

### ISSUE THREAD

**Issue by lerouxyazilim** [Blank-c/Blank-Grabber#275]
Why is Discord Injection not working in telegram logs? I log to Telegram, but I want to do it on Discord Injection.

**Comment by Blank-c** [comment]
The discord inject was not written by me and for now, it only supports discord webhooks, so thats why it is only enabled in `C2:Discord` mode for now

**Comment by lerouxyazilim** [comment]
> The discord inject was not written by me and for now, it only supports discord webhooks, so thats why it is only enabled in `C2:Discord` mode for now

Does it throw the token and information of the Discord account?

**Comment by Blank-c** [comment]
Not sure what you mean, but it sends token information to the webhook.

**Comment by lerouxyazilim** [comment]
> Not sure what you mean, but it sends token information to the webhook.

I mean, does Telegram Bot send Victim's Discord information?

**Comment by Blank-c** [comment]
If you are talking about normal grabber, then yes it does.

If you are talking about discord injection, then no it doesn't.

**Comment by furax124** [comment]
> The discord inject was not written by me and for now, it only supports discord webhooks, so thats why it is only enabled in `C2:Discord` mode for now

Use chat gpt for adapt it lol

**Comment by Blank-c** [comment]
Chatgpt does not generate 100% correct code.

**Comment by furax124** [comment]
> Chatgpt does not generate 100% correct code.

Yeah but he can help lmao
