### ISSUE TITLE
uhhh

### ISSUE THREAD

**Issue by BlitzFan1209** [Blank-c/Blank-Grabber#277]
1028 DEPRECATION: Bytecode encryption will be removed in PyInstaller v6. Please remove your --key=xxx argument to avoid breakages on upgrade. For the rationale/alternatives see https://github.com/pyinstaller/pyinstaller/pull/6999
1028 INFO: PyInstaller: 5.13.0
1029 INFO: Python: 3.10.7
1060 INFO: Platform: Windows-10-10.0.19045-SP0
1090 INFO: wrote C:\Users\User\Downloads\Blank-Grabber-main (1)\Blank-Grabber-main\Blank Grabber\env\Scripts\Built.exe.spec
1226 INFO: UPX is available and will be used if enabled on build targets.
1226 INFO: Removing temporary files and cleaning cache in C:\Users\User\AppData\Local\pyinstaller
1251 DEPRECATION: Bytecode encryption will be removed in PyInstaller v6. Please remove cipher and block_cipher parameters from your spec file to avoid breakages on upgrade. For the rationale/alternatives see https://github.com/pyinstaller/pyinstaller/pull/6999
1252 INFO: Extending PYTHONPATH with paths
['C:\\Users\\User\\Downloads\\Blank-Grabber-main '
 '(1)\\Blank-Grabber-main\\Blank Grabber\\env\\Scripts']
3789 INFO: Will encrypt Python bytecode with provided cipher key
3790 INFO: Appending 'binaries' from .spec
3791 INFO: Appending 'datas' from .spec
3791 INFO: checking Analysis
3791 INFO: Building Analysis because Analysis-00.toc is non existent
3792 INFO: Initializing module dependency graph...
3795 INFO: Caching module graph hooks...
3869 INFO: Analyzing base_library.zip ...
7341 INFO: Loading module hook 'hook-heapq.py' from 'C:\\Users\\User\\Downloads\\Blank-Grabber-main (1)\\Blank-Grabber-main\\Blank Grabber\\env\\lib\\site-packages\\PyInstaller\\hooks'...
7635 INFO: Loading module hook 'hook-encodings.py' from 'C:\\Users\\User\\Downloads\\Blank-Grabber-main (1)\\Blank-Grabber-main\\Blank Grabber\\env\\lib\\site-packages\\PyInstaller\\hooks'...
15327 INFO: Loading module hook 'hook-pickle.py' from 'C:\\Users\\User\\Downloads\\Blank-Grabber-main (1)\\Blank-Grabber-main\\Blank Grabber\\env\\lib\\site-packages\\PyInstaller\\hooks'...
26496 INFO: Caching module dependency graph...
27019 INFO: running Analysis Analysis-00.toc
27045 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by C:\Users\User\AppData\Local\Programs\Python\Python310\python.exe
27225 INFO: Analyzing C:\Users\User\Downloads\Blank-Grabber-main (1)\Blank-Grabber-main\Blank Grabber\env\Scripts\stub-o.py
27329 INFO: Analyzing hidden import 'urllib3'
28166 INFO: Analyzing hidden import 'sqlite3'
28202 INFO: Loading module hook 'hook-sqlite3.py' from 'C:\\Users\\User\\Downloads\\Blank-Grabber-main (1)\\Blank-Grabber-main\\Blank Grabber\\env\\lib\\site-packages\\PyInstaller\\hooks'...
29966 INFO: Analyzing hidden import 'pyaes'
30093 INFO: Analyzing hidden import 'ctypes'
30224 INFO: Analyzing hidden import 'ctypes.wintypes'
30248 INFO: Analyzing hidden import 'tinyaes'
30250 INFO: Processing module hooks...
30315 INFO: Looking for ctypes DLLs
30324 INFO: Analyzing run-time hooks ...
30328 INFO: Including run-time hook 'C:\\Users\\User\\Downloads\\Blank-Grabber-main (1)\\Blank-Grabber-main\\Blank Grabber\\env\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_inspect.py'
30339 INFO: Looking for dynamic libraries
901 INFO: Extra DLL search directories (AddDllDirectory): []
901 INFO: Extra DLL search directories (PATH): ['C:\\Users\\User\\Downloads\\Blank-Grabber-main (1)\\Blank-Grabber-main\\Blank Grabber\\env\\Scripts', 'C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common', 'C:\\ProgramData\\Oracle\\Java\\javapath', 'C:\\Windows\\system32', 'C:\\Windows', 'C:\\Windows\\System32\\Wbem', 'C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\', 'C:\\Windows\\System32\\OpenSSH\\', 'C:\\Program Files (x86)\\AMD\\ATI.ACE\\Core-Static', 'C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python310\\Scripts\\', 'C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python310\\', 'C:\\Users\\User\\AppData\\Local\\Microsoft\\WindowsApps']
32287 INFO: Looking for eggs
32288 INFO: Using Python library C:\Users\User\AppData\Local\Programs\Python\Python310\python310.dll
32289 INFO: Found binding redirects:
[]
32294 INFO: Warnings written to C:\Users\User\Downloads\Blank-Grabber-main (1)\Blank-Grabber-main\Blank Grabber\env\Scripts\build\Built.exe\warn-Built.exe.txt
32361 INFO: Graph cross-reference written to C:\Users\User\Downloads\Blank-Grabber-main (1)\Blank-Grabber-main\Blank Grabber\env\Scripts\build\Built.exe\xref-Built.exe.html
32424 INFO: checking PYZ
32425 INFO: Building PYZ because PYZ-00.toc is non existent
32426 INFO: Building PYZ (ZlibArchive) C:\Users\User\Downloads\Blank-Grabber-main (1)\Blank-Grabber-main\Blank Grabber\env\Scripts\build\Built.exe\PYZ-00.pyz
33152 INFO: Building PYZ (ZlibArchive) C:\Users\User\Downloads\Blank-Grabber-main (1)\Blank-Grabber-main\Blank Grabber\env\Scripts\build\Built.exe\PYZ-00.pyz completed successfully.
33185 INFO: checking PKG
33185 INFO: Building PKG because PKG-00.toc is non existent
33187 INFO: Building PKG (CArchive) Built.pkg
33193 INFO: Disabling UPX for C:\Users\User\Downloads\Blank-Grabber-main (1)\Blank-Grabber-main\Blank Grabber\env\Scripts\rar.exe due to CFG!
33214 INFO: Disabling UPX for C:\Users\User\AppData\Local\Programs\Python\Python310\VCRUNTIME140.dll due to CFG!
33480 INFO: Executing: upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\User\AppData\Local\pyinstaller\bincache01_py310_64bit\python310.dll
58822 INFO: Executing: upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\User\AppData\Local\pyinstaller\bincache01_py310_64bit\_decimal.pyd
75928 INFO: Executing: upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\User\AppData\Local\pyinstaller\bincache01_py310_64bit\_hashlib.pyd
76117 INFO: Executing: upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\User\AppData\Local\pyinstaller\bincache01_py310_64bit\select.pyd
103637 INFO: Executing: upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\User\AppData\Local\pyinstaller\bincache01_py310_64bit\_socket.pyd
120686 INFO: Executing: upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\User\AppData\Local\pyinstaller\bincache01_py310_64bit\_lzma.pyd
121098 INFO: Executing: upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\User\AppData\Local\pyinstaller\bincache01_py310_64bit\_bz2.pyd
146390 INFO: Executing: upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\User\AppData\Local\pyinstaller\bincache01_py310_64bit\tinyaes.cp310-win_amd64.pyd
146554 INFO: Executing: upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\User\AppData\Local\pyinstaller\bincache01_py310_64bit\_ctypes.pyd
174104 INFO: Executing: upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\User\AppData\Local\pyinstaller\bincache01_py310_64bit\_sqlite3.pyd
191085 INFO: Executing: upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\User\AppData\Local\pyinstaller\bincache01_py310_64bit\_ssl.pyd
216130 INFO: Executing: upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\User\AppData\Local\pyinstaller\bincache01_py310_64bit\_queue.pyd
249808 INFO: Executing: upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\User\AppData\Local\pyinstaller\bincache01_py310_64bit\unicodedata.pyd
275464 INFO: Executing: upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\User\AppData\Local\pyinstaller\bincache01_py310_64bit\libcrypto-1_1.dll
303207 INFO: Executing: upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\User\AppData\Local\pyinstaller\bincache01_py310_64bit\libffi-7.dll
303557 INFO: Executing: upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\User\AppData\Local\pyinstaller\bincache01_py310_64bit\sqlite3.dll
331638 INFO: Executing: upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\User\AppData\Local\pyinstaller\bincache01_py310_64bit\libssl-1_1.dll
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\User\Downloads\Blank-Grabber-main (1)\Blank-Grabber-main\Blank Grabber\env\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "C:\Users\User\Downloads\Blank-Grabber-main (1)\Blank-Grabber-main\Blank Grabber\env\lib\site-packages\PyInstaller\__main__.py", line 194, in _console_script_run
    run()
  File "C:\Users\User\Downloads\Blank-Grabber-main (1)\Blank-Grabber-main\Blank Grabber\env\lib\site-packages\PyInstaller\__main__.py", line 180, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\Users\User\Downloads\Blank-Grabber-main (1)\Blank-Grabber-main\Blank Grabber\env\lib\site-packages\PyInstaller\__main__.py", line 61, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\Users\User\Downloads\Blank-Grabber-main (1)\Blank-Grabber-main\Blank Grabber\env\lib\site-packages\PyInstaller\building\build_main.py", line 1019, in main
    build(specfile, distpath, workpath, clean_build)
  File "C:\Users\User\Downloads\Blank-Grabber-main (1)\Blank-Grabber-main\Blank Grabber\env\lib\site-packages\PyInstaller\building\build_main.py", line 944, in build
    exec(code, spec_namespace)
  File "C:\Users\User\Downloads\Blank-Grabber-main (1)\Blank-Grabber-main\Blank Grabber\env\Scripts\Built.exe.spec", line 24, in <module>
    exe = EXE(
  File "C:\Users\User\Downloads\Blank-Grabber-main (1)\Blank-Grabber-main\Blank Grabber\env\lib\site-packages\PyInstaller\building\api.py", line 572, in __init__
    self.pkg = PKG(
  File "C:\Users\User\Downloads\Blank-Grabber-main (1)\Blank-Grabber-main\Blank Grabber\env\lib\site-packages\PyInstaller\building\api.py", line 240, in __init__
    self.__postinit__()
  File "C:\Users\User\Downloads\Blank-Grabber-main (1)\Blank-Grabber-main\Blank Grabber\env\lib\site-packages\PyInstaller\building\datastruct.py", line 184, in __postinit__
    self.assemble()
  File "C:\Users\User\Downloads\Blank-Grabber-main (1)\Blank-Grabber-main\Blank Grabber\env\lib\site-packages\PyInstaller\building\api.py", line 328, in assemble
    CArchiveWriter(self.name, bootstrap_toc + archive_toc, pylib_name=pylib_name)
  File "C:\Users\User\Downloads\Blank-Grabber-main (1)\Blank-Grabber-main\Blank Grabber\env\lib\site-packages\PyInstaller\archive\writers.py", line 155, in __init__
    toc_entry = self._write_entry(fp, entry)
  File "C:\Users\User\Downloads\Blank-Grabber-main (1)\Blank-Grabber-main\Blank Grabber\env\lib\site-packages\PyInstaller\archive\writers.py", line 233, in _write_entry
    return self._write_file(fp, src_name, dest_name, typecode, compress=compress)
  File "C:\Users\User\Downloads\Blank-Grabber-main (1)\Blank-Grabber-main\Blank Grabber\env\lib\site-packages\PyInstaller\archive\writers.py", line 253, in _write_file
    data_length = os.stat(src_name).st_size
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\User\\AppData\\Local\\pyinstaller\\bincache01_py310_64bit\\python310.dll'

**Comment by BlitzFan1209** [comment]
nvm it was my antivirus

**Comment by aryan5555github** [comment]
uhhhhhhhhhhhhhhhh
