### ISSUE TITLE
Tokens not showing + how do I get it to generate over people’s information? I’m fairly new to this please help.  ^^

### ISSUE THREAD

**Issue by muttnut** [Blank-c/Blank-Grabber#279]

**Comment by aryan5555github** [comment]
????

**Comment by aryan5555github** [comment]
I'm not new I'll help u @muttnut

**Comment by aryan5555github** [comment]
U click da buttons

**Comment by Blank-c** [comment]
You need to build it and sent to your victim. When they runs the generated file, you will get their info.

**Comment by muttnut** [comment]
Thank you everyone for your help! Ima tad bit embarrassed from the dumb question but Ty for being so nice and taking your time to answer

**Comment by aryan5555github** [comment]
@muttnut its fine
