### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by CrackerCheats** [Blank-c/Blank-Grabber#281]
Suggestion: steal cc(credit card) added by victim.

**Comment by Blank-c** [comment]
> Suggestion: steal cc(credit card) added by victim.

This was a feature lon ago. But since Browsers don't store CVV, it is basically useless.

**Comment by CrackerCheats** [comment]
If it is possible to steal the victim's password with the injection of Discord it is possible to steal new payment method that victim added like cc(credit card)?
srry for bad english

**Comment by Blank-c** [comment]
> If it is possible to steal the victim's password with the injection of Discord it is possible to steal new payment method that victim added like cc(credit card)? srry for bad english

The injections wasn't coded by me. And it does steal the new password that victim changed to and also if he added a payment method (probably)

**Comment by aryan5555github** [comment]
btw cc is practically useless
