### ISSUE TITLE
Good Suggestions!

### ISSUE THREAD

**Issue by sanzaz** [Blank-c/Blank-Grabber#282]
Some spooky Encantments
1. Jumpscare victim (opens up a url with max volum of a scary video)
2. swap mouse button
3. dissable inputs
4. idk if this is even possible but if u could choose a mp3 file in the builder that  would play when victim runs

**Comment by Blank-c** [comment]
Well, thats not something a stealthy trojan should do.

**Comment by aryan5555github** [comment]
@sanzaz or it will play a video on startup by the mbr lol he will like it

**Comment by Blank-c** [comment]
> Well, thats not something a stealthy trojan should do.

.

**Comment by sanzaz** [comment]
> Well, thats not something a stealthy trojan should do.
oh i  didnt  mean a live functio nthat u control i mean like its an option in the builder u not something u control after victim has ran it

**Comment by Blank-c** [comment]
I mean a stealer should be stealthy, it should not do anything to grab victim's attention.

**Comment by aryan5555github** [comment]
yed

**Comment by Blank-c** [comment]
Thats why.

**Comment by sanzaz** [comment]
oh well i suppose ur right
