### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Trollol01** [Blank-c/Blank-Grabber#286]
How can I grab youtube or gmail session token?

**Comment by Blank-c** [comment]
The cookies allow you to login to gmail, youtube etc.

**Comment by Trollol01** [comment]
Yes, I know. But how I can use from the file "Chrome Cookies.txt" the values to log in?

**Comment by Bloopy365** [comment]
> Yes, I know. But how I can use from the file "Chrome Cookies.txt" the values to log in?

cookie manager

**Comment by Blank-c** [comment]
> Yes, I know. But how I can use from the file "Chrome Cookies.txt" the values to log in?

Check out #133

**Comment by Trollol01** [comment]
Thanks  💪
