### ISSUE TITLE
BRO NO ONE IS HELPING ME

### ISSUE THREAD

**Issue by EeroTheDEV** [Blank-c/Blank-Grabber#287]
BRO NO ONE IS HELPING ME IN THE TELEGRAM

**Comment by Blank-c** [comment]
You can always DM me too. So what help do you need?

**Comment by aryan5555github** [comment]
I'll help
I'm veri helpful @EeroTheDEV

**Comment by EeroTheDEV** [comment]
help me sign into someones stuff with the epic and steam info files

**Comment by Blank-c** [comment]
**Steam:** Paste the grabbed files as well as the ssfn files into your own steam installation folder (usually in `C:/Program Files(x86)/Steam`. 
Then run steam, it will ask you to login. Simply login to your own account Then go to your account and click on 'change account', steam will restart and show you 2 (or more) accounts. One will be yours and the other will be of the victim. You can then select their account. If he hasn't changed the password, you will get inside their account.

**Epic:** 1) Press **Windows key** + **R**
2) Type `%localappdata%`
3) Go to `...\EpicGamesLauncher\Saved\Config\Windows`
4) Paste all the files you got there.

**Comment by EeroTheDEV** [comment]
okay thanks
