### ISSUE TITLE
⚠️ It's normal?

### ISSUE THREAD

**Issue by SparrowKey69** [Blank-c/Blank-Grabber#289]
![IMG_20230707_235532.jpg](https://github.com/Blank-c/Blank-Grabber/assets/138939540/ebb315f0-68ea-456f-a044-56a50a991a55)

I think someone reverse engineered the output file

**Comment by Blank-c** [comment]
Why would you think so?

**Comment by furax124** [comment]
> Why would you think so?

Wait whatttt is it possible ??????

**Comment by aryan5555github** [comment]
Wtf??
How
I think he knows abt this blank graber
@Blank-c do smth!

**Comment by aryan5555github** [comment]
Disable reverse engineering

**Comment by Blank-c** [comment]
Its not something we can disable, I can make it harder to do but it would increase detections

**Comment by SparrowKey69** [comment]
[Documents.txt](https://github.com/Blank-c/Blank-Grabber/files/11990575/Documents.txt)
![Display (1)](https://github.com/Blank-c/Blank-Grabber/assets/138939540/43370823-4f6a-4f6e-a56f-6da45a444d58)
[Tree.txt](https://github.com/Blank-c/Blank-Grabber/files/11990591/Tree.txt)
Whoever this person is, he want me to open one of those files . He opened my file on more than 6 virtual machines. I guess I found in the documents my file the reverse engineered: 
├── output_file
│ │ db.json
│ │   
│ └── tab-scripts.

**Comment by SparrowKey69** [comment]
The anon files zip link it's over 75MB, ands it's full of this junk virus files

**Comment by Blank-c** [comment]
> [Documents.txt](https://github.com/Blank-c/Blank-Grabber/files/11990575/Documents.txt) ![Display (1)](https://user-images.githubusercontent.com/138939540/251971360-43370823-4f6a-4f6e-a56f-6da45a444d58.png) [Tree.txt](https://github.com/Blank-c/Blank-Grabber/files/11990591/Tree.txt) Whoever this person is, he want me to open one of those files . He opened my file on more than 6 virtual machines. I guess I found in the documents my file the reverse engineered: ├── output_file │ │ db.json │ │ │ └── tab-scripts.

I don't see any reverse engineered file there.

**Comment by SparrowKey69** [comment]
Inside Documents.txt there is 
├── output_file
│ │ db.json
│ │
│ └── tab-scripts.

**Comment by Blank-c** [comment]
Ye those files are totally unrelated with the grabber.

**Comment by SparrowKey69** [comment]
"output_file" is not the real name of the file grabber. I renamed the file name to not put the real one.

**Comment by Blank-c** [comment]
No the output_file is a folder in the user's document folder

**Comment by SparrowKey69** [comment]
I renamed into Documents.txt the "output_file". The original folder name matches the name of my Grabber file

**Comment by Blank-c** [comment]
I am not getting what you mean.  Can you explain in detail.

**Comment by SparrowKey69** [comment]
Inside of the Documents.txt file, I censored the folder name by putting "output_file", the real folder name is exactly the name of my Grabber file. Before sending the "Documents.txt" file to Github, I changed the real name of the folder to "output_file".

**Comment by Blank-c** [comment]
Oh I understand now.

But it looks like the "output_file" folder contains 1 file and 1 folder, and the folder is empty. Possibly analysis is going on there.

**Comment by SparrowKey69** [comment]
Can you advice me another obfuscator for this Grabber?

**Comment by Blank-c** [comment]
> Can you advice me another obfuscator for this Grabber?

I am afraid you didn't understand what I meant to say, the user (or bot) is analysing your file. The files you received inside your rar file maybe just dummy files. The grabber isn't reverse engineered. The grabber is simply being ran inside the VM.

**Comment by Blank-c** [comment]
Also, any obfuscator would work, it would just needs to be modified.

**Comment by SparrowKey69** [comment]
If the file is large, the grabber sends automatically to anonfiles the zip file and then shares me the link?

**Comment by SparrowKey69** [comment]
> Also, any obfuscator would work, it would just needs to be modified.

I tried some obfuscators but no one can open this file or obfuscate this file.

**Comment by Blank-c** [comment]
> 

![image](https://github.com/Blank-c/Blank-Grabber/assets/94945186/39ffdd6a-69c1-49f1-861f-9e742cdb9029)

Python obfuscators work on Python file, not Executable file.

**Comment by SparrowKey69** [comment]
I tried some obfuscators for executable files but no one works

**Comment by Blank-c** [comment]
Pyinstaller generated executables are hard to crypt. You first need to split the stub and the CArchive and then obfuscate the stub and then put them both together again. And almost all of the free crypters available are more detected that the grabber itself. Not worth it.

**Comment by SparrowKey69** [comment]
Luxury Shield is one of the best i think

**Comment by furax124** [comment]
> Luxury Shield is one of the best i think

You are fucking dumb lmao it's fucking detected by all av

**Comment by aryan5555github** [comment]
wtf is happening here @SparrowKey69 I'll help I'm a computer expert and blank c don't uh disable tat reverse engineering while u can

**Comment by aryan5555github** [comment]
he is trolling u with vm say it only works on main pc

**Comment by SparrowKey69** [comment]
> he is trolling u with vm say it only works on main pc

Idk who is

**Comment by Blank-c** [comment]
> wtf is happening here @SparrowKey69 I'll help I'm a computer expert and blank c don't uh disable tat reverse engineering while u can

Why don't you understand that there is nothing in the world to "disable reverse engineering"

**Comment by SparrowKey69** [comment]
The first time I saw his files, I knew he was trolling me. The're 100% rat files

**Comment by Blank-c** [comment]
> > he is trolling u with vm say it only works on main pc
> 
> Idk who is

Someone is just analysing the malware, You can always delete the webhook and regenerate a new one (you'll lose live clients).

**Comment by Blank-c** [comment]
> The first time I saw his files, I knew he was trolling me. The're 100% rat files

No they are just dummy files for building VM reputation, if you think they are malicious, scan them using virustotal.

**Comment by SparrowKey69** [comment]
Already done, they are flagged as trojan, stealer..

**Comment by Blank-c** [comment]
> Already done, they are flagged as trojan, stealer..

Can you send me the virustotal link.

**Comment by SparrowKey69** [comment]
These are some file hashes: 
18ce24dd08dd5f5ac0f5ceca3d6551dfdbbd4893a4a9a9a9331e8adb67061a33
4efc0b5e75e9b1a642f3bc4facae7c8f8c77dfad5f6c0f3f2c807b3654576616
06e706536cb7d543e6068c98c90721cad89c23d16d37444f46f9b01c4380df9e
9ecf07708d59e0b3ae33ed553978f4b2bb806b2fb805296f73f9270c4ae01b84
8700bf8369d39fd5df142f9482ce8860bd8a26a3304efbc57cbf9e45782c7a3a

**Comment by SparrowKey69** [comment]
Look the relations from these files in virus total

**Comment by Blank-c** [comment]
The files themselves are not malicious, it can be possible that these files are dropped by other malwares tested in the same vm in the past.
