### ISSUE TITLE
SUGGESTION- commands

### ISSUE THREAD

**Issue by Crryz** [Blank-c/Blank-Grabber#290]
itd be nice to have commands like take a screenshot, take a webcam photo, upload files, delete files, download files, get current discord token, etc. it would make it nice and easy to constantly keep access to whoever's pc. just a suggestion though!

**Comment by sanzaz** [comment]
thats a rat not a grabber

**Comment by Blank-c** [comment]
> whoever's

You should use a rat if you want to do that.
