### ISSUE TITLE
When i click on the .rar file it says this

### ISSUE THREAD

**Issue by GavinHoh1** [Blank-c/Blank-Grabber#292]
![image](https://github.com/Blank-c/Blank-Grabber/assets/138548083/349ee145-e262-4e10-ab24-5575b4ceecdf)

**Comment by Blank-c** [comment]
Bro you need winrar/winzip/7z any archive related software. You cannot open it in notepad.

**Comment by GavinHoh1** [comment]
oh ok

**Comment by GavinHoh1** [comment]
how do i use the roblox cookies to get into a roblox account tho

**Comment by Blank-c** [comment]
You just need to use any cookie editor extention. Go to roblox.com, and login with your own account. Now click on the cookie editor extention icon and you will see many entries. Find the one which says ".ROBLOSECURITY" and click edit value and paste the cookie you have. Now save it and refresh.

**Comment by GavinHoh1** [comment]
ok thanks
