### ISSUE TITLE
not sending to webhook when clicked

### ISSUE THREAD

**Issue by gtavmodder** [Blank-c/Blank-Grabber#297]

**Comment by VOREGA** [comment]
+same

**Comment by Blank-c** [comment]
> +same

Can you test the `Console:Debug` mode to see if there are any errors.

**Comment by VOREGA** [comment]
**Hi, when I run the program as administrator, the problem is solved.+up**

**Comment by Blank-c** [comment]
@gtavmodder wbu?

**Comment by Blank-c** [comment]
you there bud?

**Comment by vahrervert** [comment]
> you there bud?

**unrelated** is this fud?

**Comment by Blank-c** [comment]
> > you there bud?
> 
> **unrelated** is this fud?

no its not.

**Comment by Blank-c** [comment]
@gtavmodder Should I assume your problem is fixed?
