### ISSUE TITLE
Grabber does not run in VMs/sandbox

### ISSUE THREAD

**Issue by minhhaihup95** [Blank-c/Blank-Grabber#30]
i haved already follow all instrucsions. I bring exe file run into sand box which have logged Facebook acc. But nothing happened. the progam did nothing. No data has sent to my discord webhook

**Comment by Blank-c** [comment]
![image](https://user-images.githubusercontent.com/94945186/170714859-33cf935f-7291-41d4-87da-86244a54f0e6.png)
[Blank Grabber/Data/main.py](https://github.com/Blank-c/Blank-Grabber/blob/main/Blank%20Grabber/Data/main.py#L5)

_Originally posted by @Blank-c in https://github.com/Blank-c/Blank-Grabber/issues/26#issuecomment-1139651237_

**Comment by Blank-c** [comment]
Change it to
```python
VMPROTECT = False
```

**Comment by Blank-c** [comment]
> 

Turn vmprotect off

**Comment by Gaminguide1000** [comment]
I did turn it off bro, i aint dumb

**Comment by Blank-c** [comment]
What VM did you run it in???

**Comment by Gaminguide1000** [comment]
VMware 16

**Comment by Gaminguide1000** [comment]
U gonnas answer?

**Comment by Blank-c** [comment]
I don't know what the problem is with the vm. It is possible that the grabber crashes in the vm. Have you tried with the latest version? Also try to remove the *--noconsole* flag from convert.bat and check if there is any error.
