### ISSUE TITLE
Multi-os support

### ISSUE THREAD

**Issue by aryan5555github** [Blank-c/Blank-Grabber#301]
can u add multi os support to ur grabber

**Comment by Blank-c** [comment]
No sorry but I'd like to keep it simple.

**Comment by aryan5555github** [comment]
It's still a good idea bcz not all people use windows

**Comment by Blank-c** [comment]
Also, the fact that I have little to zero experience with other OS.

**Comment by aryan5555github** [comment]
... wat abt

**Comment by aryan5555github** [comment]
Oops close accidentally wat abt Android

**Comment by Blank-c** [comment]
Nope only Windows.

**Comment by LemionLaLemon** [comment]
> Oops close accidentally wat abt Android

ANDROID? who in the world would have the right mind to spend time downloading some already sketchy .apk and install it
i think if there were to be multi-OS support it'd be limited to windows and mac. Phones are weird.
