### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by ExecutivePrograms** [Blank-c/Blank-Grabber#308]
How do i fix this:

Fatal error in launcher: Unable to create process using '"C:\Users\execu\Desktop\Blank-Grabber-main\Blank Grabber\env\Scripts\python.exe"  "C:\Users\execu\Desktop\Grabbers\Blank-Grabber-main\Blank Grabber\env\Scripts\pyinstaller.exe" --noconsole --onefile --clean --noconfirm loader-o.py --key 8974121685118226 --name "Built.exe" -i NONE --hidden-import urllib3 --hidden-import sqlite3 --hidden-import pyaes --hidden-import ctypes --hidden-import ctypes.wintypes --hidden-import json --add-binary rar.exe;. --add-data rarreg.key;. --add-data blank.aes;. --version-file version.txt ': 
The specified file could not be found.

**Comment by aryan5555github** [comment]
Disable av and reinstall the grabber files  @ExecutivePrograms

**Comment by Blank-c** [comment]
Can you try to rebuild. (Delete the env folder in the builder's directory)

**Comment by ExecutivePrograms** [comment]
it worked thanks

**Comment by Blank-c** [comment]
I am glad that your problem is solved.
