### ISSUE TITLE
error customkinter

### ISSUE THREAD

**Issue by oskippah** [Blank-c/Blank-Grabber#312]
i have an error that says "Traceback (most recent call last):
  File "E:\blank grabber\Blank-Grabber-main\Blank Grabber\gui.py", line 12, in <module>
    import customtkinter as ctk
ModuleNotFoundError: No module named 'customtkinter'"

**Comment by oskippah** [comment]
fixed it. just had to reinstall python

**Comment by aryan5555github** [comment]
... @oskippah just pip install customtkinter
