### ISSUE TITLE
Detection

### ISSUE THREAD

**Issue by ExecutivePrograms** [Blank-c/Blank-Grabber#313]
**Dear Blank Grabber Developers,**

I saw that the detections of the grabber are bit high.
It bypassed good amount but it doesn't bypass Microsoft and Google.
So please make it bypass Microsoft and Google.

Best regards,
Executive

**Comment by Blank-c** [comment]
I have tried that many times and sometimes it worked out too. But as soon as I release it on github, some hours later, the antiviruses start detecting it again.

**Comment by aryan5555github** [comment]
> **Dear Blank Grabber Developers,**
> 
> I saw that the detections of the grabber are bit high. It bypassed good amount but it doesn't bypass Microsoft and Google. So please make it bypass Microsoft and Google.
> 
> Best regards, Executive

Noble messaging ✔️

**Comment by aryan5555github** [comment]
> I have tried that many times and sometimes it worked out too. But as soon as I release it on github, some hours later, the antiviruses start detecting it again.

Also it gets detected bcz many users put it into scan on tat virustotal

**Comment by aryan5555github** [comment]
> **Dear Blank Grabber Developers,**
> 
> I saw that the detections of the grabber are bit high. It bypassed good amount but it doesn't bypass Microsoft and Google. So please make it bypass Microsoft and Google.
> 
> Best regards, Executive

Also this is GitHub so uh they just....... Detect it soon
