### ISSUE TITLE
vpn

### ISSUE THREAD

**Issue by Bloopy365** [Blank-c/Blank-Grabber#318]
what is vpn for

**Comment by Blank-c** [comment]
what vpn?

**Comment by Bloopy365** [comment]
![image](https://github.com/Blank-c/Blank-Grabber/assets/135502033/d6d5681a-72f3-4753-9573-93b84377b4b5)


> what vpn?

**Comment by Blank-c** [comment]
> ![image](https://user-images.githubusercontent.com/135502033/254331545-d6d5681a-72f3-4753-9573-93b84377b4b5.png)
> 
> > what vpn?

Ah it just means if the user is connected to a vpn or not.

**Comment by Bloopy365** [comment]
> > ![image](https://user-images.githubusercontent.com/135502033/254331545-d6d5681a-72f3-4753-9573-93b84377b4b5.png)
> > > what vpn?
> 
> Ah it just means if the user is connected to a vpn or not.

ok
