### ISSUE TITLE
.bat

### ISSUE THREAD

**Issue by Bloopy365** [Blank-c/Blank-Grabber#320]
Can .bat file Get My Info?

**Comment by Blank-c** [comment]
There are certain tools online that can hide malware behind batch files. And since they are mostly undetectable, they can execute malware without you noticing.

So yeah, make sure to check any file you download with VirusTotal unless you trust it.

**Comment by aryan5555github** [comment]
Uh the builder.bat won't bram you

**Comment by Bloopy365** [comment]
> There are certain tools online that can hide malware behind batch files. And since they are mostly undetectable, they can execute malware without you noticing.
> 
> So yeah, make sure to check any file you download with VirusTotal unless you trust it.

ok thanks
