### ISSUE TITLE
how do i see ur source code

### ISSUE THREAD

**Issue by Dariusispro** [Blank-c/Blank-Grabber#325]
how to see ur source code

**Comment by Blank-c** [comment]
In the code tab of github, click on Blank Grabber folder, and there are the code files/folders.

**Comment by Dariusispro** [comment]
> In the code tab of github, click on Blank Grabber folder, and there are the code files/folders.

give me screenshot

**Comment by Dariusispro** [comment]
> In the code tab of github, click on Blank Grabber folder, and there are the code files/folders.

how i make my own grabber like blank grabber

**Comment by Blank-c** [comment]
> > In the code tab of github, click on Blank Grabber folder, and there are the code files/folders.
> 
> how i make my own grabber like blank grabber

Understand the concepts, get yourself a good language, you can make one too.

**Comment by Dariusispro** [comment]
> > > In the code tab of github, click on Blank Grabber folder, and there are the code files/folders.
> > 
> > 
> > how i make my own grabber like blank grabber
> 
> Understand the concepts, get yourself a good language, you can make one too.

python? batch?

**Comment by Dariusispro** [comment]
> > > In the code tab of github, click on Blank Grabber folder, and there are the code files/folders.
> > 
> > 
> > how i make my own grabber like blank grabber
> 
> Understand the concepts, get yourself a good language, you can make one too.

i use python but i dont know how to code

**Comment by aryan5555github** [comment]
Then learn it or use an ai like chat.openai.com or zzzcode.ai

**Comment by Dariusispro** [comment]
@Blank-c 
![image](https://github.com/Blank-c/Blank-Grabber/assets/135502033/c81f7b41-1266-4bf3-b6d7-4cde5cab2f56)
how to change

**Comment by Blank-c** [comment]
I wouldn't help with that. Its not a good practice to steal other people's code and frame it as yours.

You are literally asking me, "Bro I stole your debit card, whats your account password?"

**Comment by Dariusispro** [comment]
> I wouldn't help with that. Its not a good practice to steal other people's code and frame it as yours.
> 
> You are literally asking me, "I stole your debit card, whats your account password?"

no

**Comment by Dariusispro** [comment]
> I wouldn't help with that. Its not a good practice to steal other people's code and frame it as yours.
> 
> You are literally asking me, "I stole your debit card, whats your account password?"

im just trying to ask how to change name and icon

**Comment by Blank-c** [comment]
Why would you want to do that? If I may ask?

**Comment by Dariusispro** [comment]
> Why would you want to do that? If I may ask?

i just want to change the icon and name

**Comment by Blank-c** [comment]
Ye I am asking why you want to do that? Whats wrong with the default one? Also in the picture you already seems to have done that.

**Comment by Blank-c** [comment]
Don't steal code, change name and frame it as yours. Get some life and learn to code. It get you anywhere.
