### ISSUE TITLE
when i try to open the chrome rar file to  it get infinity downloads on google, help

### ISSUE THREAD

**Issue by 01234567876543210** [Blank-c/Blank-Grabber#326]

**Comment by aryan5555github** [comment]
@01234567876543210 wat?????

**Comment by Blank-c** [comment]
Can you elaborate your question?

**Comment by aryan5555github** [comment]
@Blank-c @01234567876543210 means he got infinity downloads on google

**Comment by aryan5555github** [comment]
Aww man ur pc will break @01234567876543210

**Comment by Blank-c** [comment]
I am still not sure. @01234567876543210 please send a picture or explain what you mean.

**Comment by Blank-c** [comment]
Need more info. If the problem still persists, please make a new issue explaining the problem in detail.
