### ISSUE TITLE
python not installed tho installed

### ISSUE THREAD

**Issue by ShockerLL22** [Blank-c/Blank-Grabber#327]

**Comment by Blank-c** [comment]
Did you add it to path? When installing Python, there is a tickbox "Add Python to PATH", did you tick it? Verify by typing `python --version` in cmd. If it says, Python was not found, then you forgot to do it.

**Comment by Blank-c** [comment]
@ShockerLL22 Is it fixed?

**Comment by idcaboutmyuserxdxd** [comment]
@Blank-c  i have the same issue i installed python 3.11.4 and made sure i enabled PATH but it still doesnt work

**Comment by Blank-c** [comment]
> @Blank-c i have the same issue i installed python 3.11.4 and made sure i enabled PATH but it still doesnt work

Can you try to reinstall it and then in cmd write the command `python --version`

**Comment by Blank-c** [comment]
Please open a new issue if you are still having problems.
