### ISSUE TITLE
so idk what to do i'm new to this and someone please help me

### ISSUE THREAD

**Issue by stormismanke** [Blank-c/Blank-Grabber#328]
![Screenshot 2023-07-23 165917](https://github.com/Blank-c/Blank-Grabber/assets/140327642/b57f21c0-f876-410c-bce9-b9c2a38e55dd)

**Comment by stormismanke** [comment]
this

**Comment by ghubrakesh** [comment]
You don't have the python library "customtkinter" installed in your system. Just install the package using package using `pip install customtkinter` and run the code again.

**Comment by Blank-c** [comment]
This is a problem with Python, please uninstall it from control panel and reinstall (make sure to enable "Add to PATH option").

**Comment by Blank-c** [comment]
@ghubrakesh There is a problem going on with Python where PIP is not properly installed upon Python installation, this usually gets fixed when reinstalling Python.

FYI, the builder.bat already attempts to install required libraries.

**Comment by ghubrakesh** [comment]
> @ghubrakesh There is a problem going on with Python where PIP is not properly installed upon Python installation, this usually gets fixed when reinstalling Python.
> 
> FYI, the builder.bat already attempts to install required libraries.

Oh, I am sorry. I thought the `customtkinter` is not installed beforehand.

**Comment by stormismanke** [comment]
> You don't have the python library "customtkinter" installed in your system. Just install the package using package using `pip install customtkinter` and run the code again.

where do i get customkinter

**Comment by stormismanke** [comment]
> This is a problem with Python, please uninstall it from control panel and reinstall (make sure to enable "Add to PATH option").

it still doesnt work
i deleted it from control panel and when i reinstalled it i downloaded blank grabber and it still dont work-_-

**Comment by Blank-c** [comment]
Did it show the same error? Which python version are you using? Also try to type `python -m pip install customtkinter` in command prompt.

**Comment by ExecutivePrograms** [comment]
> > This is a problem with Python, please uninstall it from control panel and reinstall (make sure to enable "Add to PATH option").
> 
> it still doesnt work i deleted it from control panel and when i reinstalled it i downloaded blank grabber and it still dont work-_-

Open cmd and write this: pip install customtkinter

**Comment by ghubrakesh** [comment]
> > You don't have the python library "customtkinter" installed in your system. Just install the package using package using `pip install customtkinter` and run the code again.
> 
> where do i get customkinter

Just run the pip install command I provided and `customtkinter' will get installed in your machine.
