### ISSUE TITLE
How to login with steam.

### ISSUE THREAD

**Issue by ParrotPatcher** [Blank-c/Blank-Grabber#329]
Hey Blank! So After i log someones steam account i was wondering on how to login. I think its something with the files it gives you but im not the smartest. i was wondering if you would be able to tell me how? Its no problem if you dont have time!

**Comment by Blank-c** [comment]
> Paste the grabbed files as well as the ssfn files into your own steam installation folder (usually in `C:/Program Files(x86)/Steam`. 
Then run steam, it will ask you to login. Simply login to your own account Then go to your account and click on 'change account', steam will restart and show you 2 (or more) accounts. One will be yours and the other will be of the victim. You can then select their account. If he hasn't changed the password, you will get inside their account.

_Originally posted by @Blank-c in https://github.com/Blank-c/Blank-Grabber/issues/266#issuecomment-1616681976_

**Comment by ParrotPatcher** [comment]
thanks!
