### ISSUE TITLE
Reduce Detections

### ISSUE THREAD

**Issue by ExecutivePrograms** [Blank-c/Blank-Grabber#331]
Hey, I got an idea to reduce detections.

You shall make the output as obfuscated batch file.

Inside the batch file, put a script that will download a exe file and execute it.

So it will reduce detections for the exe file.

**Comment by Blank-c** [comment]
I had this idea but there is a problem with that. As soon as the exe file is saved on disk, the antivirus will raise alarms.

**Comment by Blank-c** [comment]
I would rather add an open to recompile Pyinstaller bootloader on buildtime if it reduces detections.

**Comment by Blank-c** [comment]
For now, it is unavoidable. The GUI binary of Pyinstaller is getting flagged. But I'll continue working on this issue.
