### ISSUE TITLE
I have python install from website but when i run there says errror

### ISSUE THREAD

**Issue by gewoonhacker123** [Blank-c/Blank-Grabber#333]
please help i have it install from website not from store but it still says error i checked in cmd and it says it there the python path

**Comment by Blank-c** [comment]
Can you share a screenshot of the output of the command `where python && python --version`

**Comment by gewoonhacker123** [comment]
> Can you share a screenshot of the output of the command `where python && python --version`
Sure just wait a sec

**Comment by gewoonhacker123** [comment]
> Can you share a screenshot of the output of the command `where python && python --version`
Mb fucking bad i am so stupid sorry i figured it out i had to many python version installed sorry sorry
