### ISSUE TITLE
Reopen if you want to answer.

### ISSUE THREAD

**Issue by darknightmc80** [Blank-c/Blank-Grabber#335]
Reopen if you want to answer.

_Originally posted by @Blank-c in https://github.com/Blank-c/Blank-Grabber/issues/221#issuecomment-1594819284_

**Comment by darknightmc80** [comment]
when I tested the payload on my second PC it worked and I just left it for like a day. After like 2 days when I came back to Discord there were like 500 pings on the test server I used for it and it said YOU GOT BEAMED SAY GOOD BUY TO YOUR DICORD ACC and the dummy account I used for the test was taken from my secondary email and I had been logged out ( this is a malware trap isn't it ?)

(sorry for the bad typing my primary language is not English)

**Comment by darknightmc80** [comment]
and if its not a trap just explain how did that happen

**Comment by darknightmc80** [comment]
side note it failed to grab some other passwords from chrome

**Comment by Blank-c** [comment]
This code is completely safe, you can check every line of the code.

From what it looks like, you either downloaded it from somewhere else or you got infected by other malware. 

I'd recommend you to scan your second PC using a good antivirus, like malwarebytes.
And if you found something suspicious, feel free to DM me on telegram.

**Comment by darknightmc80** [comment]
> This code is completely safe, you can check every line of the code.
> 
> From what it looks like, you either downloaded it from somewhere else or you got infected by other malware.
> 
> I'd recommend you to scan your second PC using a good antivirus, like malwarebytes. And if you found something suspicious, feel free to DM me on telegram.

completely reinstralled it and added a fresh new set of test accounts and stuff

**Comment by darknightmc80** [comment]
> It can be possible that you had any other malware in your PC.

nah I just tested that just after setting a fresh windows os

**Comment by darknightmc80** [comment]
and im 100% sure im the only one new the things I used for it like the bot/webhook  and was the only one on the test server

**Comment by darknightmc80** [comment]
sorry clicked it by a mistake

**Comment by darknightmc80** [comment]
mmmm guess i gotta wait for someone else to get beamed

**Comment by darknightmc80** [comment]
since i cant prove it by myself

**Comment by Blank-c** [comment]
You may join my telegram group and ask others if something like this happened to them and ask for help.

**Comment by darknightmc80** [comment]
why dont you guys use discord or smt?
(just asking)

**Comment by Blank-c** [comment]
Discord bans

**Comment by darknightmc80** [comment]
> Discord bans such servers.

i don't think so as long as you're informing its for educational purposes only and not supporting wrong behavior your fine
I'm saying that because a RAT builder project has a discord server that was started in 2018 and it is still fine.

**Comment by Blank-c** [comment]
I had a testing server for this but it (+ my main account) got banned after 1 year.

Since then I created two accounts and both of them ended up getting banned in not more than 1 week.
