### ISSUE TITLE
no such files directory

### ISSUE THREAD

**Issue by pasteque57** [Blank-c/Blank-Grabber#340]
hello when i lunch bulder.bat the error is 
python: can't open file 'C:\\Users\\______\\AppData\\Local\\Temp\\Temp1_Blank-Grabber-main.zip\\Blank-Grabber-main\\Blank Grabber\\gui.py': [Errno 2] No such file or directory
but i dont move any files en de codes sems ok so i dont enderstand
thanks

**Comment by Blank-c** [comment]
You have to extract the files to a folder before running.

**Comment by pasteque57** [comment]
sorry i'm dumb
