### ISSUE TITLE
Pls help me with this

### ISSUE THREAD

**Issue by admin863078** [Blank-c/Blank-Grabber#341]
How can i fix this
![image](https://github.com/Blank-c/Blank-Grabber/assets/70264110/a3dea9c2-0cbe-4806-9dcb-a84fb2b18f34)

**Comment by Blank-c** [comment]
Can you type `where python & python --version` in cmd

**Comment by admin863078** [comment]
![image](https://github.com/Blank-c/Blank-Grabber/assets/70264110/946604ce-7067-4231-9d3a-4454eab8ddde)
![image](https://github.com/Blank-c/Blank-Grabber/assets/70264110/e941710c-df43-4694-bf8d-f0f459b8b0be)

**Comment by Blank-c** [comment]
Please uninstall all the python versions you have and install the latest one from the [website](https://python.org/download).

**Comment by Blank-c** [comment]
works now?

**Comment by Blank-c** [comment]
Reopen if necessary
