### ISSUE TITLE
PLEASE HELP ME FOR PASSWORLDS 

### ISSUE THREAD

**Issue by HackTipsT** [Blank-c/Blank-Grabber#342]
[](https://cdn.discordapp.com/attachments/1135017651899478178/1135021737692631080/image.png)

**Comment by Blank-c** [comment]
When you ran blank grabber for first time, it asked you the password to use. Do you remember what you put there? If you put nothing there, the password would be `blank123`.

Anyways you can check it inside the config.json file next to the builder.bat file.
