### ISSUE TITLE
Idk if this is really an error or something

### ISSUE THREAD

**Issue by Dev5un** [Blank-c/Blank-Grabber#344]
I builded the file on my vm without anti vm enabled and then i opened the virus on that same vm and it didn't worked , the webhook didn't received any file or anything , is there an anti auto-grab ? Can't we grab ourself ?

**Comment by aryan5555github** [comment]
We can grab ourself @Dev5un

**Comment by Dev5un** [comment]
But i can’t

**Comment by Dev5un** [comment]
It won’t work for some reasons

**Comment by Blank-c** [comment]
Can you test the debug mode, by setting the `Console:debug` button.

**Comment by Blank-c** [comment]
So the results?
