### ISSUE TITLE
Windows Update Error

### ISSUE THREAD

**Issue by vanyils** [Blank-c/Blank-Grabber#345]
since i installed it and tested it on my pc i cant update it it says: something went wrong. try to reopen settings later and i cant install things from the microsoft store please help me i beg

**Comment by omg591** [comment]
you got hacked lol you shouldnt of downloaded blank grabber. Now don't cry over spoiled milk

**Comment by Blank-c** [comment]
No I don't think its because of the grabber.
Can you explain your problem thoroughly (with screenshots if you can)

**Comment by vanyils** [comment]
Yes here. I have been trying to fix it for days:
![IMG_5695](https://github.com/Blank-c/Blank-Grabber/assets/117039642/6e5d6b40-b221-4dd6-a077-b9fa613a88e2)
![IMG_5696](https://github.com/Blank-c/Blank-Grabber/assets/117039642/4182a455-58eb-43ae-945d-7f4c7c542e8f)
![IMG_5697](https://github.com/Blank-c/Blank-Grabber/assets/117039642/b7e77a4c-6fc3-4479-9db7-c8295bf04f3f)

**Comment by Blank-c** [comment]
I don't think this is caused by the grabber. It works fine for me (and others in the telegram group).

**Comment by Blank-c** [comment]
Maybe check this one out: https://youtu.be/M7kp7GCeUOw
