### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ExecutivePrograms** [Blank-c/Blank-Grabber#346]
**No Python at '"C:\Users\godya\AppData\Local\Programs\Python\Python312\python.exe'
1059 DEPRECATION: Bytecode encryption will be removed in PyInstaller v6. Please remove your --key=xxx argument to avoid breakages on upgrade. For the rationale/alternatives see https://github.com/pyinstaller/pyinstaller/pull/6999
1060 INFO: PyInstaller: 5.13.0
1060 INFO: Python: 3.11.0
1077 INFO: Platform: Windows-10-10.0.19045-SP0
1082 INFO: wrote C:\Users\godya\Desktop\Blank-Grabber-main\Blank Grabber\env\Scripts\Built.exe.spec
1120 INFO: UPX is available and will be used if enabled on build targets.
1120 INFO: Removing temporary files and cleaning cache in C:\Users\godya\AppData\Local\pyinstaller
1123 DEPRECATION: Bytecode encryption will be removed in PyInstaller v6. Please remove cipher and block_cipher parameters from your spec file to avoid breakages on upgrade. For the rationale/alternatives see https://github.com/pyinstaller/pyinstaller/pull/6999
script 'C:\Users\godya\Desktop\Blank-Grabber-main\Blank Grabber\env\Scripts\loader-o.py' not found**

**Comment by Blank-c** [comment]
Please disable your antivirus.

In cmd type `where python && python --version` and send screenshot.

**Comment by ExecutivePrograms** [comment]
> where python && python --version

> 
![d](https://github.com/Blank-c/Blank-Grabber/assets/133688649/f576b1a0-8a59-492f-b627-6e8855740483)

**Comment by Blank-c** [comment]
Did you disable virus + deleted env folder?

**Comment by ExecutivePrograms** [comment]
> Did you disable antivirus + deleted env folder?

Yes, I did. Shall I retry?

**Comment by Blank-c** [comment]
sure

**Comment by Blank-c** [comment]
works now?
