### ISSUE TITLE
yo i get info yk but like i dont get a zip i get a war file which asks for a password i got the file from go file 

### ISSUE THREAD

**Issue by Q1CKS1LVER** [Blank-c/Blank-Grabber#348]
Please help me discord Q1CKS1LVER#9938
how me get info i got a weird black something war file asking for a password to archive it. Please help

**Comment by Blank-c** [comment]
When you first used the grabber, it asked you to set a password for the archive. If you set nothing, the default password is `blank123`

**Comment by Q1CKS1LVER** [comment]
oh thats weird asf i typed the password just n and worked xd maybe cuz when it asked me y/n i put n so thats the pass idrk but ty for ur help:D
