### ISSUE TITLE
folder not opening

### ISSUE THREAD

**Issue by canzozozozozo** [Blank-c/Blank-Grabber#35]
ive done everything and the dist file doesnt open

**Comment by Blank-c** [comment]
Do you have python installed? Replace `exit` with `pause` in run.bat file and see if there are any errors.

**Comment by canzozozozozo** [comment]
i have pyhton, what exit and pause

**Comment by Blank-c** [comment]
open *run.bat* file in the data folder using notepad. Remove every word "cls" and replace every word "exit" with "pause". It will pause the compilation of the program if some error happens

Also if possible. Can you record your screen for me to check what happened.

**Comment by canzozozozozo** [comment]
idk it didnt work for my friend either but like we reinstalled 3 times and now it works so i think its okay now thanks
