### ISSUE TITLE
Hey there is a error idk what

### ISSUE THREAD

**Issue by gewoonhacker123** [Blank-c/Blank-Grabber#350]
![help](https://github.com/Blank-c/Blank-Grabber/assets/140543036/49d776a7-23b0-4fd3-9110-8961e39af018)

**Comment by Blank-c** [comment]
Disable antivirus and delete the `env` folder near the Builder file and rebuild.

**Comment by gewoonhacker123** [comment]
> Disable antivirus and delete the `env` folder near the Builder file and rebuild.

Yes it worked maybe pin this for other people

**Comment by Blank-c** [comment]
Can't pin more than one issue and must keep the important ones pinned.
