### ISSUE TITLE
Error line 12 idk why

### ISSUE THREAD

**Issue by Fexx06** [Blank-c/Blank-Grabber#351]
![image](https://github.com/Blank-c/Blank-Grabber/assets/141052100/516d55b4-174d-4797-b3a2-ee3ca97c5e41)

**Comment by Blank-c** [comment]
Please reinstall Python. This is happening to many users where pip is not working properly and reinstalling can fix it.

Make sure to uninstall it before reinstalling.

**Comment by Blank-c** [comment]
Works now?

**Comment by Fexx06** [comment]
Yes it works, you have to use a x64 version of python, I was using x32
