### ISSUE TITLE
Issue with building

### ISSUE THREAD

**Issue by Coolthan** [Blank-c/Blank-Grabber#353]
"306 DEPRECATION: Bytecode encryption will be removed in PyInstaller v6. Please remove your --key=xxx argument to avoid" It has a bunch of other stuff too. I was looking at other issues and I turned of anti-virus and delete the env file. Still not working.

**Comment by Blank-c** [comment]
Can you send me full screenshot.

**Comment by Coolthan** [comment]
I think I fixed it. I redownloaded both things and now it works
