### ISSUE TITLE
Suggetsion

### ISSUE THREAD

**Issue by gewoonhacker123** [Blank-c/Blank-Grabber#354]
Add 2fa codes so when u trying to log in into a user account with 2fa that the codes send to u idk if its possible but luna grabbers has it

**Comment by gewoonhacker123** [comment]
Backup codes for roblox i mean

**Comment by Blank-c** [comment]
Let me tell you how Luna Grabber's "backup codes" feature work.

It will simply search the downloads folder for a file named "discord_backup_codes.txt". If the file is found, it will copy the file.

But this feature is not guaranteed to give the correct details, hence this grabber do not have the feature.

> Backup codes for roblox i mean

Roblox works on Authy or Google Authticator too, and so its not possible (or easy) to make it a feature.

**Comment by gewoonhacker123** [comment]
> Let me tell you how Luna Grabber's "backup codes" feature work.
> 
> It will simply search the downloads folder for a file named "discord_backup_codes.txt". If the file is found, it will copy the file.
> 
> But this feature is not guaranteed to give the correct details, hence this grabber do not have the feature.
> 
> > Backup codes for roblox i mean
> 
> Roblox works on Authy or Google Authenticator too, and so its not possible (or easy) to make it a feature.

**Comment by gewoonhacker123** [comment]
A another quostion i was trying to make my own theme but when i run the gui nothing works or did i do something wrong

**Comment by gewoonhacker123** [comment]
I was like trying to create a icon but it didnt work

**Comment by gewoonhacker123** [comment]
![Chungus stealer (1)](https://github.com/Blank-c/Blank-Grabber/assets/140543036/63986048-0218-4774-b04e-ee0ad412fe6a)
I want to make it like this

**Comment by Blank-c** [comment]
I can't help with that. I have seen various people just changing the theme and posting as their own creation (either backdoored or not). This may have bad impacts for this project.

**Comment by gewoonhacker123** [comment]
O Np i understand

**Comment by aryan5555github** [comment]
> ![Chungus stealer (1)](https://user-images.githubusercontent.com/140543036/257591140-63986048-0218-4774-b04e-ee0ad412fe6a.png) I want to make it like this

A Chungus stealer lol
