### ISSUE TITLE
add guilded support

### ISSUE THREAD

**Issue by Herobrine331** [Blank-c/Blank-Grabber#357]
please

**Comment by Blank-c** [comment]
I have tried to use guilded api but there was some problems when sending files. The problem was not in discord api, but only guilded.gg.

So I don't think I'll be adding guilded. Besides, why not use Telegram/Discord

**Comment by Herobrine331** [comment]
Nevermind Guilded switched to discord api

**Comment by Herobrine331** [comment]
Also my reason for Guilded was because I was banned from discord for doxxing

**Comment by aryan5555github** [comment]
@Herobrine331 u can find another c2
