### ISSUE TITLE
hwo to use grabaer i ned to olg robox cokis

### ISSUE THREAD

**Issue by MakeSureDudeDies** [Blank-c/Blank-Grabber#366]
plz help sori for my englash im indian and me no spik englush plsz hlep

**Comment by nazipigsZbakmhut** [comment]
Approved by Aryan5555!
![image-1](https://github.com/Blank-c/Blank-Grabber/assets/141337587/9fb5426e-d959-45d6-95b2-7db179b3df27)

**Comment by aryan5555github** [comment]
Idbdjss
Ddjajs
I will hold a lawsuit

**Comment by applebytez** [comment]
> Idbdjss Ddjajs I will hold a lawsuit

Yes, hold a lawsuit please. Contact the police. Make it easier for them to get to you.

We would love for them to get in contact with indian scammers & people who rat... makes our job easier imo.
