### ISSUE TITLE
Idea for an update

### ISSUE THREAD

**Issue by Azuuu1** [Blank-c/Blank-Grabber#371]
First off all it would be great if the cookies would be sended like this:
Cookies Found!

youtube spotify

2 cookies found 
im juust giving an example here and second good thing would be a file stealer 
this is just 2 ideas but hope they will help :D

**Comment by Blank-c** [comment]
I don't think how segregating cookies is a good idea.

The files stealer is already there.

**Comment by Azuuu1** [comment]
yo sorry my bad i meant to wirte it on the luna logger my bad bro
