### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Witherred** [Blank-c/Blank-Grabber#40]
Can you make it that it grabs their discord token aswell and not just their log in details. Another suggestions, can you make gather all passwords from all browsers on the pc?

**Comment by Blank-c** [comment]
It already grabs discord token, I will try for other browsers too

**Comment by Witherred** [comment]
> It already grabs discord token, I will try for other browsers too

where do i find the tokens? because all i can find is their discord login

**Comment by Blank-c** [comment]
there is token inside the file, isn't it?

**Comment by Witherred** [comment]
> there is token inside the file, isn't it?

Yes there is my bad i tried it on my mates and only one of them had their discord on chrome which is why the file didnt show up mostly. my bad

**Comment by Witherred** [comment]
> It already grabs discord token, I will try for other browsers too

also how long do u think it'd take to add the other browser function? just askin

**Comment by Blank-c** [comment]
Depends on how busy I am

**Comment by Blank-c** [comment]
I tried to implement it and it surprizingly increased the virustotal detection. Also for most users, chrome is the default browser so I am currently not going to implement it

**Comment by dotmp4** [comment]
try not to upload it to virustotal because virustotal spreads it to other defenders which will also increase detection, ive been told to use this https://www.antiscan.me/
