### ISSUE TITLE
Virus

### ISSUE THREAD

**Issue by Witherred** [Blank-c/Blank-Grabber#41]
Chrome recognises it as a virus is there anyway this can be avoided. Same with windows although i think itd be hefty work to avoid windows defender.

**Comment by Blank-c** [comment]
why not pack it into a password protected zip file and then send to someone??

**Comment by Witherred** [comment]
> why not pack it into a password protected zip file and then send to someone??

because people find that fishy and instantly think its a virus (in my opinion)

**Comment by Blank-c** [comment]
yea
