### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Witherred** [Blank-c/Blank-Grabber#42]
Sorry for all of the posts but I was wondering how do people make these sort of things and how did you make it search through chrome for passwords. Ill stop asking on forums after this. Also, what's your discord.

**Comment by Blank-c** [comment]
Chrome saves its passwords encrypted in a data base file in its folder. The program searches through the file and tries to decrypt the passwords.

Discord: *Blank?#0886*

**Comment by Blank-c** [comment]
please close the issue when solved :)
