### ISSUE TITLE
Start the Grabber

### ISSUE THREAD

**Issue by Gaminguide1000** [Blank-c/Blank-Grabber#45]
Is there a way to start the Grabber using a .bat? "start "Blank Grabber.exe"" results in a cmd without starting the grabber

**Comment by Blank-c** [comment]
Why do you want to start the grabber using a bat file when you can double click it?

BTW if you want to start the grabber you can write `call <grabber name>.exe` in bat file.

**Comment by Gaminguide1000** [comment]
Thanks, i wanted to start it using a so a 0% sus file can run it
