### ISSUE TITLE
Do you know of any token grabbers for mobile? Or will your work for mobile?

### ISSUE THREAD

**Issue by Trent2990** [Blank-c/Blank-Grabber#47]

**Comment by Trent2990** [comment]
Also your discord link to contact you won't work😕

**Comment by Blank-c** [comment]
**Mobile token grabber require rooter device (not so many people have their device rooted).**
or
**Creating a custom discord android app with backdoor and making the user log in it.**

> Also your discord link to contact you won't work😕

Fixed, thanks for informing!
