### ISSUE TITLE
contect discord

### ISSUE THREAD

**Issue by Brandon981026** [Blank-c/Blank-Grabber#48]
i sant discord invitation requast to you, can you accapt it?
cuz i have bunch of question to ask
or i can just ask here
1. can you gave me the website to install the virtualenv? i did find it myself but i don't want to download the worng one
thanks
i just start learning codes

**Comment by Brandon981026** [comment]
the name from my discord is called Brandon允凱

**Comment by Blank-c** [comment]
@Brandon981026 you must install virtual env using `pip install virtualenv` in command prompt (Make sure you have python installed and added to path)
