### ISSUE TITLE
question

### ISSUE THREAD

**Issue by canzozozozozo** [Blank-c/Blank-Grabber#49]
does it grab cookies and passwords from microsoft edge? if not is there an update soon for it?

**Comment by Blank-c** [comment]
Passwords: Internet Explorer (Version 4.0 - 11.0), Mozilla Firefox (All Versions), Google Chrome, Safari, and Opera.

Cookies: Chrome only.

I don't think there would be an update to it in a while, as most people use Chrome.

**Comment by canzozozozozo** [comment]
ofo okay thanks

**Comment by jontstaz** [comment]
> Passwords: Internet Explorer (Version 4.0 - 11.0), Mozilla Firefox (All Versions), Google Chrome, Safari, and Opera.
> 
> Cookies: Chrome only.
> 
> I don't think there would be an update to it in a while, as most people use Chrome.

And nobody uses IE. Many people use Edge, way more than use IE that's for sure. For example most workplaces enforce the use of Edge as they don't allow other browsers or applications to be downloaded so the employees are forced to use Edge as it's the default browser.

**Comment by bruh-bruh8** [comment]
> > Passwords: Internet Explorer (Version 4.0 - 11.0), Mozilla Firefox (All Versions), Google Chrome, Safari, and Opera.
> > Cookies: Chrome only.
> > I don't think there would be an update to it in a while, as most people use Chrome.
> 
> And nobody uses IE. Many people use Edge, way more than use IE that's for sure. For example most workplaces enforce the use of Edge as they don't allow other browsers or applications to be downloaded so the employees are forced to use Edge as it's the default browser.

if they dont allow chrome they wont allow discord

**Comment by canzozozozozo** [comment]
> > Passwords: Internet Explorer (Version 4.0 - 11.0), Mozilla Firefox (All Versions), Google Chrome, Safari, and Opera.
> > Cookies: Chrome only.
> > I don't think there would be an update to it in a while, as most people use Chrome.
> 
> And nobody uses IE. Many people use Edge, way more than use IE that's for sure. For example most workplaces enforce the use of Edge as they don't allow other browsers or applications to be downloaded so the employees are forced to use Edge as it's the default browser.

yeah thats right, i agree

**Comment by Blank-c** [comment]
> 

*"most workplaces enforce the use of Edge as they don't allow other browsers or applications to be downloaded"*

Then why would they allow the stub?

**Comment by canzozozozozo** [comment]
i tried it, it gives me virus on google chrome and edge

**Comment by Blank-c** [comment]
> > > 
> > 
> > 
> > _"most workplaces enforce the use of Edge as they don't allow other browsers or applications to be downloaded"_
> > Then why would they allow the stub?
> 
> i tried it, it gives me virus on google chrome and edge

wdym?
