### ISSUE TITLE
Invalid Webhook

### ISSUE THREAD

**Issue by mkdiretc** [Blank-c/Blank-Grabber#5]
I have created 3 channels , voice and text, created webhooks, but your software it always tell me invalid hook.

**Comment by Blank-c** [comment]
> I have created 3 channels , voice and text, created webhooks, but your software it always tell me invalid hook.

Conditions for it to consider a webhook legit:-
1) Webhook should start with "https://discord.com/api/webhooks/"
2) It should be valid

**Comment by Blank-c** [comment]
If the error still persists, you can download older versions too to check for yourself

**Comment by mkdiretc** [comment]
All is ok. My webhook was with discordAPP.com , anyway, can you msg me to @mkdirnow , on telegram ?

**Comment by mkdiretc** [comment]
as, when I am to step : ICON, is closing without any warnings

**Comment by Blank-c** [comment]
> All is ok. My webhook was with discordAPP.com , anyway, can you msg me to @mkdirnow , on telegram ?

sorry I don't use tepegram

**Comment by Blank-c** [comment]
> as, when I am to step : ICON, is closing without any warnings

Can you upload a video on how and what happens?

**Comment by mkdiretc** [comment]
is Just close the window. That`s all. mkdiretc1#3992 this is my discord, I would like to discuss some technical problems.

**Comment by Blank-c** [comment]
Works fine of my and my other discord friends' devices. Check if your firewall or antivirus is blocking it or not. Can't use discord so please keepvyour issue here.

**Comment by Blank-c** [comment]
Also check if older versions are working or not
