### ISSUE TITLE
Where can the txt files be found?

### ISSUE THREAD

**Issue by FH204** [Blank-c/Blank-Grabber#51]
now ofc I am trying this on myself before anything to test it's working properly and so I'm receiving the notifications through the discord web hook but I can't seem to find where the txt files and grabbed information is stored.

**Comment by Blank-c** [comment]
it should be below the webhook?

**Comment by FH204** [comment]
excuse my incompetence but I'm a bit lost, where would I look a little more specifically please. In discord? or in any directory files. is the discord output supposed be a link to the text?
![tokens - Discord 8_8_2022 8_17_48 PM](https://user-images.githubusercontent.com/110859316/183542024-fb3579da-eebe-458f-87ce-d705697bf403.png)

**Comment by Blank-c** [comment]
The output should be a discord attachment. With what you are trying to say, it looks like your attachment is not send to the webhook. There could be various reasons and the problem is not of the grabber. What you can do is to run it again.

**Comment by Blank-c** [comment]
I would probably add another file hosting server for this in the next update.

**Comment by FH204** [comment]
I've ran through the process a couple times again and I'm still able to get the same discord notifications but still no attachment, any Ideas on how to troubleshoot this?

**Comment by Blank-c** [comment]
Have you tried turning off antivirus?

**Comment by FH204** [comment]
Yes, I made sure of it and It's been off consistently for a few days now. anything else I could be missing?

**Comment by Blank-c** [comment]
Try to remove the `--noconsole` flag from the convert.bat file in the data folder and then build again, it might show the error in the console.

**Comment by FH204** [comment]
if you meant to edit the convert.bat file by removing --noconsole then I just did that and even saved it and when I built again, strangely it still worked the same way it has been working with no attachment in the discord server

**Comment by FH204** [comment]
wait I forgot a line one sec

**Comment by FH204** [comment]
nope, strange. even still it just did what It's been doing. builds the exe, I run the exe, I get the notifications on discord but no attachment to be found. one thing I do which could be improper is close the two running Blank Grabber processes by going under "details" in task manager and ending the tasks.

**Comment by FH204** [comment]
okay so I went into the the scripts folder and removed --noconsole from the convert.bat in there and built again and this time the console was shown and I was given these errors on repeat infinitely

 FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\MyName\\AppData\\Local\\Google\\Chrome\\User Data\\Local Storage\\leveldb'
Exception in thread Thread-469 (<lambda>):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "<string>", line 329, in <lambda>
  File "<string>", line 295, in RickRollDecrypt
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\MyName\\AppData\\Local\\Microsoft\\Edge\\User Data\\Local Storage\\leveldb'
Exception in thread Thread-531 (<lambda>):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "<string>", line 329, in <lambda>
  File "<string>", line 295, in RickRollDecrypt

**Comment by Blank-c** [comment]
> okay so I went into the the scripts folder and removed --noconsole from the convert.bat in there and built again and this time the console was shown and I was given these errors on repeat infinitely
> 
> FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\Users\MyName\AppData\Local\Google\Chrome\User Data\Local Storage\leveldb' Exception in thread Thread-469 (): Traceback (most recent call last): File "threading.py", line 1016, in _bootstrap_inner File "threading.py", line 953, in run File "", line 329, in File "", line 295, in RickRollDecrypt FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\Users\MyName\AppData\Local\Microsoft\Edge\User Data\Local Storage\leveldb' Exception in thread Thread-531 (): Traceback (most recent call last): File "threading.py", line 1016, in _bootstrap_inner File "threading.py", line 953, in run File "", line 329, in File "", line 295, in RickRollDecrypt

I would release a fix for it today, probably it would fix your problem too

**Comment by FH204** [comment]
Alright sweet I'll leave you to your work and attempt again once the new release is up. thanks! (' v ')
