### ISSUE TITLE
Unable to connect to the internet

### ISSUE THREAD

**Issue by Bluebricki** [Blank-c/Blank-Grabber#52]
When i try to test the webhook it freeze an say Unable to connect to the internet

**Comment by Blank-c** [comment]
You need internet connection.

**Comment by Blank-c** [comment]
check if you can connect to http://1.1.1.1 in any browser

**Comment by Bluebricki** [comment]
I'm on the internet and can't connect to this link

**Comment by Blank-c** [comment]
I would look into the problem, can you give video/images of the error?

**Comment by Bluebricki** [comment]
yes 1 sec

**Comment by Bluebricki** [comment]
can we write on discord it's a bit easier for me

**Comment by Bluebricki** [comment]
to sent the video

**Comment by Blank-c** [comment]
sure but I might not be able to reply right now as its literally 1 AM here

**Comment by Bluebricki** [comment]
ahaha ok

**Comment by Bluebricki** [comment]
Wolke#1000 write me a dm or friend request

**Comment by Blank-c** [comment]
<kbd>Blank?#0886</kbd> Can't access discord right now, so you can add me instead.

Also, I'd recommend you to try again with a different wifi

**Comment by Blank-c** [comment]
@Bluebricki Please close the issue if solved

**Comment by MintOnTop** [comment]
I had the same problem but I solved it with just disabling my VPN, maybe this helps...
