### ISSUE TITLE
detected by Zillya

### ISSUE THREAD

**Issue by Righted1** [Blank-c/Blank-Grabber#53]
so i tried to test my file on hybrid analysis, the most of the grabber works, other than detections, in which this case is detected by zillya.
heres the link to the analysis: https://www.hybrid-analysis.com/sample/3bd142722a9bd89b0992ea15f95fba2ae4b5b92811e7de11d7f5afaca4fda8c6

**Comment by Blank-c** [comment]
Some antivirus can detect pyinstaller. In the readme file, I have written, its undetected by Yara (used by virustotal).

**Comment by Blank-c** [comment]
It can still be detected by modifying yara easily but virustotal use that one and only yara rule for pyinstaller

**Comment by Blank-c** [comment]
Solved, I guess?
