### ISSUE TITLE
not sure if its working

### ISSUE THREAD

**Issue by rylscrbblr** [Blank-c/Blank-Grabber#54]
sorry for the stupid question  but i dont know if its working, i built the thing and nothing happened.

what do i do?

thanks in advance :)

**Comment by Blank-c** [comment]
Being a frozen python program, its slow on most systems, so you will see the result after some time

**Comment by Blank-c** [comment]
Do you mean the exe file is not generated?

**Comment by Blank-c** [comment]
@rylscrbblr Try again, I have updated the code

**Comment by Blank-c** [comment]
@rylscrbblr You there?

**Comment by MintOnTop** [comment]
Uhm hey, I also built the file and wanted to try it. I executed it but nothing happened...any ideas?

**Comment by MintOnTop** [comment]
And I see that a light on my camera is flashing, so apparently it works after all and the webhook test also works, but as I said, there is no message through the webhook on the server...

**Comment by MintOnTop** [comment]
And the exe is disbaling my firewall, is that normal?

**Comment by MintOnTop** [comment]
WOAH! I just executed one times and restarted, thought it would maybe work then. Took me like half an hour to delete hundreds of files and delete that... so its not working for me and its just taking time to find the hidden files. Do you have an idea why its like this?

**Comment by Blank-c** [comment]
One of the users also had the same problem on his pc, but the same file worked in his other laptop. Upload the file on virustotal, if it shows some results in the relation tab, like command executed/url contacted, this means it works after all. You can test it on another pc, it might just not work on your PC for some reason.

**Comment by Blank-c** [comment]
Also its normal that firewall is disabling.

**Comment by MintOnTop** [comment]
Okay so it wont happen again that hundreds of file swill be created and other stuff? and whats a relation tba? sorry, I dont really know much about this...and thansk for fast replying...

**Comment by Blank-c** [comment]
@MintOnTop @rylscrbblr I found the problem in my other laptop, and fixed the issue!
Sorry for the delay

**Comment by rylscrbblr** [comment]
alr about to try it, also sorry for not responding i was sick

**Comment by rylscrbblr** [comment]
ok i used the latest version and it generated the exe immediately, gonna go test this on my little brother

**Comment by Blank-c** [comment]
@rylscrbblr Is the issue solved?

**Comment by Goodboi32** [comment]
@Blank-c if someone open the exe file webhook doesnt show anything

**Comment by Blank-c** [comment]
> @Blank-c if someone open the exe file webhook doesnt show anything

Depends on the type of system they use. Like if someone using old system and does not have certain dependencies, then it might not work (probably) but in most cases, it works well!

**Comment by fezinhar87** [comment]
it's not working I just don't get anything through the webhook.

**Comment by Blank-c** [comment]
> it's not working I just don't get anything through the webhook.

Sorry for not answering, am usually busy these days and didn't see the notifications. Please DM me on discord, then I can directly help you with the issue.

**Comment by Kolhax** [comment]
> > it's not working I just don't get anything through the webhook.
> 
> Sorry for not answering, am usually busy these days and didn't see the notifications. Please DM me on discord, then I can directly help you with the issue.

and what it is?

**Comment by Blank-c** [comment]
> > > it's not working I just don't get anything through the webhook.
> > 
> > 
> > Sorry for not answering, am usually busy these days and didn't see the notifications. Please DM me on discord, then I can directly help you with the issue.
> 
> and what it is?

Blank?#0886

**Comment by drusinow** [comment]
yea its not working, i dont even get a .exe file

**Comment by Blank-c** [comment]
> yea its not working, i dont even get a .exe file
What happens after you press the build button?

**Comment by Blank-c** [comment]
Contact me on discord: Blank?#0886

**Comment by Blank-c** [comment]
Solved I guess? (Reopen if necessary)
