### ISSUE TITLE
Remove the token grabber

### ISSUE THREAD

**Issue by beebo1** [Blank-c/Blank-Grabber#55]
I ran the grabber on my pc but keep getting pinged now and I check the 'startup' folder but there is no vbs in there and I have hidden files shown on, how do I remove it?

**Comment by Blank-c** [comment]
The vbs method has been removed. Now if you want to remove the exe

1) Go to *Run* dialog box
2) Type `shell:common startup`
3) Delete the "screensaver" named files.

**Comment by beebo1** [comment]
Thanks!

**Comment by dr-dark-flames** [comment]
how to undo changes made by Blank Grabber if ran on my pc?

**Comment by Blank-c** [comment]
> how to undo changes made by Blank Grabber if ran on my pc?

what changes?

**Comment by dr-dark-flames** [comment]
Like discord injection.

**Comment by Blank-c** [comment]
> Like discord injection.

In `%localappdata%` directory, remove any directory whose name contains `discord`.

**Comment by dr-dark-flames** [comment]
Thank u man. Ur work is great. Can I add u on discord?
