### ISSUE TITLE
Invalid Discord Webhook

### ISSUE THREAD

**Issue by noahmajors** [Blank-c/Blank-Grabber#58]
When copying and pasting webhooks from discord, the program states that it is invalid. After reading through the script, I cant find why to as this is, because it checks that the url starts with https://discordapp.com/api/webhooks/. Dont know what the issue could be

**Comment by noahmajors** [comment]
found that removing lines 81 82 83 158 159 160 from builder.py solves the issue entirely. Just bypasses the check to make sure that its an actual webhook and forces it instead. Confirmed to work with the test feature.

perhaps you should push those changes, bc if someone isn't competent enough to know how to copy and paste a webhook url, then they shouldn't be using the program anyway.

**Comment by Blank-c** [comment]
> When copying and pasting webhooks from discord, the program states that it is invalid. After reading through the script, I cant find why to as this is, because it checks that the url starts with https://discordapp.com/api/webhooks/. Dont know what the issue could be

A little correction, it checks if the url starts with **https://discord.com/api/webhooks/** ~~https://discordapp.com/api/webhooks/~~

So you dont have to remove any lines, just write the webhook in that format.

**Comment by noahmajors** [comment]
ahh. I see. I know it’s an easy fix but perhaps you could add those lines to allow for the discordapp variant to work as well, because I just removed the lines altogether and pasted and it works flawlessly. So my advice is to either remove the line of code entirely, or allow it to accept discordapp. I’ll submit a merge later.

**Comment by Blank-c** [comment]
Ye I thought about it, will do it soon
