### ISSUE TITLE
gui closes immediately after clicking build

### ISSUE THREAD

**Issue by noahmajors** [Blank-c/Blank-Grabber#59]
as the title stated, the gui closes almost immediately after pressing build. No file is output from the gui. No errors thrown.

**Comment by Blank-c** [comment]
Ok so first answer my few questions:

1) Have you extracted all the files from the zip?
2) Your antivirus didn't delete any file right?

Quick checking the errors:
Open cmd in the *current dir* (where builder.py is located) and then type
```
python builder.py
```
Build, if it closes immediately again, you will see error.

If not sure about something, contact on my discord

**Comment by Blank-c** [comment]
is there `...\env\Scripts\activate.bat` file after you click building?

**Comment by noahmajors** [comment]
when running the program from cmd "python builder.py" an output is created. when running directly from either the .bat or the .py however, no output is generated

**Comment by Blank-c** [comment]
> when running the program from cmd "python builder.py" an output is created. when running directly from either the .bat or the .py however, no output is generated

You mean, the exe is generated?

**Comment by noahmajors** [comment]
yes the exe is generated

**Comment by Blank-c** [comment]
What is the output of the commands?
```
where python
```
```
python --version
```

**Comment by noahmajors** [comment]
C:\Users\Noah>where python
C:\Python310\python.exe
C:\Users\Noah\AppData\Local\Microsoft\WindowsApps\python.exe
C:\Program Files\Inkscape\bin\python.exe

C:\Users\Noah>python --version
Python 3.10.4

**Comment by Blank-c** [comment]
just keep the first one and uninstall the other python installations

**Comment by Blank-c** [comment]
@noahmajors Is the issue solved?

**Comment by fezinhar87** [comment]
> C:\Users\Noah>where python C:\Python310\python.exe C:\Users\Noah\AppData\Local\Microsoft\WindowsApps\python.exe C:\Program Files\Inkscape\bin\python.exe
> 
> C:\Users\Noah>python --version Python 3.10.4

keep only this installation "C:Python310python.exe" and uninstall the others, go to control panel and repair this installation.
also check that the environment variables are pointing to "C:\Users\Noah\AppData\Local\Programs\Python\Python310" and "C:\Users\Noah\AppData\Local\Programs\Python\Python310\scripts"
