### ISSUE TITLE
Crashes/closes after Icon

### ISSUE THREAD

**Issue by Gaminguide1000** [Blank-c/Blank-Grabber#6]
After i typed in the icon name it just closes. It also happens when i dont type anything in. Theres no python error message or something like that. I have Python 3.10.2 installed

**Comment by Blank-c** [comment]
> After i typed in the icon name it just closes. It also happens when i dont type anything in. Theres no python error message or something like that. I have Python 3.10.2 installed

Please try older versions and check if the error still persists. If possible, please attach a video of what happens, I will look into the problem.

**Comment by TypicalMane** [comment]
the same thing happens to me, which version of python do you recommend?

**Comment by Blank-c** [comment]
Try the first version

**Comment by TypicalMane** [comment]
![unknown](https://user-images.githubusercontent.com/101685604/158509980-8995b177-2773-4f71-8922-11e86f9ca932.png)

I get that error for a millisecond and it closes.

**Comment by Gaminguide1000** [comment]
https://user-images.githubusercontent.com/63616197/158604840-5536852e-48e8-4f6e-9969-d9eef7a8c1ad.mp4

Here. I also sometimes see a error, but i dont know what it says cus its not in the video

**Comment by Gaminguide1000** [comment]
So, tried with 3.8.10, also isnt working

**Comment by Gaminguide1000** [comment]
3.9.10 also not working..

**Comment by Blank-c** [comment]
I cannot try to fix it if it doesn't show error

**Comment by Gaminguide1000** [comment]
Its likely the same as the other guy said

**Comment by Gaminguide1000** [comment]
Tried it on VM also happend. I uninstalled python, but it didnt say "python not installed" or smth like that, it just crashes again, after picture thingy

**Comment by Gaminguide1000** [comment]
Do you have a open-source version, or can u send me exactly the file u are using?

**Comment by Gaminguide1000** [comment]
i checked with the new one, while starting it, i had this:
![image](https://user-images.githubusercontent.com/63616197/158856293-6c69c31a-3a2a-4548-9279-7322355e7a56.png)
(It means "The Command "pip" is wrong written or couldnt be found")
Maybve something with that

**Comment by Gaminguide1000** [comment]
I meant with the newest generater version

**Comment by Gaminguide1000** [comment]
And also got the error now 
![image](https://user-images.githubusercontent.com/63616197/158856573-40bf3daa-45c7-4156-b00e-c8acce15638e.png)

**Comment by Gaminguide1000** [comment]
https://user-images.githubusercontent.com/63616197/158857325-c9274010-e568-4ffe-8a1f-82bbba60e348.mp4

Theres a Vid of it, and here is a screenshot of the script i started 
![image](https://user-images.githubusercontent.com/63616197/158857444-3698b1e1-328e-40d0-91cc-6475229417a7.png)
Yeah, i did start the convert to exe thingy, but yeah idk where it drops it

**Comment by Blank-c** [comment]
it drops the exe in a "dist" folder in the same directory. Makebsure you have installed the requirements and your python is 3.7+

**Comment by Blank-c** [comment]
> i checked with the new one, while starting it, i had this: ![image](https://user-images.githubusercontent.com/63616197/158856293-6c69c31a-3a2a-4548-9279-7322355e7a56.png) (It means "The Command "pip" is wrong written or couldnt be found") Maybve something with that

Oh have you added python to path when installing? Check google to fix "pip" not found issue, its the most important thing a python user should have fixed

**Comment by Gaminguide1000** [comment]
Nah i actually said the completely normal, its maybe cuz i have desktop, downloads, documents, pictures, and videos on my second drive, not the C: one

**Comment by Gaminguide1000** [comment]
Ima reinstall it now

**Comment by Gaminguide1000** [comment]
Is it maybe because i installed the 64 bit version?

**Comment by Gaminguide1000** [comment]
![image](https://user-images.githubusercontent.com/63616197/159035427-54459876-6ade-48a0-b2b0-3a383cbcb3b6.png)
There aint no dist folder bub

**Comment by Gaminguide1000** [comment]
Btw still not working

**Comment by Gaminguide1000** [comment]
So searched through complete C:, started it in C:\Programs with everything admin, no "dist" folder or something like that. Searched also the other drives, but nothing happening

**Comment by Blank-c** [comment]
> ![image](https://user-images.githubusercontent.com/63616197/159035652-166b0b44-28b8-4787-bbac-80b51bf5d1f5.png) and i just click install now

Click on add python to path, and type pip in command prompt, it it works then the grabber will work

**Comment by Gaminguide1000** [comment]
So, i do have the "dist" folder now, but the exe isnt working

**Comment by Blank-c** [comment]
> So, i do have the "dist" folder now, but the exe isnt working

How do you think its not working? have you installed the requirements?

**Comment by Gaminguide1000** [comment]
Well now it kinda works

**Comment by Gaminguide1000** [comment]
wait pls

**Comment by Gaminguide1000** [comment]
if u send someone the exe, does the person need python & the requirements?

**Comment by Blank-c** [comment]
> if u send someone the exe, does the person need python & the requirements?

Absolutely not

Random tip: If your file is more than 17 MB you can make a virtual environment (google's tutorial) and move all the files there and install requirements and create exe there, you will get a file of 16 mb

**Comment by Gaminguide1000** [comment]
Ok, so it works then, had some bugs but after trying it on vm it worked, thanks :D
