### ISSUE TITLE
Still not working..

### ISSUE THREAD

**Issue by Gumbobrot** [Blank-c/Blank-Grabber#61]
I followed all the steps (installed python and more...).But if I run the .vbs file a window pops up and closes instantly (one second or something after I ran it the file...) So.. then.. I thought thats not so import or just installing anything in the bgackground - so... I open the .py file and there is the menu where you can set up the config for the following build. So finally I think it's working. I tested the webhook three times and turned off "run on start up" and "vm protect". So. I click on build. Again a window pops up for one second or anything and tells me any error. But it instantly closes too fast, so I can't read what it's trying to tell me. Please give me some advice. Thanks!

**Comment by Blank-c** [comment]
Please contact me on discord, *Blank?#0886*

**Comment by Gumbobrot** [comment]
I already added you. But you have messages disabled. Accept my request.

**Comment by Blank-c** [comment]
> I already added you. But you have messages disabled. Accept my request.

already done so
