### ISSUE TITLE
ImportError: Module 'pywintypes' isn't in frozen sys.path

### ISSUE THREAD

**Issue by GoldenS0ulz** [Blank-c/Blank-Grabber#63]
opens documents when finished building and theres nothing in documents

**Comment by GoldenS0ulz** [comment]
fixed , now getting this error :
Traceback (most recent call last):
  File "PyInstaller\hooks\rthooks\pyi_rth_win32api.py", line 18, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "pywintypes.py", line 128, in <module>
  File "pywintypes.py", line 44, in __import_pywin32_system_module__
ImportError: Module 'pywintypes' isn't in frozen sys.path ['C:\\Users\\KHIERA~1\\AppData\\Local\\Temp\\_MEI117602\\base_library.zip', 'C:\\Users\\KHIERA~1\\AppData\\Local\\Temp\\_MEI117602\\lib-dynload', 'C:\\Users\\KHIERA~1\\AppData\\Local\\Temp\\_MEI117602']

**Comment by Blank-c** [comment]
Its a device related issue. Try to build the grabber in a virtual machine: https://app.apponfly.com/trial

**Comment by Blank-c** [comment]
What python version are you using?

**Comment by GoldenS0ulz** [comment]
python 3.9

**Comment by Blank-c** [comment]
Try upgrading your python version. Delete the env folder and then retry the builder. If you still got error, build the file in a vps/vm.

**Comment by Blank-c** [comment]
@GoldenS0ulz Is the issue fixed? If not, contact me on discord **Blank?#0886**

**Comment by GoldenS0ulz** [comment]
Issue isn't fixed, updated python version & still have the same error

**Comment by Blank-c** [comment]
@GoldenS0ulz
Follow these steps, if it didn't work, then contact me on discord:

1) Open cmd normally from the search box.
2) Type **`pip install --upgrade pywin32`**.
3) Follow this video from 23 seconds https://youtu.be/6RyCt2xWBcM?t=23.
4) Build the grabber again.

**Note:** Your *lib* folder will be inside the *env* folder which is where your grabber's builder is.

**Comment by Blank-c** [comment]
Please reply ASAP or I'd have to mark this issue as stale!

**Comment by Blank-c** [comment]
This issue is related with pyinstaller and is device specific. Try on other device.
