### ISSUE TITLE
Failed loading dll

### ISSUE THREAD

**Issue by Xarond12** [Blank-c/Blank-Grabber#65]
![image](https://user-images.githubusercontent.com/45171942/190922182-e1176d51-1b2e-4bcb-bdde-f5b264ad4ed9.png)

**Comment by Blank-c** [comment]
Built a stub without the vmprotect option and upload it to virustotal. A while later, if you get a notification in your webhook, then it means the grabber is working but it ONLY not working in your PC. In simple term, the grabber will work if you send it to someone.

**Comment by Blank-c** [comment]
@Xarond12 Contact me on discord if you wanna discuss the issue. **Blank?#0886**

**Comment by Blank-c** [comment]
Please reply ASAP, or I'd have to mark this issue as stale.

**Comment by Blank-c** [comment]
This issue is related with pyinstaller and is device specific. Try on other device.
