### ISSUE TITLE
Its not working for windows 11?

### ISSUE THREAD

**Issue by YaGoatt** [Blank-c/Blank-Grabber#66]
Rat not working for windows 11? When I send someone he says he's computer restarting.

**Comment by Blank-c** [comment]
The document says, it works foe win 10

**Comment by YaGoatt** [comment]
> 



> The document says, it works foe win 10

No I build rat and its working for me but the person I want to hack needs to use windows 10?

**Comment by Blank-c** [comment]
yes

**Comment by YaGoatt** [comment]
> yes

Never mind its working for windows 11 but I wanna ask can I take new informations after he open or he have to open the exe again?

**Comment by Blank-c** [comment]
Good for you if it works in win11.

if you selected the startup option and their antivirus didn't remove it from there, you can get the info the next time they start their pc.

otherwise they have to open it again

**Comment by YaGoatt** [comment]
> 

Oh ok thanks for information

**Comment by Blank-c** [comment]
👌 If you don't have further questions, you may close the issue.
