### ISSUE TITLE
Project related 

### ISSUE THREAD

**Issue by Kaizer2256** [Blank-c/Blank-Grabber#67]
Hey bro I want too ask that if u aree in discord then i want too join ur server if any becoz i am having some doubts & i want too know that doo u make Phishing website grabber which which are hosted from webhoost domain & image grabber also iff it is available please tell ...

**Comment by Blank-c** [comment]
I don't make any other than this one. Also my discord contact is in the <a href="https://github.com/Blank-c/Blank-Grabber#how-can-i-contact-you">Readme</a> file

**Comment by Kaizer2256** [comment]
Umm sorry can I get ur discord I'd tag / any server becoz i am unable too find through this

**Comment by Blank-c** [comment]
ye sure, its *Blank?#0886*, you can DM me your questions and I would answer them later.

**Comment by Kaizer2256** [comment]
Okay done i send uu friend request
