### ISSUE TITLE
'virtualenv' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by mrdiploben** [Blank-c/Blank-Grabber#69]
Installed it but isnt working.
![image](https://user-images.githubusercontent.com/81100371/195987805-afb35bb6-3d4b-4940-bdd6-422a0bb620a9.png)

**Comment by Blank-c** [comment]
Looks like you are using an older version. It doesn't use virtual env now. Use the builder instead.

**Comment by mrdiploben** [comment]
Where exactly is the builder?

**Comment by Blank-c** [comment]
the Blank Grabber directory

**Comment by mrdiploben** [comment]
![image](https://user-images.githubusercontent.com/81100371/195987963-de7c73e3-3667-4f30-a14a-5fcd0466c65c.png)
Haven't got that file.

**Comment by Blank-c** [comment]
redownload

**Comment by Blank-c** [comment]
I don't know why, but you got a lot of files missing

**Comment by mrdiploben** [comment]
Agreed. Ill redownload now.

**Comment by Blank-c** [comment]
![image](https://user-images.githubusercontent.com/94945186/195988066-3de503fd-3355-4b4b-808c-45694061fda4.png)
these are the files you should see

**Comment by mrdiploben** [comment]
Reinstalled and now getting this error.
![image](https://user-images.githubusercontent.com/81100371/195988159-dfa00a34-8d2f-46ee-843f-4858a32bf1eb.png)

**Comment by Blank-c** [comment]
Looks like an error in your python app. You need to reinstall it too.

**Comment by mrdiploben** [comment]
Which version do you recommend, im currently on 3.10.

**Comment by Blank-c** [comment]
Check to see if it works
```
python --version
```

**Comment by Blank-c** [comment]
and download the latest

**Comment by mrdiploben** [comment]
Reinstalling, python was working strangely.

**Comment by mrdiploben** [comment]
![image](https://user-images.githubusercontent.com/81100371/195988415-c059f5aa-6242-4bdf-88c2-5e89155aa2a3.png)
Reinstalled, same error

**Comment by Blank-c** [comment]
Are you sure you downloaded the correct exe for your architecture?

**Comment by mrdiploben** [comment]
Im on x64.

**Comment by mrdiploben** [comment]
It works on other scripts just not that one.

**Comment by Blank-c** [comment]
Maybe your can check this out: https://stackoverflow.com/questions/11638562/python-64-bit-unable-to-start-correctly-0xc00000cc-on-windows-hpc

or use a free VPS: https://app.apponfly.com/trial

**Comment by mrdiploben** [comment]
Would it be good to compile it on a self hosted vm?

**Comment by Blank-c** [comment]
> Would it be good to compile it on a self hosted vm?

ye if it support python

**Comment by mrdiploben** [comment]
Alright ill compile it on my development vm with python working, i hope it will work.

**Comment by mrdiploben** [comment]
Okay built it on my vm and its working perfectly. Thanks for the support.

**Comment by Blank-c** [comment]
glad to know!
