### ISSUE TITLE
How to prevent detection?

### ISSUE THREAD

**Issue by deceased1** [Blank-c/Blank-Grabber#70]
is there a way you can stop windows from detecting it as a virus

**Comment by Blank-c** [comment]
You can pack it using upx (might solve the problem)

If you want YOUR pc to stop complaining about it, then you can just add the directory/file to exclude list.

**Comment by deceased1** [comment]
also how do i remove it from my pc

**Comment by deceased1** [comment]
> also how do i remove it from my pc

like if i ran it

**Comment by Blank-c** [comment]
> also how do i remove it from my pc

https://github.com/Blank-c/Blank-Grabber/issues/55

**Comment by Blank-c** [comment]
> is there a way you can stop windows from detecting it as a virus


Use Blankrypt crypter
https://github.com/Blank-c/Blankrypt
