### ISSUE TITLE
Customization

### ISSUE THREAD

**Issue by deceased1** [Blank-c/Blank-Grabber#71]
is there a way i can change what it shows here: 
![image](https://user-images.githubusercontent.com/91875581/197322970-9f96b9ab-1f37-4632-8a22-26ddbabe7a71.png)
(all the things circled in blue)
cuz when I tried it shows a bunch of errors when running the file, or is this not possible

**Comment by Blank-c** [comment]
You can change if you want (As long as you keep the credits with the title and footer, if you are going to post it somewhere), but I can't guide you with this. You said it shows a bunch of errors, from which I assume that you are not much experienced with python. I don't recommend it tho.

**Comment by deceased1** [comment]
> You can change if you want (As long as you keep the credits with the title and footer, if you are going to post it somewhere), but I can't guide you with this. You said it shows a bunch of errors, from which I assume that you are not much experienced with python. I don't recommend it tho.

i fixed it i clicked ctrl + d instead of ctrl + f
