### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by schwungvoll** [Blank-c/Blank-Grabber#72]
it's only showing IP n stuff...

**Comment by Blank-c** [comment]
Can you send a screemshot? Can you try it on another machine too.

**Comment by Blank-c** [comment]
@schwungvoll

**Comment by schwungvoll** [comment]
yeah yeah sorry will do it in a few mins

**Comment by schwungvoll** [comment]
![image](https://user-images.githubusercontent.com/96620548/197387326-56636951-bfd2-494c-bcf2-9fbcf1258156.png)
there

**Comment by schwungvoll** [comment]
no file and not even a token, please fix that and I would like it if you make eg the token, phone and credit cards, nitro codes and IP, roblox cookies to a spoiler like ||178.92.167.43|| thanks!

**Comment by Blank-c** [comment]
Please try it on a vm or other pc to see if its working or not.

**Comment by schwungvoll** [comment]
I don't have another pc lol

**Comment by Blank-c** [comment]
try on a free vm (ex appsonfly vm)

**Comment by schwungvoll** [comment]
lmao I dont know how to do that xdd

**Comment by Blank-c** [comment]
do one thing, delete the env folder (if any) and open `.../data/convert.bat` file in notepad and remove ` --noconsole` (yes include the space too. and then create the grabber and run it. If it prints something, then send the screenshot.

**Comment by schwungvoll** [comment]
nvm grabbed n nuked some assys, I just have a few ideas: make it more undetected, use emojis and make a better structure, tell about the payment methods if there are payment methods on an account

**Comment by schwungvoll** [comment]
works fine really good grabber but just make it more undetected please and show us if he/she has nitro and the nitro gift codes and the ntiro codes and injection and better structure yeah

**Comment by schwungvoll** [comment]
thanks for ur time :)

**Comment by Blank-c** [comment]
> nvm grabbed n nuked some assys, I just have a few ideas: make it more undetected, use emojis and make a better structure, tell about the payment methods if there are payment methods on an account.

Ye I am constantly trying to make it undetected and smaller in size. Just keep supporting me like this ;)
