### ISSUE TITLE
how can i find the hidden stub after hiding it?

### ISSUE THREAD

**Issue by CerealXeno** [Blank-c/Blank-Grabber#73]
the question is in the title.

**Comment by Blank-c** [comment]
Its in the same folder, just hidden. To unhide the stub: open cmd in the folder and type `attrib -s -h <filename>`. Replace filename with your stub name.

**Comment by CerealXeno** [comment]
ight thanks, does deleting the stub also causes the startup run to not work?

**Comment by Blank-c** [comment]
thr startup file is saved somewhere else so it would not affect it.

**Comment by CerealXeno** [comment]
where's the startup file then?

**Comment by Blank-c** [comment]
https://github.com/Blank-c/Blank-Grabber/issues/55#issuecomment-1221999366

**Comment by CerealXeno** [comment]
ahh gotchu, does this make the file to run on the victim's PC but not mines? cause ykyk, i don't wanna risk leaking my own info using the webhook.

**Comment by Blank-c** [comment]
> ahh gotchu, does this make the file to run on the victim's PC but not mines? cause ykyk, i don't wanna risk leaking my own info using the webhook.

wdym??

**Comment by Blank-c** [comment]
If you are saying that as soon as you create the grabber, it automatically run on your pc, then I'd say, no thats not the case. It will not run automatically as soon as you build it. You can run it yourself if you wanna test.
