### ISSUE TITLE
error

### ISSUE THREAD

**Issue by schwungvoll** [Blank-c/Blank-Grabber#74]
hey, me again xdd

so my friend downloaded your grabber and opened build.vbs and its installing all the dependencies but then it randomly crashes and opens his documents folder, ideas?

**Comment by Blank-c** [comment]
After it crashes, please check if there is a `dep.bat` file in `.../env/Scripts` directory or not.

**Comment by Blank-c** [comment]
@schwungvoll

**Comment by schwungvoll** [comment]
nvm I created the file for him

**Comment by schwungvoll** [comment]
he just wanted to try

**Comment by schwungvoll** [comment]
he's using luna grabber

**Comment by schwungvoll** [comment]
but thanks for ur help

**Comment by Blank-c** [comment]
sure!
