### ISSUE TITLE
Invalid webhook and all previously made grabbers dont work

### ISSUE THREAD

**Issue by EssentialModDevelopment** [Blank-c/Blank-Grabber#76]
I tried with several different  webhooks

**Comment by Blank-c** [comment]
Make sure your webhook starts with `http://` or `https://`

Try to run the grabber on different PC

**Comment by Blank-c** [comment]
Also try to run without <kbd>VMPROTECT</kbd>

**Comment by Blank-c** [comment]
@EssentialModDevelopment

**Comment by Blank-c** [comment]
It works perfectly, I tried on different machines.
