### ISSUE TITLE
sad...

### ISSUE THREAD

**Issue by Lier0102** [Blank-c/Blank-Grabber#77]
grabber doesn't grab tokens.
help me....

**Comment by Blank-c** [comment]
Are you using discord app or browser for logging into discord?

**Comment by Lier0102** [comment]
yep

**Comment by Blank-c** [comment]
which one?
Also, is there an error logs.txt file?

**Comment by Blank-c** [comment]
@Lier0102 Reopen if the issue is still there. It works perfectly well otherwise.
