### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by turkishdude** [Blank-c/Blank-Grabber#79]
If i try to build a file it just closes and goes to documents

**Comment by Blank-c** [comment]
Can you tell me if there is a file named `dep.bat` in `.../Blank Grabber/env/Scripts/``` path??

**Comment by turkishdude** [comment]
> Can you tell me if there is a file named `dep.bat` in `.../Blank Grabber/env/Scripts/` path??

there isnt

**Comment by Blank-c** [comment]
you sure? then find `convert.bat` file in the same folder and replace every `cls` and `exit` with `pause`. and then run the `run.bat` file. And send me the screenshot.

**Comment by Blank-c** [comment]
Reopen if the issue is still there.
