### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by deceased1** [Blank-c/Blank-Grabber#81]
grab chrome source code so u can get their session

**Comment by Blank-c** [comment]
source code? What do you mean by that?

**Comment by bruh-bruh8** [comment]
💀

**Comment by Blank-c** [comment]
> 💀

Did you understand what he mean?

**Comment by Blank-c** [comment]
Please reopen this issue with explaination of the suggestion

**Comment by deceased1** [comment]
> Please reopen this issue with explaination of the suggestion

I'm not completely sure myself but i saw something a while ago where you could steal someones chrome sessions, so you wouldnt have to log into anything it'd just have the tabs they had open with all their cookies and logins already input

**Comment by Blank-c** [comment]
> > Please reopen this issue with explaination of the suggestion
> 
> I'm not completely sure myself but i saw something a while ago where you could steal someones chrome sessions, so you wouldnt have to log into anything it'd just have the tabs they had open with all their cookies and logins already input

Oh that can be cool, if you get more info, please feel free to write about it here.
