### ISSUE TITLE
.EXE file created but, can't be executed

### ISSUE THREAD

**Issue by vanjusa** [Blank-c/Blank-Grabber#83]
![Capture](https://user-images.githubusercontent.com/115928455/201545775-f956df02-769c-489c-944f-1168facb06f0.PNG)
Please, can you solve this problem?

**Comment by Blank-c** [comment]
> ![Capture](https://user-images.githubusercontent.com/115928455/201545775-f956df02-769c-489c-944f-1168facb06f0.PNG) Please, can you solve this problem?

Doesn't works on windows 7. I have already stated that in the readme
