### ISSUE TITLE
Add Discord Injection

### ISSUE THREAD

**Issue by RGB-PANZER** [Blank-c/Blank-Grabber#86]

**Comment by Blank-c** [comment]
Yes, I am thinking about whether to do it or not. The reason that I haven't added it is that I have tried discord injection a couple of times and it broke the discord app. The app show javascript error and tries to restart just to show the error again + nothing gets sent to the webhook. Also if we do this, then it would be so much easier for someone to find the webhook. He would just have to open the file in an editor and there is our webhook, in plain text.

**Comment by RGB-PANZER** [comment]
You could add it as optional feature

**Comment by Blank-c** [comment]
Added
