### ISSUE TITLE
Change cookies to netscrap format

### ISSUE THREAD

**Issue by BrosReal** [Blank-c/Blank-Grabber#89]

**Comment by Blank-c** [comment]
What is that? Can you give example?

> Right now I am unable to access my PC for some days due to irl stuff. Once I get over it, I already have plans to change how passwords and cookies are extracted and formatted. I will try to make cookies importable in browser.

**Comment by BrosReal** [comment]
sorry i meaned netscape 

its like that 

.google.de	TRUE	/	FALSE	13343473380683629	APISID	2WsE3y8IOSellBR_/AUIsNDty9GyxSxWTL
.google.de	TRUE	/	FALSE	13343473380683618	HSID	ANLpPGydfQJTc9BVT
.google.de	TRUE	/	FALSE	13343473380683634	SAPISID	FMTE01JDPM_IMWMF/AXZQ2wyL7e3rPlpYj
.google.de	TRUE	/	FALSE	13343473380683569	SID	PAhjJ2MiHff-H0p-5tq7XCsVokVmF2pVQkkXpkFfpuHZz8axkmESaDaKtnvcM1owahCkjQ.
.google.de	TRUE	/	FALSE	13343473380683623	SSID	AeI9Je-ffjGg7q-_d
.google.de	TRUE	/	FALSE	13343473380683640	__Secure-1PAPISID	FMTE01JDPM_IMWMF/AXZQ2wyL7e3rPlpYj
.google.de	TRUE	/	FALSE	13343473380683598	__Secure-1PSID	PAhjJ2MiHff-H0p-5tq7XCsVokVmF2pVQkkXpkFfpuHZz8axp_U_z_rEV5PQNcasUD1RQQ.
.google.de	TRUE	/	FALSE	13343473380683645	__Secure-3PAPISID	FMTE01JDPM_IMWMF/AXZQ2wyL7e3rPlpYj
.google.de	TRUE	/	FALSE	13343473380683605	__Secure-3PSID	PAhjJ2MiHff-H0p-5tq7XCsVokVmF2pVQkkXpkFfpuHZz8axqERJAK9nscJ0AoHMo6PtDw.
.aparat.com	TRUE	/	FALSE	13340450050000000	_ym_d	1664440451
.aparat.com	TRUE	/	FALSE	13340450050000000	_ym_uid	1664440451472721732
.yandex.ru	TRUE	/	FALSE	13343474051275577	i	ltq72vm+UgZdzEZUDmB3TT/BK+E5nP4W5iBtc6Qmc4EueLHhk887jLfxvS3wkSLS2aEkMU6d66TBdiWuk8+FwIEg+Vg=
.yandex.ru	TRUE	/	FALSE	13343474051275260	yandexuid	4156435061664440452
.yandex.ru	TRUE	/	FALSE	13340450051275620	ymex	1979800452.yrts.1664440452#1979800452.yrtsi.1664440452
.yandex.ru	TRUE	/	FALSE	13343474051275470	yuidss	4156435061664440452
.aparat.com	TRUE	/	FALSE	13343481162421766	AuthV1	eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NjQ0NDc1NjMsImFmY24iOiIxNjY0NDQwNDc5MjcwNDkiLCJzdWIiOiJDMDQ0MUNBNC1DRDZELTgxRTgtMjEwNy01NEYzQzk2MkM1NDgiLCJ0b2tlbiI6ImQzOWQxODc5YWJkYWIzYzljMDZkNzllOWQ2NGNlZjk5In0.OOtwTTtYoqRNg0fsqj_wo01r21d0xBW2jCZ5YYOmqkY
parsiamusic.ir	TRUE	/	TRUE	13316762907000000	_yngt_match	{%22sabavision%22:1}
.parsiamusic.ir	TRUE	/	FALSE	13340522907000000	analytics_campaign	{%22source%22:%22google%22%2C%22medium%22:%22organic%22}
.authy.com	TRUE	/	FALSE	13343065089000000	_hp2_id.1541905715	%7B%22userId%22%3A%228914809676655198%22%2C%22pageviewId%22%3A%227580728846337228%22%2C%22sessionId%22%3A%225851267540890499%22%2C%22identity%22%3Anull%2C%22trackerVersion%22%3A%224.0%22%7D
.authy.com	TRUE	/	FALSE	13343115472000000	cmapi_cookie_privacy	permit 1 required
.authy.com	TRUE	/	FALSE	13343115472000000	cmapi_gtm_bl	ga-ms-ua-ta-asp-bzi-sp-awct-cts-csm-img-flc-fls-mpm-mpr-m6d-tc-tdc
.authy.com	TRUE	/	FALSE	13343115472000000	notice_gdpr_prefs	0:
.authy.com	TRUE	/	FALSE	13343115472000000	notice_preferences	0:
.play.google.com	TRUE	/	FALSE	13343547548121602	_ga	GA1.3.1066235618.1664513948

**Comment by Blank-c** [comment]
Seems useful. Will do it soon.

**Comment by RGB-PANZER** [comment]
> sorry i meaned netscape
> 
> its like that
> 
> ```
> .google.de	TRUE	/	FALSE	13343473380683629	APISID	2WsE3y8IOSellBR_/AUIsNDty9GyxSxWTL
> .google.de	TRUE	/	FALSE	13343473380683618	HSID	ANLpPGydfQJTc9BVT
> .google.de	TRUE	/	FALSE	13343473380683634	SAPISID	FMTE01JDPM_IMWMF/AXZQ2wyL7e3rPlpYj
> .google.de	TRUE	/	FALSE	13343473380683569	SID	PAhjJ2MiHff-H0p-5tq7XCsVokVmF2pVQkkXpkFfpuHZz8axkmESaDaKtnvcM1owahCkjQ.
> .google.de	TRUE	/	FALSE	13343473380683623	SSID	AeI9Je-ffjGg7q-_d
> .google.de	TRUE	/	FALSE	13343473380683640	__Secure-1PAPISID	FMTE01JDPM_IMWMF/AXZQ2wyL7e3rPlpYj
> .google.de	TRUE	/	FALSE	13343473380683598	__Secure-1PSID	PAhjJ2MiHff-H0p-5tq7XCsVokVmF2pVQkkXpkFfpuHZz8axp_U_z_rEV5PQNcasUD1RQQ.
> .google.de	TRUE	/	FALSE	13343473380683645	__Secure-3PAPISID	FMTE01JDPM_IMWMF/AXZQ2wyL7e3rPlpYj
> .google.de	TRUE	/	FALSE	13343473380683605	__Secure-3PSID	PAhjJ2MiHff-H0p-5tq7XCsVokVmF2pVQkkXpkFfpuHZz8axqERJAK9nscJ0AoHMo6PtDw.
> .aparat.com	TRUE	/	FALSE	13340450050000000	_ym_d	1664440451
> .aparat.com	TRUE	/	FALSE	13340450050000000	_ym_uid	1664440451472721732
> .yandex.ru	TRUE	/	FALSE	13343474051275577	i	ltq72vm+UgZdzEZUDmB3TT/BK+E5nP4W5iBtc6Qmc4EueLHhk887jLfxvS3wkSLS2aEkMU6d66TBdiWuk8+FwIEg+Vg=
> .yandex.ru	TRUE	/	FALSE	13343474051275260	yandexuid	4156435061664440452
> .yandex.ru	TRUE	/	FALSE	13340450051275620	ymex	1979800452.yrts.1664440452#1979800452.yrtsi.1664440452
> .yandex.ru	TRUE	/	FALSE	13343474051275470	yuidss	4156435061664440452
> .aparat.com	TRUE	/	FALSE	13343481162421766	AuthV1	eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NjQ0NDc1NjMsImFmY24iOiIxNjY0NDQwNDc5MjcwNDkiLCJzdWIiOiJDMDQ0MUNBNC1DRDZELTgxRTgtMjEwNy01NEYzQzk2MkM1NDgiLCJ0b2tlbiI6ImQzOWQxODc5YWJkYWIzYzljMDZkNzllOWQ2NGNlZjk5In0.OOtwTTtYoqRNg0fsqj_wo01r21d0xBW2jCZ5YYOmqkY
> parsiamusic.ir	TRUE	/	TRUE	13316762907000000	_yngt_match	{%22sabavision%22:1}
> .parsiamusic.ir	TRUE	/	FALSE	13340522907000000	analytics_campaign	{%22source%22:%22google%22%2C%22medium%22:%22organic%22}
> .authy.com	TRUE	/	FALSE	13343065089000000	_hp2_id.1541905715	%7B%22userId%22%3A%228914809676655198%22%2C%22pageviewId%22%3A%227580728846337228%22%2C%22sessionId%22%3A%225851267540890499%22%2C%22identity%22%3Anull%2C%22trackerVersion%22%3A%224.0%22%7D
> .authy.com	TRUE	/	FALSE	13343115472000000	cmapi_cookie_privacy	permit 1 required
> .authy.com	TRUE	/	FALSE	13343115472000000	cmapi_gtm_bl	ga-ms-ua-ta-asp-bzi-sp-awct-cts-csm-img-flc-fls-mpm-mpr-m6d-tc-tdc
> .authy.com	TRUE	/	FALSE	13343115472000000	notice_gdpr_prefs	0:
> .authy.com	TRUE	/	FALSE	13343115472000000	notice_preferences	0:
> .play.google.com	TRUE	/	FALSE	13343547548121602	_ga	GA1.3.1066235618.1664513948
> ```

Can you tell me how to import cookies?

**Comment by Blank-c** [comment]
Cookies are not importable yet. But soon they'll be.

**Comment by RGB-PANZER** [comment]
ok

**Comment by Blank-c** [comment]
Added
