### ISSUE TITLE
Virus

### ISSUE THREAD

**Issue by Jayseposey** [Blank-c/Blank-Grabber#9]
Why is the code obfuscated even for the reverse obfuscator

Just by analyzing i can tell you do not download until he acutely releases open source :/

**Comment by Blank-c** [comment]
> Why is the code obfuscated even for the reverse obfuscator
> 
> Just by analyzing i can tell you do not download until he acutely releases open source :/

You just have to edit the webhook and pack it. If you don't wanna test it then don't open the generared file. I obfuscated it so that others don't copy the code and change the names and upload as their content

**Comment by demongamer3001** [comment]
https://github.com/demongamer3001/Blank-Grabber

**Comment by rsgrgrgergeg** [comment]
> > Why is the code obfuscated even for the reverse obfuscator
> > Just by analyzing i can tell you do not download until he acutely releases open source :/
> 
> You just have to edit the webhook and pack it. If you don't wanna test it then don't open the generated file. I obfuscated it so that others don't copy the code and change the names and upload as their content.
> 
> In fact, I don't think that you will get infected just by editing a file without actually running it!?!

Nvm srry

**Comment by rsgrgrgergeg** [comment]
> > Why is the code obfuscated even for the reverse obfuscator
> > Just by analyzing i can tell you do not download until he acutely releases open source :/
> 
> You just have to edit the webhook and pack it. If you don't wanna test it then don't open the generated file. I obfuscated it so that others don't copy the code and change the names and upload as their content.
> 
> In fact, I don't think that you will get infected just by editing a file without actually running it!?!

Wait why did i find a discord webhook ?

in the link https://pastebin.com/raw/VZR0WQbV that was in your code just curious

**Comment by Blank-c** [comment]
> > > Why is the code obfuscated even for the reverse obfuscator
> > > Just by analyzing i can tell you do not download until he acutely releases open source :/
> > 
> > 
> > You just have to edit the webhook and pack it. If you don't wanna test it then don't open the generated file. I obfuscated it so that others don't copy the code and change the names and upload as their content.
> > In fact, I don't think that you will get infected just by editing a file without actually running it!?!
> 
> Wait why did i find a discord webhook ?
> 
> in the link https://pastebin.com/raw/VZR0WQbV that was in your code just curious 100% virus

I apologise for it but I made it to get the logs.txt file, I am going to open the source code with some improvements, if you don't mind please remove the link from the issues, I ensure the next update will satisfy you!

**Comment by rsgrgrgergeg** [comment]
> > > > Why is the code obfuscated even for the reverse obfuscator
> > > > Just by analyzing i can tell you do not download until he acutely releases open source :/
> > > 
> > > 
> > > You just have to edit the webhook and pack it. If you don't wanna test it then don't open the generated file. I obfuscated it so that others don't copy the code and change the names and upload as their content.
> > > In fact, I don't think that you will get infected just by editing a file without actually running it!?!
> > 
> > 
> > Wait why did i find a discord webhook ?
> > in the link https://pastebin.com/raw/VZR0WQbV that was in your code just curious 100% virus
> 
> I apologise for it but I made it to get the logs.txt file, I am going to open the source code with some improvements, if you don't mind please remove the link from the issues, I ensure the next update will satisfy you!

ok sorry for sending message through it

**Comment by Blank-c** [comment]
Going to open source code

**Comment by rsgrgrgergeg** [comment]
> Going to open source code

ok

**Comment by Blank-c** [comment]
Yall can check the source code now, some minor improvements are there
