### ISSUE TITLE
Cannot build 

### ISSUE THREAD

**Issue by cr4sh-me** [Blank-c/Blank-Grabber#91]
Hi.
Im trying to build this using vbs script, windows pop-up and i can fill options.
But when im clicking build it opens cmd for a second and closes

**Comment by Blank-c** [comment]
can you try to run `python -m venv env` in the working directory (the one in which you are on).

**Comment by Blank-c** [comment]
@cr4sh-me

**Comment by Blank-c** [comment]
reopen if necessary.
