### ISSUE TITLE
when someone trys to run the rat

### ISSUE THREAD

**Issue by EssentialModDevelopment** [Blank-c/Blank-Grabber#93]
![image](https://user-images.githubusercontent.com/112744518/206957450-bec080c1-4556-4cc7-b436-fff9c563bf6f.png)

**Comment by Blank-c** [comment]
This is a pyinstaller issue. Some fixes that might fix this:

1) Make sure you have installed exactly Python 3.11.0.

2) Try to build the grabber in another PC or VM ([Try this free online VM](https://app.apponfly.com/trial))

**Comment by EssentialModDevelopment** [comment]
fixed
