### ISSUE TITLE
detection

### ISSUE THREAD

**Issue by RGB-PANZER** [Blank-c/Blank-Grabber#94]
Can you make it that discord dont detect it as a virus?
![image](https://user-images.githubusercontent.com/107210641/207672791-ec51da7f-4ea9-46e6-89c8-cae4b09ef84c.png)

**Comment by Blank-c** [comment]
What you might do is, delete your `env` directory (if any in the builder's directory) and then in the data folder delete the pyinstaller folder and edit the `dep.bat` and remove [these lines](https://github.com/Blank-c/Blank-Grabber/blob/main/Blank%20Grabber/Data/dep.bat#L16-L18) and replace them with `python -m pip --upgrade pyinstaller`.

OR

You can zip the file with password and then send it.

**Comment by RGB-PANZER** [comment]
okay thanks
