### ISSUE TITLE
Camera stealer not working

### ISSUE THREAD

**Issue by malcikin** [Blank-c/Blank-Grabber#96]
the program does not work properly camera.exe comes to task manager and does not work until I close it manually how to i close camera stealer?

**Comment by Blank-c** [comment]
The camera stealer seems not to work on some PCs, so if you want to turn it off. First delete the `env` folder (if any) and then edit the main.py file in Data folder and set [this line](https://github.com/Blank-c/Blank-Grabber/blob/main/Blank%20Grabber/Data/main.py#L40) to `False`

**Comment by Blank-c** [comment]
no response; reopen if needed
