### ISSUE TITLE
Undo Changes made by running Blank Grabber on my PC

### ISSUE THREAD

**Issue by dr-dark-flames** [Blank-c/Blank-Grabber#97]
how i can i remove or undo changes that r made by running blank grabber on my pc?
I ran it and ive only noticed that the anti virus turned off and i got a notification that says restart ur pc to confirm changes made to ur pc (idk what changes).

**Comment by Blank-c** [comment]
It does not make any new change, thats probably your antivirus or something

**Comment by Blank-c** [comment]
Reopen if necessary.
