### ISSUE TITLE
"Built.exe" does not open.

### ISSUE THREAD

**Issue by Neceptus** [Blank-c/Blank-Grabber#98]
I did everything necessary. I got Python 3, and all that. My antivirus is turned off aswell. Despite all of that, when i try to run the thing, it does not open. Could you help me with this? 
![ooh ahh](https://user-images.githubusercontent.com/121766887/210181569-6f155f7a-c323-46bd-be54-c74669ff36a3.PNG)

**Comment by Blank-c** [comment]
Can you recreate the grabber but this time, disable the VMPROTECT option.

**Comment by Blank-c** [comment]
no response; reopen if needed
