### ISSUE TITLE
build.exe isn't opening

### ISSUE THREAD

**Issue by ANAME593** [Blank-c/Blank-Grabber#99]
when i attempt to open build.exe a blank screen appears and closes, whats causing this

**Comment by Blank-c** [comment]
Can you give more details, like
- Is the screen black? If so, can you open `cmd` in the executable's directory and then enter its name. What happen when you open it this way?
- For how long does the screen stay there?
- Are there any errors popping up?
- A video can be the best proof.

**Comment by Blank-c** [comment]
Please continue it in the following thread

Duplicate of #98
